### ISSUE TITLE
Unable to exec into pods created in kind cluster

### ISSUE THREAD

**Issue by itsnagaraj** [kubernetes-sigs/kind#3598] opened 2024-05-01 05:14 UTC
**What happened**:

Recently upgraded kind cluster that was used for integration tests 

Old version: `kindest/node:v1.27.1@sha256:b7d12ed662b873bd8510879c1846e87c7e676a79fefc93e17b2a52989d3ff42b` that was pre-built KIND v0.19.0.
New version: `kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245` that was pre-built using KIND v0.22.0

One of the workload that we run in the cluster is localstack with poststart hook and this started failing in the new version.
To determine the root cause I removed the postStart hook and tried to perform exec and that command failed with below error message

```
k exec -it providers-aws-stub-fdf6849b5-6xjsh -- cat /tmp
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "fb80eb029de4079f10ea6a7c60a0280b54f4e430e8911b33d834ff53b99eb60b": OCI runtime exec failed: exec failed: unable to start container process: error adding pid 3994 to cgroups: failed to write 3994: openat2 /sys/fs/cgroup/unified/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-burstable.slice/kubelet-kubepods-burstable-podd2734a06_8f12_489c_b5c9_572953b25715.slice/cri-containerd-bc7a5f5a7e45b166f660229b74dc271a33136f120291e685047f7d7c5c9c2759.scope/cgroup.procs: no such file or directory: unknown
```

**What you expected to happen**:
To be able to exec into the pod and determine the root cause

**How to reproduce it (as _minimally_ and precisely as possible)**:
- create kind cluster using kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
- Run localstack using  below manifest k apply -f localstack.yml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: providers-aws-stub
spec:
  progressDeadlineSeconds: 1200
  replicas: 1
  selector:
    matchLabels:
      app: providers-aws-stub
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: providers-aws-stub
        environment: local
        scheduler: "true"
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          value: EXAMPLE
        - name: AWS_SECRET_ACCESS_KEY
          value: EXAMPLE
        - name: AWS_DEFAULT_REGION
          value: ap-southeast-2
        - name: LOCALSTACK_HOST
          value: providers-aws-stub
        - name: LOCALSTACK_SERVICES
          value: dynamodb,sqs,sns,s3
        - name: START_WEB
          value: "0"
        image: localstack/localstack:3.4
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /_localstack/health
            port: 4566
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: localstack
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /_localstack/health
            port: 4566
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2
            ephemeral-storage: 2048Mi
            memory: 1024Mi
          requests:
            cpu: 800m
            ephemeral-storage: 1536Mi
            memory: 512Mi
```
- `kubectl exec -it <podname> bash` and this failed with error message that was shared earlier

**Anything else we need to know?**: NA

**Environment:** 
- kind version: (use `kind version`): `kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245` that was pre-built using KIND v0.22.0
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`):
```
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/local/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0
    Path:     /usr/local/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7880925980b188f4c97b462f709d0db8e8962aff
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.10.210-201.855.amzn2.x86_64
 Operating System: Alpine Linux v3.18 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 61.77GiB
 Name: kind-pod
 ID: 315648d0-0e16-4069-9eae-0ffd33799fee
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- OS (e.g. from `/etc/os-release`): Details are from the kind node itself
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.4
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

Details of host operating system
```
 Operating System: Amazon Linux 2
CPE OS Name: cpe:2.3:o:amazon:amazon_linux:2
Kernel: Linux 5.10.210-201.855.amzn2.x86_64
Architecture: x86-64
```
- Kubernetes version: (use `kubectl version`): 1.29.2
- Any proxies or other special environment settings?:

**Comment by aojea** [comment] 2024-05-01 06:59
duplicate of https://github.com/kubernetes-sigs/kind/issues/3340

It seems amazon linux 2 is EOL and it is fixed in the new OS version

**Closed by aojea** 2024-05-01 06:59 UTC
Labels: kind/bug

**Comment by itsnagaraj** [comment] 2024-05-01 09:11
@aojea Given that EOL has been extended up to 2025 to allow organisations to migrate, are there any plans to support kind on older linux kernel versions

Ref: https://aws.amazon.com/amazon-linux-2/faqs/
```
Q. When will support for Amazon Linux 2 end?

Amazon Linux 2 end of support date (End of Life, or EOL) has been extended by two years from 2023-06-30 to 2025-06-30 to provide customers with ample time to migrate to the next version.
````

**Comment by BenTheElder** [comment] 2024-05-01 18:57
We do not specifically provide support for Amazon Linux and I don't see why we should.

**Comment by itsnagaraj** [comment] 2024-05-02 00:30
My request was not specific to providing support for Amazon Linux but to provide support older kernel versions.

But I understand if this is not feasible.

**Comment by aojea** [comment] 2024-05-02 08:48
> But I understand if this is not feasible.

the main problem is that first evaluations to solve the problem seems that there is a lot of work specially with the latest announcements of systemd removing cgroupsv1 support, so the spectrum of users/systems to support will be one order of magnitude larger.
We can always evaluate if people come with a solution that is simple and easy to support, but does not seem the case

**Comment by BenTheElder** [comment] 2024-05-02 19:32
>  to provide support older kernel versions.

I mean, this could get arbitrarily old, we're targeting pretty similar things to projects like the core Kubernetes repo, which is not testing on AL2 but instead AL2023.

Unfortunately the ecosystem continues to move and we have limited resources to work on things that even the rest of the ecosystem around us is not really supporting.

Given that AL2023 is available, and kind should NOT be used in production, I would recommend upgrading to run devel/test environments on AL2023 or similar.

We're willing to review proposals related to specific fixes but I only have so much time to spend here versus anywhere else in the Kubernetes organization and targeting issues that crop up on outdated commercial distros isn't how I personally want to invest time and we're not seeing others pitch in here.
