### ISSUE TITLE
Unable to create kind cluster after upgrading kind to kind v0.20.0 go1.20.5 darwin/arm64

### ISSUE THREAD

**Issue by mukulgit123** [kubernetes-sigs/kind#3347] opened 2023-09-02 06:01 UTC
**What happened**:

Unable to create kind cluster after upgrading kind to kind v0.20.0 go1.20.5 darwin/arm64.

Getting errors as displayed below while trying to create the cluster.

Creating cluster "bakery-local" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
 ✗ Preparing nodes 📦  
ERROR: failed to create cluster: command "docker run --name bakery-local-control-plane --hostname bakery-local-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER --detach --tty --label io.x-k8s.kind.cluster=bakery-local --net kind --restart=on-failure:1 --init=false --cgroupns=private --publish=127.0.0.1:54274:6443/TCP -e KUBECONFIG=/etc/kubernetes/admin.conf kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72" failed with error: exit status 125
Command Output: 869f32b1a9b1871ac273602705ca582952131153b7d06bf7ec437580b60597e0
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "cgroup" to rootfs at "/sys/fs/cgroup" caused: invalid argument: unknown.

**What you expected to happen**:

Expected the kind cluster to be created which was working before upgrading.

**How to reproduce it (as _minimally_ and precisely as possible)**:

Install colima on a macOS and install kind on top of it. Try creating a kind cluster afterwards.

**Anything else we need to know?**:

It was working before the upgrade. 

**Environment:**

- kind version: v0.20.0 go1.20.5 darwin/arm64
- Runtime info: 
Client:
 Context:    colima
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 34
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e5ef943eb76627a6d3b6de8cd1ef6537f393a71
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: 
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.109-0-virt
 Operating System: Alpine Linux v3.14
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.757GiB
 Name: colima
 ID: 5VV4:ZUWX:JMHI:SCTD:7B6T:AFXT:TLAR:EU65:XOTX:TUA4:2GEH:RHI4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: mukuldoc
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

- OS: MacOS Ventura 13.2.1 (22D68)

- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}

**Comment by aojea** [comment] 2023-09-02 19:59
Duplicate of https://github.com/kubernetes-sigs/kind/issues/3277

**Closed by aojea** 2023-09-02 19:59 UTC
Labels: kind/bug
