### ISSUE TITLE
zsh completions throws an error

### ISSUE THREAD

**Issue by jecnua** [kubernetes-sigs/kind#719] opened 2019-07-18 08:52 UTC
Hi all,

**What happened**:

The kind zsh completions throws and error when you try to use it.

**What you expected to happen**:

I expect the completions to work :)

**How to reproduce it (as minimally and precisely as possible)**:

```
kind completion zsh > /usr/local/share/zsh/site-functions/_kind
autoload -U compinit && compinit
kind<TAB>
```

**Environment:**

- kind version: (use `kind version`): v0.3.0
- Kubernetes version: (use `kubectl version`): v1.15.0
- Docker version: (use `docker info`): 19.03.0-rc2
- OS (e.g. from `/etc/os-release`): Darwin xxx 18.6.0 Darwin Kernel Version 18.6.0

```
zsh --version
zsh 5.3 (x86_64-apple-darwin18.0)
```

```
brew info zsh-completions
zsh-completions: stable 0.30.0, HEAD
```

Let me know if I can help with more info.

**Comment by aojea** [comment] 2019-07-18 09:08
is this a duplicate of https://github.com/kubernetes-sigs/kind/issues/522?

**Comment by jecnua** [comment] 2019-07-18 09:10
No. I have read the other ticket before. That is just asking for a way to source the autocomplete in zsh :) This problem I have is following the normal way that is shown in:

`kind completion -h`

**Comment by BenTheElder** [comment] 2019-07-18 16:34
This is unfortunate. The zsh completions are auto generated by a dependency (https://github.com/spf13/cobra), I think they've been generally problematic upstream :/

**Comment by BenTheElder** [comment] 2019-08-16 22:45
ref: https://github.com/kubernetes-sigs/kind/pull/729

**Comment by BenTheElder** [comment] 2019-09-08 18:55
I think https://github.com/kubernetes-sigs/kind/pull/729 documented this (please correct me, I don't use zsh...)

**Closed by BenTheElder** 2019-09-08 18:55 UTC
Labels: kind/bug
