### ISSUE TITLE
Failed to start control plane on btrfs in Fedora 35

### ISSUE THREAD

**Issue by ukazap** [kubernetes-sigs/kind#2555] opened 2021-11-26 04:16 UTC
**What happened**: When creating a cluster, starting the control plane failed.

**What you expected to happen**: Cluster created successfully.

**How to reproduce it (as minimally and precisely as possible)**:  Run `kind create cluster`

**Anything else we need to know?**:

I'm running Fedora 35 with luks encrypted btrfs.

There appears to be an issue with ContainerManager in the kubelet.log:

```
Nov 26 03:51:21 kind-control-plane kubelet[978]: W1126 03:51:21.216180     978 fs.go:588] stat failed on /dev/mapper/luks-0b25d656-ca59-4fa3-8470-dcb0752b7751 with error: no such file or directory
Nov 26 03:51:21 kind-control-plane kubelet[978]: E1126 03:51:21.216207     978 kubelet.go:1384] "Failed to start ContainerManager" err="failed to get rootfs info: failed to get device for dir \"/var/lib/kubelet\": could not find device with major: 0, minor: 39 in cached partitions map"
```

Additional logs: https://gist.github.com/ukazap/13acef5eebb8aa06413bc58698e7426e

**Environment:**

- kind version: (use `kind version`): kind v0.11.1 go1.16.4 linux/amd64
- Kubernetes version: (use `kubectl version`): v1.22.4
- ~~Docker~~ Podman version: (use `docker info`): 3.4.2
- OS (e.g. from `/etc/os-release`): Fedora 35

**Comment by aojea** [comment] 2021-11-26 07:01
This is a duplicate of https://github.com/kubernetes-sigs/kind/issues/2411 

You can read more about the issue and how to solve it in that link

I'm going to close it so we keep all the information in the same place

Thanks for reporting

**Closed by aojea** 2021-11-26 07:01 UTC
Labels: kind/bug

**Comment by ukazap** [comment] 2021-11-26 08:24
@aojea Thanks for the clarification.

**Comment by mbana** [comment] 2022-02-12 01:53
Just to add, please also see https://github.com/kubernetes-sigs/kind/issues/2521#issuecomment-1036937681 where I got it running in Fedora 35 with BTRFS.
