### ISSUE TITLE
Helm: rabbitmq-ha deployment fails to discover k8s nodes #851 

### ISSUE THREAD

**Issue by ajitkumartanwade** [kubernetes-sigs/kind#1306] opened 2020-02-03 15:14 UTC
Hi Guys, we are not able to set up rabbitmq-ha. We have created a master node and 3 worker nodes on Azure VMs with CentOS. Logs are showing the K8S is not able to find the node to schedule the pod. Please find attached the log screenshot. Please help. Referring to the same issue

**Comment by ajitkumartanwade** [comment] 2020-02-03 15:16
Hi Guys, we are not able to set up rabbitmq-ha. We have created a master node and 3 worker nodes on Azure VMs with CentOS. Logs are showing the K8S is not able to find the node to schedule the pod. Please find attached the log screenshot. Please help. Referring to the same issue

**Comment by BenTheElder** [comment] 2020-02-03 16:21
I don't see any attachments?

**Comment by BenTheElder** [comment] 2020-02-03 16:22
> We have created a master node and 3 worker nodes on Azure VMs with CentOS. 

I think you have the wrong repo. KIND is for local clusters on a single host machine and does not currently involve VMs

**Comment by BenTheElder** [comment] 2020-02-03 18:20
found https://github.com/kubernetes-sigs/kind/issues/851#issuecomment-581459790 reading back through my notifications and I'm going to echo https://github.com/kubernetes-sigs/kind/issues/851#issuecomment-581464012

**Comment by Gsantomaggio** [comment] 2020-02-03 19:41
try:
```
 kubectl create -f https://k8s.io/examples/admin/dns/busybox.yaml
```

then
```
 kubectl exec -ti busybox -- nslookup kubernetes.default.svc.cluster.local
```

that's should be the result:

```
➜  ~ kubectl exec -ti busybox -- nslookup kubernetes.default.svc.cluster.local
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default.svc.cluster.local
Address 1: 10.96.0.1 kubernetes.default.svc.cluster.local
```
tried on `Kind`

**Comment by ajitkumartanwade** [comment] 2020-02-04 12:21
We have tried to create using the busybox.yaml as well but still we are not able to identify the error. 
![image](https://user-images.githubusercontent.com/56916241/73744186-4a827c80-4776-11ea-908e-485bc7ce85ad.png)
While the rabbitmq-ha is still in Crashloopback and the logs are attached hereby.
![image](https://user-images.githubusercontent.com/56916241/73744337-9cc39d80-4776-11ea-8aac-13fa54d8212b.png)
We are not able to resolve dns using the resolv.conf .  Any leads would be appreciated.

**Comment by Gsantomaggio** [comment] 2020-02-04 13:30
@ajitkumartanwade  please read this comment https://github.com/kubernetes-sigs/kind/issues/1306#issuecomment-581495668

I think you are using the wrong repository, not use you are using `KIND` 

you can understand if you are using `kind` with this command:
```
-$ kind version
```

it should be like:
```
$ kind version
kind v0.7.0 go1.13.6 linux/amd64
```

and also follow this [link](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) to debug the DNS problems.

The problem is not in RabbitMQ

**Comment by BenTheElder** [comment] 2020-03-06 16:16
Closing on suspicion that this is the wrong repo, and lack of follow up.

**Closed** 2020-03-06 16:15 UTC
Labels: triage/needs-information, triage/support
