### ISSUE TITLE
Working with a private repo with certificates in kind

### ISSUE THREAD

**Issue by nerokiryu** [kubernetes-sigs/kind#888] opened 2019-09-30 13:38 UTC
Hi !
I've an issue with a connection to a company repo using certs. Please help, I've been on this issue since Friday.
**I want to download a docker image that is on a server (private repo) on my company network.**

My config is : A windows computer running a centos 7.7 VM and in that centos i run a 3 nodes kind cluster (1 control-plane ans 2 workers).
 I've had a token and an httpheaders in the .docker/config.json for the server in my centos VM and mounted it on every nodes.
I've mounted my /etc/pki on each nodes and pods.

```
#config.yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /etc/pki/
    hostPath: /etc/pki/
  - containerPath: /var/lib/kubelet/config.json
    hostPath: $HOME/.docker/config.json
- role: worker
  extraMounts:
  - containerPath: /etc/pki/
    hostPath: /etc/pki/
  - containerPath: /var/lib/kubelet/config.json
    hostPath: $HOME/.docker/config.json
- role: worker
  extraMounts:
  - containerPath: /etc/pki/
    hostPath: /etc/pki/
  - containerPath: /var/lib/kubelet/config.json
    hostPath: $HOME/.docker/config.json
```

When i run helm install with an image in the docker hub it work no problem.
When i try to download a file on the repo form my vm it works no problem
When i try to download a file from my kind cluster (with a pod using kubectl exec -it ... sh ) it print:
```
--2019-09-30 13:07:19--  https://xxx.xxx.xxx.net:8443/repository/maven-public/org/apache/maven/maven/3.0/maven-3.0.pom
Resolving xxx.xxx.xxx.net... 16.16.16.16
Connecting to xxx.xxx.xxx.net|16.16.16.16|:8888... connected.
ERROR: cannot verify xxx.xxx.xxx.net's certificate, issued by 'CN=Enterprise Private SSL CA,OU=Infrastructure Services,O=Enterprise Company,C=US':
  Self-signed certificate encountered.
To connect to xxx.xxx.xxx.net insecurely, use --no-check-certificate'.
```

When i add --no-check-certificate it work perfectly

The log of my kubectl on the pod is : 

> Error from server (BadRequest): container "test-dr" in pod "test-dr-6765759d8-2wsp8" is waiting to start: trying and failing to pull image

**Comment by aojea** [comment] 2019-09-30 14:42
kind is not using docker inside the nodes, this seems a duplicate of #110 

Seem there are 2 solutions in the thread, sideloading the images 

https://github.com/kubernetes-sigs/kind/issues/110#issuecomment-536028439

or the one provided here https://github.com/kubernetes-sigs/kind/issues/110#issuecomment-536028439

**Comment by BenTheElder** [comment] 2019-09-30 16:00
+1 @aojea 

> I've mounted my /etc/pki on each nodes and pods.

that's a fun idea but I don't think this will work correctly, also be aware that kind in multi-control-plane mode needs to manipulate this directory.

Please see #110 for more details and existing discussion around this, as well as https://kind.sigs.k8s.io/docs/user/private-registries/

**Comment by nerokiryu** [comment] 2019-09-30 16:17
Thanks that solve my issue I will side load my images.

>

>  I've mounted my /etc/pki on each nodes and pods.

> 
> that's a fun idea but I don't think this will work correctly, also be aware that kind in multi-control-plane mode needs to manipulate this directory.

It does not solve the problem because the node does not trust this.

You can close this issue.

**Comment by BenTheElder** [comment] 2019-09-30 16:18
ack

**Closed by BenTheElder** 2019-09-30 16:18 UTC
Labels: triage/support
