### ISSUE TITLE
mysql fails to start correctly

### ISSUE THREAD

**Issue by tormodmacleod** [kubernetes-sigs/kind#2489] opened 2021-10-08 14:03 UTC
**What happened**:
```
$ kubectl logs mysql-7b946f9b6-h8dt2
2021-10-08 13:32:10+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.35-1debian10 started.
2021-10-08 13:32:14+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
        command was: mysqld --verbose --help --log-bin-index=/tmp/tmp.vIcfc4zTsA
```

**What you expected to happen**:
start up correctly

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kind --version
kind version 0.11.1

$ kind create cluster

$ kubectl version --short
Client Version: v1.18.2
Server Version: v1.21.1

$ cat mysql.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123"
        ports:
        - containerPort: 3306
          name: mysql

$ kubectl apply -f mysql.yaml 
deployment.apps/mysql created
```

**Anything else we need to know?**:

if i make the following change to the spec, it starts up fine
`- image: mysql:8`

I appreciate that this kind of suggests a mysql issue but in my googling I found [this link](https://github.com/kubernetes/minikube/issues/5751) that seemed to suggest it was an issue with that particular Kubernetes distribution.

**Environment:**

- kind version: 0.11.1
- Kubernetes version: 1.21.1
- Docker version: 19.03.13, build 4484c46
- OS: Fedora 33

**Comment by BenTheElder** [comment] 2021-10-11 03:41
5.7 appears to be from 2015, is it possible to just upgrade and accept that mysql 8 works fine?
I'm not sure we can reasonably prioritize looking at this.

The linked bug is talking about docker as the container runtime in a minikube VM, at that time minikube didn't even support the KIND-derived docker backend. I don't see anything related in the thread.

**Comment by BenTheElder** [comment] 2021-10-15 17:47
Thanks! :-) I appreciate the update and the feedback.

There were recent issues with selinux policy on fedora, perhaps this is related to https://github.com/kubernetes-sigs/kind/issues/2296.

Maybe @aojea wants to look? Personally I'm happy to accept that this is fixed by a newer fedora build, there's too many ways we've encountered small security compatibility issues like this that have turned out to be upstream bugs that have been pretty quickly resolved 😅

**Comment by aojea** [comment] 2021-10-30 16:38
> Docker version: 19.03.13, build 4484c46

> Good news! I upgraded to Fedora 34 and this appears to have fixed the problem. Certainly I can now start a mysql 5.7 container. The upgrade bumped my docker version as below
> Perhaps this fixed the issue? Anyway, I'm happy to close the bug but if you want more detail before closing then just let me know.


AFAIK only docker 20.x is supported, we can't do anything if the problem is related to docker 19.x, 
Thanks
/close

**Closed** 2021-10-30 16:38 UTC
Labels: kind/bug
