### ISSUE TITLE
Kind with docker for mac, service node port not working with localhost or on node IP.

### ISSUE THREAD

**Issue by sbhardwaj-mt** [kubernetes-sigs/kind#449] opened 2019-04-19 05:31 UTC
**What happened**: deploy a service on kubernetes with kind and exposed it to NodePort. 

**What you expected to happen**: the service should work either with localhost:{{NodePort}} or {{NodeIP}}:{{NodePort}}

**How to reproduce it (as minimally and precisely as possible)**: easily reproducible, just need docker for mac and kind.

**Anything else we need to know?**:

**Environment:** Docker for mac

- kind version: (use `kind version`): 0.3.0-alpha
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
- Docker version: (use `docker info`): 18.09.2
- OS (e.g. from `/etc/os-release`): Mac OS

**Comment by BenTheElder** [comment] 2019-04-19 23:59
this is a dupe of #99 

docker for mac does not provide routable IPs for containers from the host, and we aren't binding _every_ port to localhost.

this should be possible to work around in various ways, but we don't have anything yet. see #99

in the meantime something like `kubectl port-forward` should work, other workarounds are mentioned inn #99

**Closed** 2019-04-19 23:59 UTC
Labels: kind/bug, triage/duplicate
