### ISSUE TITLE
kind + metallb stopped working last week

### ISSUE THREAD

**Issue by darint00** [kubernetes-sigs/kind#2673] opened 2022-03-14 17:02 UTC
**What happened**:
kind + metallb installation, per https://kind.sigs.k8s.io/docs/user/loadbalancer/  Stopped working last week.  No longer do we get an external IP address.

**What you expected to happen**:
To get an external IP address.  This was working for months on laptop b.  And for about a year on laptop a.  Doesn't work on either now.

**How to reproduce it (as minimally and precisely as possible)**:
install docker/kind and metallb.

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.11.1
- Kubernetes version: (use `kubectl version`): 1.21.1
- Docker version: (use `docker info`): 20.10.11
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

I suspect metallb made some changes that are incompatible with current kind?

**Comment by aojea** [comment] 2022-03-14 17:04
Can you add more details and logs about the failure?

**Comment by darint00** [comment] 2022-03-14 17:10
Please tell me what you would like to see.  I'm not versed in
troubleshooting k8s/kind/metallb

I am, on laptop a, installing 0.12.0 and will test out metallb with this.

**Comment by aojea** [comment] 2022-03-14 17:21
Kind export logs should output the important information to a folder, just zip that and attach it after you reproduce the issue

**Comment by darint00** [comment] 2022-03-14 17:29
Here is the kind export.

Two other pieces of information.

I noticed the k logs on the speaker pod/metallb showed these
errors/warnings:
grep -e error /tmp/out
{"caller":"level.go:63","error":null,"expected":3,"joined":2,"level":"error","msg":"partial
join","op":"memberDiscovery","ts":"2022-03-14T17:17:49.864534159Z"}
{"caller":"level.go:63","error":"1 error occurred:\n\t* Failed to join
172.18.0.6: dial tcp 172.18.0.6:7946: connect: connection
refused\n\n","expected":1,"joined":0,"level":"error","msg":"partial
join","op":"memberDiscovery","ts":"2022-03-14T17:17:49.864691392Z"}
***@***.***:/$ grep -e warning /tmp/out
W0314 17:17:49.550577       1 warnings.go:70] discovery.k8s.io/v1beta1
EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use
discovery.k8s.io/v1 EndpointSlice

And I tried with 0.12.0 Which is using k8s 1.23.4 and got the same
error/warings in the speaker pods of metallb.

**Comment by aojea** [comment] 2022-03-17 10:19
> Here is the kind export.

there is no export attached :smile:

**Comment by darint00** [comment] 2022-03-17 14:18
Do you not see the kind.logs file listed in the email.  I even see the
file  in your response...           Although it is named kind.logs.  Should
be kind.logs.tgz.

1.  mv kind.logs kind.logs.tgz
2.  gunzip kind.logs.tgz
3.  tar xvf kind.logs.tar

You should see the directory 090866399/*  with all the kind exported data.

Darin

**Comment by fedepaol** [comment] 2022-03-21 14:18
I think this will be fixed by https://github.com/kubernetes-sigs/kind/pull/2687, @darint00 you may have a look at what needs to be changed in order to make metallb work again.

**Comment by BenTheElder** [comment] 2022-03-29 18:19
closing due to https://github.com/kubernetes-sigs/kind/pull/2687

thanks all.

**Closed by BenTheElder** 2022-03-29 18:19 UTC
Labels: kind/bug

**Comment by fedepaol** [comment] 2022-10-11 08:39
Sorry, would you mind elaborating what is not working?
I remember testing it both when opening https://github.com/kubernetes-sigs/kind/pull/2687 and later on opening https://github.com/kubernetes-sigs/kind/pull/2901

What version of metallb are you consuming? And how are you configuring it?
Thanks!
