### ISSUE TITLE
DNS resolution / configuration appears to be incorrect

### ISSUE THREAD

**Issue by w-p** [kubernetes-sigs/kind#1148] opened 2019-12-06 16:50 UTC
I am unable to validate node / container DNS configuration within the cluster according to the [Kubernetes docs on debugging DNS](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/). Am I doing something totally wrong?

**What happened**:
Commands
```
kind create cluster --config ./cluster.yaml --name my-cluster
kubectl apply -f https://k8s.io/examples/admin/dns/busybox.yaml
kubectl exec -ti busybox -- nslookup kubernetes.default
```
Output
```
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 23.202.231.166 a23-202-231-166.deploy.static.akamaitechnologies.com
Address 2: 23.195.69.106 a23-195-69-106.deploy.static.akamaitechnologies.com
```

**What you expected to happen**:
Something similar to this, without resolution to an akamai host
```
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      kubernetes.default
Address 1: 10.0.0.1
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
My system has default `/etc/resolv.conf` and `/etc/hosts` files.

My `cluster.yaml`
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
    extraPortMappings:
      - hostPort: 8000
        containerPort: 8000
```

**Environment:**

- kind version:
```
kind v0.6.1 go1.13.1 linux/amd64
```
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version:
```
19.03.1
```
- OS:
```
19.04 (Disco Dingo)
```

**Comment by BenTheElder** [comment] 2019-12-06 16:54
https://github.com/docker-library/busybox/issues/61#issuecomment-503218240

**Comment by BenTheElder** [comment] 2019-12-06 16:56
This is probably not a kind bug, DNS lookup in your pod isn't respecting all of the DNS config regarding search paths.

Though I don't know why it is resolving to that host, probably something with your host's DNS, which the kind nodes will inherit, and transitively the pods as the fallback DNS.

**Comment by BenTheElder** [comment] 2019-12-06 17:01
You can also check via some of the kubernetes system pods, which would be very broken if they couldn't resolve this.

**Comment by w-p** [comment] 2019-12-06 20:03
You are correct. Both `ubuntu` and `python:3.7-slim` work. Thanks.

**Comment by BenTheElder** [comment] 2019-12-06 20:25
We should update those docs 😅

**Comment by BenTheElder** [comment] 2019-12-06 21:49
it seems the k8s documentation is supposed to pin to a version where this works (`busybox:1.28`), is there any chance you were not using this version?

**Comment by BenTheElder** [comment] 2019-12-06 21:50
https://github.com/kubernetes/website/pull/9901

**Comment by BenTheElder** [comment] 2019-12-06 21:53
I actually can't reproduce this with the current docs :confused:

**Comment by w-p** [comment] 2019-12-08 16:00
I consistently get the same results but I can't determine the source of whatever DNS misconfiguration I have going on. I've setup a reproduction repo [here](https://github.com/w-p/kubernetes-sigs-kind-issues-1148-repro). Since I have a solution, we can close this out unless you'd like to continue digging for the root cause.

**Comment by aojea** [comment] 2019-12-08 20:42
Can you log the queries received and processed in your CoreDNS and paste them here?
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#are-dns-queries-being-received-processed

It seems that your DNS provider is resolving `kubernetes.default` 

>Name:      kubernetes.default
>Address 1: 23.202.231.166 a23-202-231-166.deploy.static.akamaitechnologies.com

I'm curious about what's the order of requests from the busybox pod

**Comment by BenTheElder** [comment] 2019-12-10 04:42
@aojea beat met to it - patching the k/website example to use a different image for debugging DNS with more suitable tools 🤞 
will hold this open

**Comment by BenTheElder** [comment] 2019-12-11 02:20
https://github.com/kubernetes/website/pull/18001

**Comment by BenTheElder** [comment] 2019-12-11 02:22
will track in k/website on second thought, as the bug is really there. we're doing pretty bog standard kubernetes DNS

**Closed by BenTheElder** 2019-12-11 02:22 UTC
Labels: kind/external, triage/support

**Comment by gooddalton** [comment] 2021-09-14 08:43
> I consistently get the same results but I can't determine the source of whatever DNS misconfiguration I have going on. I've setup a reproduction repo [here](https://github.com/w-p/kubernetes-sigs-kind-issues-1148-repro). Since I have a solution, we can close this out unless you'd like to continue digging for the root cause.

Hello! I'm running a kind cluster and encountering the same issues as you have described. You mention a having a solution, what was the workaround for this?
