### ISSUE TITLE
Issues with `0.9.0` images and `port-forward`

### ISSUE THREAD

**Issue by timmyers** [kubernetes-sigs/kind#2019] opened 2021-01-21 19:28 UTC
**What happened**:

Since upgrading to `0.9.0`, and using the new images, have been experiencing issues with port forwarding resulting in errors like

```
E0121 12:22:36.924536   64212 portforward.go:340] error creating error stream for port 56880 -> 8545: Timeout occured
E0121 12:23:07.933938   64212 portforward.go:362] error creating forwarding stream for port 56880 -> 8545: Timeout occured
E0121 12:23:38.945495   64212 portforward.go:362] error creating forwarding stream for port 56880 -> 8545: Timeout occured
E0121 12:24:09.957239   64212 portforward.go:340] error creating error stream for port 56880 -> 8545: Timeout occured
E0121 12:24:40.962297   64212 portforward.go:362] error creating forwarding stream for port 56880 -> 8545: Timeout occured
```

**What you expected to happen**:

Port forwarding continue to works as expected.

**How to reproduce it (as minimally and precisely as possible)**:

Port forwarding into a container and trying to access it with `0.9.0` and `kindest/node:v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600`

**Anything else we need to know?**:

Using `0.9.0`, but the images built for `0.8.x` seems to continue to work.

**Environment:**

```
❯ kind version
kind v0.9.0 go1.15.2 darwin/amd64


❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

❯ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.7GiB
 Name: docker-desktop
 ID: ZETD:2IN5:QULT:EOSF:WJVX:H5UI:HG7L:2JHU:TRUU:MITZ:RVOY:Z43J
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

Big Sur 11.1

**Comment by timmyers** [comment] 2021-01-21 21:19
This seems to happen in a rather subtle timing scenario.  If I try to open a connection to the forwarded pod before it has opened its listener, it will fail as expected `connect: connection refused`.

My code keeps retrying in this case.  If it tries to make a connection very soon after the pod is listening, I get the above issue.  If I wait a little while after the pod has started listening, everything works fine.

**Comment by BenTheElder** [comment] 2021-01-21 22:49
https://github.com/kubernetes-sigs/kind/issues/1723 previous issues with port forward

> Using 0.9.0, but the images built for 0.8.x seems to continue to work.

can you give an example image? these are also different kubernetes versions.

We're finally preparing to release 0.10.0 after some bug fixes landed (not related to this), what happens if you use the default image from HEAD?

**Comment by timmyers** [comment] 2021-01-22 18:38
It seemed that basically any release associated with `0.9.0` failed and with `0.8.1` worked.  I tested these ones specifically:

Failed:
```
1.19: kindest/node:v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600
1.18: kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb
1.17: kindest/node:v1.17.11@sha256:5240a7a2c34bf241afb54ac05669f8a46661912eab05705d660971eeb12f6555
```

Passed:
```
kindest/node:v1.18.2@sha256:7b27a6d0f2517ff88ba444025beae41491b016bc6af573ba467b70c5e8e0d85f
kindest/node:v1.17.5@sha256:ab3f9e6ec5ad8840eeb1f76c89bb7948c77bbf76bcebe1a8b59790b8ae9a283a
```

**Comment by BenTheElder** [comment] 2021-01-22 19:01
cc @aojea this is probably related to the downstream CRI changes?

**Comment by timmyers** [comment] 2021-01-22 19:34
> what happens if you use the default image from HEAD
Are there any tagged releases of this easily available to test out?

**Comment by timmyers** [comment] 2021-01-22 19:58
Running with the default image using `https://kind.sigs.k8s.io/dl/latest/kind-darwin-amd64` (`kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab`) had the same issue.

**Comment by aojea** [comment] 2021-01-22 20:34
your kubectl versions seems too old
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by timmyers** [comment] 2021-01-22 20:47
Sorry I should have mentioned I am doing the actual port-forwading in code with `k8s.io/client-go/tools/portforward`, same as is it is done by up to date `kubectl` source.

I did just try updating to `kubectl v1.19.7` just to make sure and re-ran my tests, since it is used for some other setup, but no change.

**Comment by timmyers** [comment] 2021-01-22 21:15
Right now I am adding a delay of 10 seconds between setting up the port-forward connection and making any requests to it.  That seems to work by getting around some odd timing window but is obviously a workaround.

**Comment by BenTheElder** [comment] 2021-01-23 01:28
https://github.com/kubernetes-sigs/kind/issues/2019#issuecomment-765638766 there are now :-)
https://github.com/kubernetes-sigs/kind/releases/tag/v0.10.0

but I'd expect the issue to be in the images as you discovered, something in cri-containerd most likely.

**Comment by timmyers** [comment] 2021-01-27 17:07
No surprises here but I am seeing the issue in the new release and these images as well:
```
kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca
kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
```

**Comment by aojea** [comment] 2021-01-27 18:13
Can you paste a gist with a reproducer?

**Comment by BenTheElder** [comment] 2021-02-06 01:59
or alternatively we probably want the containerd logs for the node with the forward, these can be dumped by `kind export logs`.

we'll be rolling forward to the latest containerd constantly, but we've worked with upstream before to fix issues like this. @aojea and I have been pretty busy, so any work making this trivially reproducible or diagnosing it helps!

**Comment by BenTheElder** [comment] 2021-03-24 03:53
@aojea we should still take a stab at reproducing this despite lack of specific example. There may be a kubernetes or containerd bug.

**Comment by francescortiz** [comment] 2021-03-24 08:19
I second what @BenTheElder says. After months of struggling with unstable and slow port-forward, at my work we concluded that there is a general issue with kubectl port-forward. Our approach has been to switch to k3s for development because it exposes in the local ip all LoadBalancer ports. Is there an equivalent approach for kind?

**Comment by aojea** [comment] 2021-03-24 08:27
> @aojea we should still take a stab at reproducing this despite lack of specific example. There may be a kubernetes or containerd bug.

next week I'm on vacation and I can take a look
/assign

> . Our approach has been to switch to k3s for development because it exposes in the local ip all LoadBalancer ports. Is there an equivalent approach for kind?

You can use portmapping, as in the Ingress example https://kind.sigs.k8s.io/docs/user/ingress/
or use metallb in linux https://kind.sigs.k8s.io/docs/user/loadbalancer/

**Comment by BenTheElder** [comment] 2021-03-24 08:37
Thanks @aojea 

>> Our approach has been to switch to k3s for development because it exposes in the local ip all LoadBalancer ports. Is there an equivalent approach for kind?
>
> You can use portmapping, as in the Ingress example https://kind.sigs.k8s.io/docs/user/ingress/

To elaborate a little:
If you're running k3s then presumably you're on linux and all the kind node IPs will be routable from the host. So you can access applications using anything from metallb to nodePort services.

If you aren't on linux you can use https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings to forward traffic from the host to a port on a node, and then use a nodePort (or say an ingress behind a nodeport, see https://kind.sigs.k8s.io/docs/user/ingress/).

**Comment by BenTheElder** [comment] 2021-03-27 11:22
https://github.com/kubernetes/kubernetes/issues/99850#issuecomment-808554195

I suspect this may be resolved in the next release, with downstream work on the container runtimes by @aojea (and indeed a fix/bug not specific to kind).

**Comment by Koshmaar** [comment] 2021-04-13 12:32
Hi, I'm getting something similiar when trying to port forward to service:
```
$ kubectl port-forward svc/foobar 8082 -n myns
Forwarding from 127.0.0.1:8082 -> 8082
Forwarding from [::1]:8082 -> 8082

Handling connection for 8082
E0413 14:23:01.072337 1017808 portforward.go:400] an error occurred forwarding 8082 -> 8082: error forwarding port 8082 to pod 499b954e60257db52587dfe2e79fe8a294ea75ee81142093b2c3a2c76f02bdf7, uid : failed to execute portforward in network namespace "/var/run/netns/cni-c557d1f1-3d11-aa4f-abc4-d53ef87b1d5b": failed to dial 8082: dial tcp4 127.0.0.1:8082: connect: connection refused
```
However directly forwarding to pod works fine.
I'm using `kind v0.9.0 go1.15.2 linux/amd64`, on Ubuntu 18.04.

**Comment by BenTheElder** [comment] 2021-06-24 08:02
https://github.com/kubernetes/kubernetes/issues/99850 was fixed. in the latest kind v0.11.1 we're running containerd v1.5.2 which theoretically includes improvements to this vs kind v0.9.0. but we still don't know where this is ultimately coming from yet.

**Comment by BenTheElder** [comment] 2022-05-11 18:02
probably needs re-investigating to see if it's still happening, we're on the latest CNI plugins, Kubernetes, and containerd 1.6.4 instead of 1.5.x now.

**Comment by BenTheElder** [comment] 2022-10-04 17:01
Is anyone still seeing this on KIND v0.16.0 / current Kubernetes? I'd test myself but time is tight and we don't have a minimal reproducer here yet.

**Closed** 2023-04-18 05:18 UTC
Labels: kind/bug
