### ISSUE TITLE
Cannot use HostToContainer mount propagation on MacOS

### ISSUE THREAD

**Issue by fardarter** [kubernetes-sigs/kind#2576] opened 2021-12-30 10:02 UTC
https://github.com/kubernetes-sigs/kind/blob/bdfe777928f675ebcecc838511d173c36ba6d789/site/static/examples/config-with-mounts.yaml#L18

Cannot use HostToContainer on MacOS as per: https://github.com/kubernetes/kubernetes/issues/61058

**Comment by aojea** [comment] 2021-12-30 11:21
> https://github.com/kubernetes-sigs/kind/blob/bdfe777928f675ebcecc838511d173c36ba6d789/site/static/examples/config-with-mounts.yaml#L18
> 
> Cannot use HostToContainer on MacOS as per: [kubernetes/kubernetes#61058](https://github.com/kubernetes/kubernetes/issues/61058)

that is kind config not kubernetes config, that configuration works in Mac

**Comment by fardarter** [comment] 2021-12-30 11:24
These is discussion on the linked thread.

The error I get is identical: 

```
ERROR: failed to create cluster: docker run error: command "docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --net kind --restart=on-failure:1 --init=false --volume=/path/WithTestData:/WithTestData:ro,rslave --publish=0.0.0.0:80:80/TCP --publish=0.0.0.0:443:443/TCP --publish=0.0.0.0:31433:31433/TCP --publish=127.0.0.1:64174:6443/TCP -e KUBECONFIG=/etc/kubernetes/admin.conf kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6" failed with error: exit status 125
Command Output: 80f688eb0b45e1d5e8db561d1748a602581be5c6834a3a2df09a13cf52e43953
docker: Error response from daemon: path /host_mnt//path/WithTestData is mounted on /host_mnt but it is not a shared or slave mount.
make: *** [set-up-kind] Error 1
```

**Comment by aojea** [comment] 2021-12-30 11:37
The error may be identical , but in this case is docker who fails to mount the volume `docker run --hostname ... --volume=/path/WithTestData:/WithTestData:ro,rslave `

The kubernetes cluster is still not running, try to test your docker installation without kind , there has to be something there ...

**Comment by fardarter** [comment] 2021-12-30 12:27
Using Docker Desktop for Mac. I've checked the file share paths (as per docs) and all is in order (cluster starts fine if I remove the field).

If you have any ideas I'm all ears.

**Comment by aojea** [comment] 2021-12-30 17:00
we have a template to report issues like this, otherwise is hard to understand the problem, ideally, it is easier if you explain how to reproduce it.

At least we need
- kind version: (use `kind version`):
- Docker version: (use `docker info`):
- kind configuration file

**Comment by BenTheElder** [comment] 2021-12-30 22:49
this is a dupe of https://github.com/kubernetes-sigs/kind/issues/2400

this is *not possible* with host directories on the mac.

**Comment by fardarter** [comment] 2021-12-31 05:56
If you're correct, @BenTheElder, then a comment on the docs would be correct, IMO, especially as they're example docs.

**Comment by BenTheElder** [comment] 2022-01-05 17:52
PRs to the docs warning about this would be most welcome, I think.

The configuration guide has a note that it's still a bit lacking at the top, this field is a pretty "power user" feature and there's just so much to do.

**Comment by fardarter** [comment] 2022-01-05 17:55
> PRs to the docs warning about this would be most welcome, I think.
> 
> The configuration guide has a note that it's still a bit lacking at the top, this field is a pretty "power user" feature and there's just so much to do.

Normally I'm happy to make docs PRs but I think it needs some explanation about why it doesn't work (even one sentence or a link) and I'm not really sure I get why (docker inner workings are not my thing -- I'm just setting up a k8s dev environment for local and am trying to keep things isolated from host.).

**Comment by BenTheElder** [comment] 2022-01-05 18:10
Roughly mentioned in https://github.com/kubernetes-sigs/kind/issues/2400#issuecomment-889997259

Not in a nice docs comment form but a more detailed brain dump on that:

<details>
Mount propagation can't happen because one filesystem is running in the macOS kernel on the host and the other is in the docker desktop linux kernel inside a virtual machine.

These operating system kernels *do not* share mounts, full stop. Docker doesn't actually make any shared mounts between the host and the virtual machine, that functionality doesn't exist. 

Instead it emulates individual shared mounts the user requested when running the container by synchronizing filesystem state between the host and the virtual machine. It hooks filesystem calls within these mounts on the virtual machine side so when you list the directory or file contents inside the VM it intercepts those system calls and responds with results from the macOS host, roughly.

Mount propagation would require that *new* mounts dynamically created at runtime show up, which wouldn't make sense as the original mount never showed up, instead the contents of the directory are actively mapped between the two kernels as closely as possible.
</details>

----

I think it would be fair to just add a warning along the lines of "mount propagation won't work with the docker desktop app, this is a Docker limitation" and perhaps link to this thread.

If the set the same equivalent options are used just `docker run foo` the same underlying docker desktop limitation will arise, so I don't think it's this project's place to go into great detail on that. It would be nice if docker covered this, perhaps here https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation

**Comment by fardarter** [comment] 2022-01-05 18:13
OK, I'll do a little PR tomorrow.

**Comment by BenTheElder** [comment] 2022-04-22 16:33
/help
/good-first-issue
For anyone interested: our [contributor guide](https://kind.sigs.k8s.io/docs/contributing/getting-started/) has details on how to develop the documentation site.

**Comment by amleshk66** [comment] 2022-08-23 07:09
any suggested solution ? i am also facing same issues on mac .

Error: failed to start container "provisioner": Error response from daemon: path /Users/****/mysql/data is mounted on /host_mnt but it is not a shared or slave mount

**Comment by BenTheElder** [comment] 2022-08-23 21:24
you *cannot* use this on macOS if you're using a host mount*. you also probably don't need it. https://github.com/kubernetes-sigs/kind/issues/2576#issuecomment-1005958468

\* mounts that are from within the VM can do this. mounts that cross the VM boundary back to macOS cannot.

**Closed** 2022-10-20 21:53 UTC
Labels: triage/duplicate, kind/documentation

**Comment by BenTheElder** [comment] 2022-10-20 22:28
I've added a bit more details to the docs around this.
