### ISSUE TITLE
[v0.9.0 with unpinned image] Issue: kind create cluster --image kindest/node --> failed to get kubernetes version from node

### ISSUE THREAD

**Issue by Dietmar1963** [kubernetes-sigs/kind#2428] opened 2021-08-20 11:35 UTC
Hi,
I was using kindest/node:v1.20.0 and the creating of a cluster worked always well.
As this version was not be able to be pulled from docker this morning (https://hub.docker.com/r/kindest/node)  I went to the latest version v1.22.0.
But now the cluster creation fails.  I have the same problem with v1.21.2 and v1.21.1.

**FAILED v1.22.0**
PS C:\Users\dietm\KinD-K8S> kind create cluster --image kindest/node:v1.22.0 --name kind-webtaf --config webTafConfig.yaml
Creating cluster "kind-webtaf" ...
 • Ensuring node image (kindest/node:v1.22.0) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.22.0) 🖼
 • Preparing nodes 📦 📦   ...
 ✓ Preparing nodes 📦 📦
 • Writing configuration 📜  ...
 ✗ Writing configuration 📜
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-webtaf-worker cat /kind/version" failed with error: exit status 1

Command Output: level=error msg="stopped process cannot be started: kind-webtaf-worker: unknown"
PS C:\Users\dietm\KinD-K8S>

**OK v1.20.0**
kind create cluster --image kindest/node:v1.20.0 --name kind-webtaf --config webTafConfig.yaml
Creating cluster "kind-webtaf" ...
 • Ensuring node image (kindest/node:v1.20.0) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.20.0) 🖼
 • Preparing nodes 📦 📦 📦 📦   ...
 ✓ Preparing nodes 📦 📦 📦 📦
 • Writing configuration 📜  ...
 ✓ Writing configuration 📜
 • Starting control-plane 🕹️  ...
 ✓ Starting control-plane 🕹️
 • Installing CNI 🔌  ...
 ✓ Installing CNI 🔌
 • Installing StorageClass 💾  ...
 ✓ Installing StorageClass 💾
 • Joining worker nodes 🚜  ...
 ✓ Joining worker nodes 🚜
Set kubectl context to "kind-kind-webtaf"
You can now use your cluster with:

kubectl cluster-info --context kind-kind-webtaf

Have a nice day! 👋

**My Environment**
Windows 10 Pro
VMware® Workstation 16 Pro 16.1.2 build-17966106
Lenovo P50 with 32 GB Memory

**Installation Steps**
vctl system config --vm-cpus 12 --vm-mem 12288 --k8s-cpus 2 --k8s-mem 4096
vctl system start
vctl kind
kind create cluster --image kindest/node:v1.22.0 --name kind-webtaf --config webTafConfig.yaml

see log attached

[containerd.log](https://github.com/kubernetes-sigs/kind/files/7021211/containerd.log)

Thanks for the support
Dietmar

**Comment by BenTheElder** [comment] 2021-08-20 16:06
> --image kindest/node:v1.22.0

Please don't use images without pinning the digest. Pinning the digest:
- enhances security
- ensures reproducibility (including debugging issues like this)
- prevents against the possibility that a newer version turns out not to be compatible with an old version of kind (we try not to, but it's not manageable to actually test the full matrix of these)

The release notes specify this https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1, and the user guide points to the release notes https://kind.sigs.k8s.io/docs/user/quick-start/#creating-a-cluster

> My Environment

This is missing some details from the bug template, like your kind version, can you please share more information like this?

You can also do `kind create cluster` with `--retain` (prevent cleanup on failure) and then `kind export logs` and share those to give us much more debug info.

> ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-webtaf-worker cat /kind/version" failed with error: exit status 1

This is a symptom of the node container exiting, it should not exit, that means something is broken in the host environment that caused the container to fail before we could actually do anything.

**Comment by Dietmar1963** [comment] 2021-08-20 21:39
> Hi,
> I was using kindest/node:v1.20.0 and the creating of a cluster worked always well.
> As this version was not be able to be pulled from docker this morning (https://hub.docker.com/r/kindest/node) I went to the latest version v1.22.0.
> But now the cluster creation fails. I have the same problem with v1.21.2 and v1.21.1.
> 
> **FAILED v1.22.0**
> PS C:\Users\dietm\KinD-K8S> kind create cluster --image kindest/node:v1.22.0 --name kind-webtaf --config webTafConfig.yaml
> Creating cluster "kind-webtaf" ...
> • Ensuring node image (kindest/node:v1.22.0) 🖼 ...
> ✓ Ensuring node image (kindest/node:v1.22.0) 🖼
> • Preparing nodes 📦 📦 ...
> ✓ Preparing nodes 📦 📦
> • Writing configuration 📜 ...
> ✗ Writing configuration 📜
> ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-webtaf-worker cat /kind/version" failed with error: exit status 1
> 
> Command Output: level=error msg="stopped process cannot be started: kind-webtaf-worker: unknown"
> PS C:\Users\dietm\KinD-K8S>
> 
> **OK v1.20.0**
> kind create cluster --image kindest/node:v1.20.0 --name kind-webtaf --config webTafConfig.yaml
> Creating cluster "kind-webtaf" ...
> • Ensuring node image (kindest/node:v1.20.0) 🖼 ...
> ✓ Ensuring node image (kindest/node:v1.20.0) 🖼
> • Preparing nodes 📦 📦 📦 📦 ...
> ✓ Preparing nodes 📦 📦 📦 📦
> • Writing configuration 📜 ...
> ✓ Writing configuration 📜
> • Starting control-plane 🕹️ ...
> ✓ Starting control-plane 🕹️
> • Installing CNI 🔌 ...
> ✓ Installing CNI 🔌
> • Installing StorageClass 💾 ...
> ✓ Installing StorageClass 💾
> • Joining worker nodes 🚜 ...
> ✓ Joining worker nodes 🚜
> Set kubectl context to "kind-kind-webtaf"
> You can now use your cluster with:
> 
> kubectl cluster-info --context kind-kind-webtaf
> 
> Have a nice day! 👋
> 
> **My Environment**
> Windows 10 Pro
> VMware® Workstation 16 Pro 16.1.2 build-17966106
> Lenovo P50 with 32 GB Memory
> 
> **Installation Steps**
> vctl system config --vm-cpus 12 --vm-mem 12288 --k8s-cpus 2 --k8s-mem 4096
> vctl system start
> vctl kind
> kind create cluster --image kindest/node:v1.22.0 --name kind-webtaf --config webTafConfig.yaml
> 
> see log attached
> 
> [containerd.log](https://github.com/kubernetes-sigs/kind/files/7021211/containerd.log)
> 
> Thanks for the support
> Dietmar



> > --image kindest/node:v1.22.0
> 
> Please don't use images without pinning the digest. Pinning the digest:
> 
> * enhances security
> * ensures reproducibility (including debugging issues like this)
> * prevents against the possibility that a newer version turns out not to be compatible with an old version of kind (we try not to, but it's not manageable to actually test the full matrix of these)
> 
> The release notes specify this https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1, and the user guide points to the release notes https://kind.sigs.k8s.io/docs/user/quick-start/#creating-a-cluster
> 
> > My Environment
> 
> This is missing some details from the bug template, like your kind version, can you please share more information like this?
> 
> You can also do `kind create cluster` with `--retain` (prevent cleanup on failure) and then `kind export logs` and share those to give us much more debug info.
> 
> > ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-webtaf-worker cat /kind/version" failed with error: exit status 1
> 
> This is a symptom of the node container exiting, it should not exit, that means something is broken in the host environment that caused the container to fail before we could actually do anything.



> > --image kindest/node:v1.22.0
> 
> Please don't use images without pinning the digest. Pinning the digest:
> 
> * enhances security
> * ensures reproducibility (including debugging issues like this)
> * prevents against the possibility that a newer version turns out not to be compatible with an old version of kind (we try not to, but it's not manageable to actually test the full matrix of these)
> 
> The release notes specify this https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1, and the user guide points to the release notes https://kind.sigs.k8s.io/docs/user/quick-start/#creating-a-cluster
> 
> > My Environment
> 
> This is missing some details from the bug template, like your kind version, can you please share more information like this?
> 
> You can also do `kind create cluster` with `--retain` (prevent cleanup on failure) and then `kind export logs` and share those to give us much more debug info.
> 
> > ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-webtaf-worker cat /kind/version" failed with error: exit status 1
> 
> This is a symptom of the node container exiting, it should not exit, that means something is broken in the host environment that caused the container to fail before we could actually do anything.





> > --image kindest/node:v1.22.0
> 
> Please don't use images without pinning the digest. Pinning the digest:
> 
> * enhances security
> * ensures reproducibility (including debugging issues like this)
> * prevents against the possibility that a newer version turns out not to be compatible with an old version of kind (we try not to, but it's not manageable to actually test the full matrix of these)
> 
> The release notes specify this https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1, and the user guide points to the release notes https://kind.sigs.k8s.io/docs/user/quick-start/#creating-a-cluster
> 
> > My Environment
> 
> This is missing some details from the bug template, like your kind version, can you please share more information like this?
> 
> You can also do `kind create cluster` with `--retain` (prevent cleanup on failure) and then `kind export logs` and share those to give us much more debug info.
> 
> > ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-webtaf-worker cat /kind/version" failed with error: exit status 1
> 
> This is a symptom of the node container exiting, it should not exit, that means something is broken in the host environment that caused the container to fail before we could actually do anything.



OK - I cleaned up  and deleted .kube and .vctl 

**Commands**
[containerd.log](https://github.com/kubernetes-sigs/kind/files/7024187/containerd.log)
[containerd.log](https://github.com/kubernetes-sigs/kind/files/7024198/containerd.log)

PS C:\Users\dietm\KinD-K8S> vctl system config --vm-cpus 12 --vm-mem 12288 --k8s-cpus 4 --k8s-mem 4096
Preparing storage...
Container storage has been prepared successfully under C:\Users\dietm\.vctl\storage
Preparing container network...
Container network has been prepared successfully using vmnet: vmnet8
Checking installation of VMware Workstation...
VMware Workstation is ready, use 'vctl system start' to start container runtime
PS C:\Users\dietm\KinD-K8S> vctl system start
Downloading 3 files...
Downloading [crx.vmdk 5.65% kubectl.exe 2.40% kind-windows-amd64 92.80%]
Finished kind-windows-amd64 100.00%
Downloading [crx.vmdk 81.17% kubectl.exe 97.93%]
Finished kubectl.exe 100.00%
Downloading [crx.vmdk 98.23%]
Finished crx.vmdk 100.00%
3 files successfully downloaded.
Preparing storage...
Container storage has been prepared successfully under C:\Users\dietm\.vctl\storage
Preparing container network...
Container network has been prepared successfully using vmnet: vmnet8
Launching container runtime...
Container runtime has been started.
PS C:\Users\dietm\KinD-K8S> vctl kind


kind create cluster --image kindest/node:v1.22.0@sha256:f97edf7f7ed53c57762b24f90a34fad101386c5bd4d93baeb45449557148c717 --retain --name kind-webtaf --config createCluster.yml
Creating cluster "kind-webtaf" ...
 • Ensuring node image (kindest/node:v1.22.0) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.22.0) 🖼
 • Preparing nodes 📦 📦   ...
 ✓ Preparing nodes 📦 📦
 • Writing configuration 📜  ...
 ✗ Writing configuration 📜
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-webtaf-control-plane cat /kind/version" failed with error: exit status 1

Command Output: level=error msg="stopped process cannot be started: kind-webtaf-control-plane: unknown"
PS C:\Users\dietm\KinD-K8S>


**Logs**  
[containerd.log](https://github.com/kubernetes-sigs/kind/files/7024156/containerd.log)

Export Logs not possible 
kind export logs
ERROR: unknown cluster "kind"

time="2021-08-20T23:21:30.812063000+02:00" level=debug msg="[shim] ===>> &StateRequest{ID:kind-webtaf-control-plane,ExecID:,XXX_unrecognized:[],}"
time="2021-08-20T23:21:30.812063000+02:00" level=debug msg="[shim] <<=== &StateResponse{ID:kind-webtaf-control-plane,Bundle:C:\\Users\\dietm\\.vctl\\storage\\containerd\\state\\io.containerd.runtime.v2.task\\vctl\\kind-webtaf-control-plane,Pid:1264,Status:STOPPED,Stdin:\\\\.\\pipe\\ctr-kind-webtaf-control-plane-stdin,Stdout:\\\\.\\pipe\\ctr-kind-webtaf-control-plane-stdout,Stderr:,Terminal:true,ExitStatus:1,ExitedAt:0001-01-01 00:00:00 +0000 UTC,ExecID:,XXX_unrecognized:[],}"
time="2021-08-20T23:21:30.813066100+02:00" level=debug msg="[shim] ===>> &StateRequest{ID:kind-webtaf-control-plane,ExecID:,XXX_unrecognized:[],}"


**Docker output**
PS C:\Users\dietm\KinD-K8S> docker ps -a
────                        ─────                                                                                  ───────                   ──    ─────                                  ──────    ─────────────
NAME                        IMAGE                                                                                  COMMAND                   IP    PORTS                                  STATUS    CREATION TIME
────                        ─────                                                                                  ───────                   ──    ─────                                  ──────    ─────────────
kind-webtaf-control-plane   kindest/node@sha256:f97edf7f7ed53c57762b24f90a34fad101386c5bd4d93baeb45449557148c717   /usr/local/bin/entry...   n/a   80:80/tcp,443:443/tcp,63042:6443/tcp   stopped   2021-08-20T23:17:18+02:00
kind-webtaf-worker          kindest/node@sha256:f97edf7f7ed53c57762b24f90a34fad101386c5bd4d93baeb45449557148c717   /usr/local/bin/entry...   n/a   n/a                                    stopped   2021-08-20T23:17:16+02:00



**createCluster.yml**
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker

**Kind Version**
PS C:\Users\dietm\KinD-K8S> kind version
kind v0.9.0 go1.15.2 windows/amd64
VMWare Workstation 16 PRO:  16.1.2 build-17966106


OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
System Manufacturer:       LENOVO
System Model:              20ENCTO1WW
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2592 Mhz
BIOS Version:              LENOVO N1EET90W (1.63 ), 2020-10-21
Total Physical Memory:     32,588 MB
Available Physical Memory: 21,170 MB
Virtual Memory: Max Size:  37,452 MB
Virtual Memory: Available: 11,222 MB
Virtual Memory: In Use:    26,230 MB
[containerd.log](https://github.com/kubernetes-sigs/kind/files/7024220/containerd.log)

**Comment by BenTheElder** [comment] 2021-08-20 22:41
Kind v0.9.0 is multiple releases back, can you try upgrading first? v0.9.0 is nearly a year old now.

**Comment by BenTheElder** [comment] 2021-08-25 16:00
See also the release notes and docs describing how to use these images appropriately (I.E. pin to known good versions by digest) https://github.com/kubernetes-sigs/kind/releases

**Comment by BenTheElder** [comment] 2021-11-10 19:01
closing due to lack of follow-up and outdated release

**Closed by BenTheElder** 2021-11-10 19:01 UTC
Labels: triage/needs-information
