### ISSUE TITLE
New way to change the cluster.local default domain deployed with kind

### ISSUE THREAD

**Issue by kluevandrew** [kubernetes-sigs/kind#2774] opened 2022-05-17 16:22 UTC
I need to change "cluster.local" dns domain to something else, after some attempts i found #1466 issue, but seems it's not working now.

I've tried next config, but node stuck in NotReady state:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-a
networking:
  disableDefaultCNI: true
  podSubnet: 10.201.0.0/16
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        ---
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: ClusterConfiguration
        networking:
          dnsDomain: "kind-a.cluster.local"
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            system-reserved: memory=4Gi,cpu=4
```

Any body knows how to fix it?

**Comment by BenTheElder** [comment] 2022-05-19 16:25
Did you install a CNI driver? 
If you disable the default CNI and don't install something else the node will not ready due to the network not being ready.

**Comment by BenTheElder** [comment] 2022-08-10 21:08
closing for now, feel free to reopen or file a new issue with more information.

**Closed by BenTheElder** 2022-08-10 21:08 UTC
Labels: kind/support

**Comment by kaiburjack** [comment] 2024-05-15 18:42
@BenTheElder thanks for immediately closing this issue....

I also reproduced this locally with a `kind` cluster (no special configuration overrides), just `kind create cluster`.
Then:
- `helm install istio-base istio/istio-base --version 1.21.2`
- `helm install istiod istio/istiod --version 1.21.2`
- helm upgrade --install istio-base istio/istio-base --version 1.22.0`
- helm upgrade --install istiod istio/istiod --version 1.22.0`

After I've done this, I could not create any pods anymore.
