### ISSUE TITLE
Error in creating cluster, podman is provider

### ISSUE THREAD

**Issue by xiaofan-linux** [kubernetes-sigs/kind#2892] opened 2022-08-20 16:24 UTC
#### Error in creating cluster, podman is provider

```shell

➜  ~ cat /etc/redhat-release
Fedora release 36 (Thirty Six)
➜  ~ uname -r
5.18.17-200.fc36.x86_64
➜  ~ uname -a
Linux localhost.localdomain 5.18.17-200.fc36.x86_64 containers/podman#1 SMP PREEMPT_DYNAMIC Thu Aug 11 14:36:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```shell

➜  ~ podman network ls
NETWORK ID    NAME        DRIVER
88c9b7b61afd  kind        bridge
2f259bab93aa  podman      bridge
➜  ~ podman inspect kind
[
     {
          "name": "kind",
          "id": "88c9b7b61afd09229a54869e7f3603416f588848f71343ee2706ca1dc21c1d49",
          "driver": "bridge",
          "network_interface": "podman1",
          "created": "2022-08-21T00:14:12.41086239+08:00",
          "subnets": [
               {
                    "subnet": "fc00:f853:ccd:e793::/64",
                    "gateway": "fc00:f853:ccd:e793::1"
               },
               {
                    "subnet": "10.89.0.0/24",
                    "gateway": "10.89.0.1"
               }
          ],
          "ipv6_enabled": true,
          "internal": false,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
➜  ~ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:03:5e:28 brd ff:ff:ff:ff:ff:ff
    inet 172.28.28.121/20 brd 172.28.31.255 scope global dynamic noprefixroute eth0
       valid_lft 85030sec preferred_lft 85030sec
5: podman1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 62:a5:c2:5f:89:9b brd ff:ff:ff:ff:ff:ff
```

```shell
➜  KIND_EXPERIMENTAL_PROVIDER=podman sudo kind create cluster --config ./config.yml
enabling experimental podman provider
Creating cluster "kind" ...
 ✓ Ensuring node image (localhost/kindest/node:22.10.20220801.1.24.3) 🖼
 ✗ Preparing nodes 📦 📦
ERROR: failed to create cluster: command "podman run --name kind-control-plane --hostname kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --tmpfs /tmp --tmpfs /run --volume 29eb75650a9b89f0032582a1d5930ac072f5dc8c4bd692a8a87255ebb184196b:/var:suid,exec,dev --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER --detach --tty --net kind --label io.x-k8s.kind.cluster=kind -e container=podman --volume /dev/mapper:/dev/mapper --publish=127.0.0.1:43279:6443/tcp -e KUBECONFIG=/etc/kubernetes/admin.conf localhost/kindest/node:22.10.20220801.1.24.3" failed with error: exit status 126
Command Output: Error: netavark: failed to configure bridge and veth interface: failed while configuring network interface: failed to set ip address to podman1: Permission denied (os error 13)
```

**Comment by wherka-ama** [comment] 2022-08-21 16:16
@xiaofan-linux : you are referring to `--config ./config.yml` - any chance of attaching the content of `config.yml` please? It may help these who will try to reproduce the problem during the analysis of this ticket. Thanks in advance!

**Comment by xiaofan-linux** [comment] 2022-08-22 01:58
The following is the content of config.yaml

```yaml
➜  yaml cat config.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "192.168.0.0/16"
  serviceSubnet: "10.0.0.0/20"
  kubeProxyMode: "ipvs"
nodes:
- role: control-plane
  image:  localhost/kindest/node:22.10.20220801.1.24.3
- role: worker
  image:  localhost/kindest/node:22.10.20220801.1.24.3
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```

**Comment by aojea** [comment] 2022-08-22 07:45
> Command Output: Error: netavark: failed to configure bridge and veth interface: failed while configuring network interface: failed to set ip address to podman1: Permission denied (os error 13)

are you able to create containers without kind? in their own network?

**Comment by xiaofan-linux** [comment] 2022-08-24 09:27
Using podman compose,  create containers normally

```shell
➜  podman-compose up -d
['podman', '--version', '']
using podman version: 4.1.1
** excluding:  set()
['podman', 'network', 'exists', 'sealer_default']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=sealer', '--label', 'com.docker.compose.project=sealer', 'sealer_default']
['podman', 'network', 'exists', 'sealer_default']
podman run --name=sealer10 -d --label io.podman.compose.config-hash=123 --label io.podman.compose.project=sealer --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=sealer --label com.docker.compose.project.working_dir=/root/containerd/sealer --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=sealer10 --net sealer_default --network-alias sealer10 --hostname sealer10 --privileged --restart always localhost/fedora/sealer:36.20220801.0.8.6
250c03e9f58a7d37138ad5f4b960536c5c9a7f06d443d8fb07970692a378afea
exit code: 0
['podman', 'network', 'exists', 'sealer_default']
podman run --name=sealer11 -d --label io.podman.compose.config-hash=123 --label io.podman.compose.project=sealer --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=sealer --label com.docker.compose.project.working_dir=/root/containerd/sealer --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=sealer11 --net sealer_default --network-alias sealer11 --hostname sealer11 --privileged --restart always localhost/fedora/sealer:36.20220801.0.8.6
508ff0213ec695cb89d0fd4df05df7bf7fccd720146ce8f02beeb36be0bd01dc
exit code: 0
['podman', 'network', 'exists', 'sealer_default']
podman run --name=sealer12 -d --label io.podman.compose.config-hash=123 --label io.podman.compose.project=sealer --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=sealer --label com.docker.compose.project.working_dir=/root/containerd/sealer --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=sealer12 --net sealer_default --network-alias sealer12 --hostname sealer12 --privileged --restart always localhost/fedora/sealer:36.20220801.0.8.6
d673a390d1ee67258a3a5cf14627b133d70893341513ef11c184c4ccb21428f1
exit code: 0
➜  podman-compose ps
['podman', '--version', '']
using podman version: 4.1.1
podman ps -a --filter label=io.podman.compose.project=sealer
CONTAINER ID  IMAGE                                      COMMAND     CREATED        STATUS            PORTS       NAMES
250c03e9f58a  localhost/fedora/sealer:36.20220801.0.8.6              9 seconds ago  Up 9 seconds ago              sealer10
508ff0213ec6  localhost/fedora/sealer:36.20220801.0.8.6              8 seconds ago  Up 8 seconds ago              sealer11
d673a390d1ee  localhost/fedora/sealer:36.20220801.0.8.6              7 seconds ago  Up 7 seconds ago              sealer12
➜  podman network ls
NETWORK ID    NAME            DRIVER
5901eb89a717  kind            bridge
2f259bab93aa  podman          bridge
b06aea648bcb  sealer_default  bridge
```

**Comment by aojea** [comment] 2022-08-24 11:21
I see, you are using netavark, and the support was added very recently

https://github.com/kubernetes-sigs/kind/pull/2883

we have to release soon, in the meantime you have to use kind from HEAD

**Comment by wherka-ama** [comment] 2022-08-24 21:42
@aojea : FYI - I believe it's linked with https://github.com/containers/podman/issues/15395. However, I'd say it may have more to do with podman than Kind.

Just to be clear: the problem does not occur with new podman(4.x) when I use it in rootless mode. That's something specific to podman with netavark when running as root.

Rootless:
```
[vagrant@fedora36 workspace]$ kind create cluster --config ./config_1.yml 
enabling experimental podman provider
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.24.0) 🖼 
 ✓ Preparing nodes 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Thanks for using kind! 😊
```

Obviously, I'm not trying to say the ticket is invalid - quite the opposite. It is a real problem for sure, but we have to focus on the **rootful** podman with netavark here.

**Comment by wherka-ama** [comment] 2022-09-05 15:57
It looks like it's down to ipv6 disabled in fedora 36 by default. Please see https://github.com/containers/podman/issues/15395#issuecomment-1237240217

I believe this aspect is already documented https://kind.sigs.k8s.io/docs/user/configuration/#networking
However, there is one remaining problem - I don't think the `networking.ipFamily` is taken into account.

**Comment by BenTheElder** [comment] 2022-09-05 17:44
The network is shared between clusters. Dual stack is opportunistically enabled. It is not based on a cluster's IPFamily which affects the cluster internals not the "node" network.
I think our docker provider will fallback to no IPv6 if it recognizes an error related to IPv6 not being available when creating the network.

**Comment by wherka-ama** [comment] 2022-09-05 18:00
> The network is shared between clusters. Dual stack is opportunistically enabled. It is not based on a cluster's IPFamily which affects the cluster internals not the "node" network. I think our docker provider will fallback to no IPv6 if it recognizes an error related to IPv6 not being available when creating the network.

Alright, it's not so straight forward then. Agreed. What we can do, however is to detect the kernel state as far as the IPv6 and/or to align podman with docker so it takes a second turn with the IPv6 taken out of the equation to improve the odds.

@BenTheElder : feel free to assign this issue to me if there is nobody else around interested in taking it on. I can try to fix it within a couple of weeks as I might be a little bit more busy than usual in the next 7-10 days.

**Comment by aojea** [comment] 2022-09-05 18:45
hmm per your comment https://github.com/containers/podman/issues/15395#issuecomment-1237240217

why this is not working?

https://github.com/kubernetes-sigs/kind/blob/c6b929bd797afecc2cbcc4d5425c614e6a68f495/pkg/cluster/internal/providers/podman/provision.go#L143

it looks like a podman bug

**Comment by wherka-ama** [comment] 2022-09-05 18:50
> hmm per your comment [containers/podman#15395 (comment)](https://github.com/containers/podman/issues/15395#issuecomment-1237240217)
> 
> why this is not working?
> 
> https://github.com/kubernetes-sigs/kind/blob/c6b929bd797afecc2cbcc4d5425c614e6a68f495/pkg/cluster/internal/providers/podman/provision.go#L143
> 
> it looks like a podman bug

Yep, I'd say so. For some reason podman is ignoring this hint. I'll see if I can dig into it a bit more. It may be podman itself, but my bet is it can touch netavark too.

**Comment by aojea** [comment] 2022-09-05 18:56
> Yep, I'd say so. For some reason podman is ignoring this hint. I'll see if I can dig into it a bit more. It may be podman itself, but my bet is it can touch netavark too.

I would bet that since netavark is a different component, something is not well connected between podman <-> netvark ... but I'm especulating

**Comment by wherka-ama** [comment] 2022-09-10 19:54
> why this is not working?

@aojea & @BenTheElder  : I spent a bit more time on understanding the flow and the reason why this hint is not really taken into account by podman.

All the values passed via`--sysctl` in podman's `run` mode have no effect on the default namespace where the netavark operates in. 
All these instructions are saved into container spec(in `/var/lib/containers/storage/overlay-containers/<id>/userdata/config.json`) and passed on to OCI runtime  e.g. crun (via conmon) which is then responsible for setting them **inside the container** while the netavark which is trying to set the IP address operates **outside**.
 
`podman` is not really setting any kernel parameters directly. `netavark` does some, but not the ones in question. 
I reckon it could work if `netavark` detected the intent of using the IPv6 and configured the kernel accordingly prior to setting the addresses. However, I'm not really sure if we should take this direction and if it's acceptable to a wider community.

From the `kind` perspective it might be safer to check if we are in rootful mode and if IPv6 is disabled. When these conditions are met, we should issue the warning along with the instructions on how one can correct it. On the other hand we may silently deactivate the IPv6 flows on that level(I think that's what happens when docker is in the picture).

**Comment by aojea** [comment] 2022-09-10 20:24
> I reckon it could work if `netavark` detected the intent of using the IPv6 and configured the kernel accordingly prior to setting the addresses. However, I'm not really sure if we should take this direction and if it's acceptable to a wider community

It has to be, is how cni works, you have to set some sysctl for different reasons

https://github.com/containernetworking/plugins/blob/8c3664b2b158614171eedadf471c8236421aa07f/plugins/main/bridge/bridge.go#L294

**Comment by wherka-ama** [comment] 2022-09-10 21:30
> > I reckon it could work if `netavark` detected the intent of using the IPv6 and configured the kernel accordingly prior to setting the addresses. However, I'm not really sure if we should take this direction and if it's acceptable to a wider community
> 
> It has to be, is how cni works, you have to set some sysctl for different reasons
> 
> https://github.com/containernetworking/plugins/blob/8c3664b2b158614171eedadf471c8236421aa07f/plugins/main/bridge/bridge.go#L294

If we are convinced that `netavark` should be responsible for setting that part up, I suggest we modify it here:
https://github.com/containers/netavark/blob/1d597279f63f78dd4bef15cde581f3ff4857ece7/src/network/bridge.rs#L444

The `net.ipv6.conf.all.forwarding` is already taken care of there, but it makes no difference if the IPv6 is disabled. Setting `net.ipv6.conf.all.disable_ipv6` to 0 seems like a precondition to me. Should we reach out to maintainers of `netavark` with that idea?

BTW: I've already validated it with a dirty patch below. Everything worked perfectly fine :) I don't know what would be the side effects though, so we would need to ask `netavark` folks whether or not that's how we can solve it for good.

```
diff --git a/src/network/bridge.rs b/src/network/bridge.rs
index 670c44f..29e11af 100644
--- a/src/network/bridge.rs
+++ b/src/network/bridge.rs
@@ -383,2 +383,3 @@ static IPV4_FORWARD_ONCE: Once = Once::new();
 static IPV6_FORWARD_ONCE: Once = Once::new();
+static IPV6_DISABLE_ONCE: Once = Once::new();
 
@@ -387,2 +388,4 @@ const IPV6_FORWARD: &str = "net.ipv6.conf.all.forwarding";
 
+const IPV6_DISABLE: &str = "net.ipv6.conf.all.disable_ipv6";
+
 fn setup_ipv4_fw_sysctl() -> NetavarkResult<()> {
@@ -403,2 +406,3 @@ fn setup_ipv6_fw_sysctl() -> NetavarkResult<()> {
     let mut result = Ok("".to_string());
+    let mut result2 = Ok("".to_string());
 
@@ -406,2 +410,8 @@ fn setup_ipv6_fw_sysctl() -> NetavarkResult<()> {
         result = CoreUtils::apply_sysctl_value(IPV6_FORWARD, "1");
+        result2 = CoreUtils::apply_sysctl_value(IPV6_DISABLE, "0");
+    });
+
+    IPV6_DISABLE_ONCE.call_once(|| {
+        result = CoreUtils::apply_sysctl_value(IPV6_FORWARD, "1");
+        result2 = CoreUtils::apply_sysctl_value(IPV6_DISABLE, "0");
     });
@@ -412,3 +422,10 @@ fn setup_ipv6_fw_sysctl() -> NetavarkResult<()> {
     };
+
+    match result2 {
+        Ok(_) => {}
+        Err(e) => return Err(e.into()),
+    };
+
     Ok(())
+
 }
```

**Comment by BenTheElder** [comment] 2022-09-10 21:39
I don't know anything about how netavark specifics but I would expect networking sysctls set on a pod to be set in the network namespace for the container and in general I would expect namespace sysctls to be the purpose of the flag.

**Comment by BenTheElder** [comment] 2023-04-18 05:31
cc @aojea 

probably the podman provider should detect https://github.com/containers/netavark/pull/471/files#diff-ece52eee74a18e4ea910910c9361a7a7b3d4be1a7c8222298b8260811bfb67a3R182 message similar to the docker provider

**Closed** 2023-04-24 22:37 UTC
Labels: kind/bug, area/provider/podman
