### ISSUE TITLE
Gloo/Envoy issue with kind?

### ISSUE THREAD

**Issue by derrickburns** [kubernetes-sigs/kind#577] opened 2019-05-31 02:08 UTC
**What happened**:

I did the following:
1) created a kind cluster (defualt config)
2) installed helm
3) installed weave flux (which automatically installs my application)
4) inspected the Gloo API Gateway that I am using: FAILURE

The failure is that *the Gloo gateway proxy that is based on ENVOY is not getting route info from the Gloo Gateway pod. 

The key line from the logs appears to be:

```
[2019-05-31 01:54:13.790][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 14, no healthy upstream

```
Here is the log of the gateway-proxy (envoy) from `kind`:
```
kubectl logs -n gloo-system gateway-proxy-598f55798d-z2mtp
[2019-05-31 01:54:13.778][6][info][main] [external/envoy/source/server/server.cc:205] initializing epoch 0 (hot restart version=disabled)
[2019-05-31 01:54:13.779][6][info][main] [external/envoy/source/server/server.cc:207] statically linked extensions:
[2019-05-31 01:54:13.779][6][info][main] [external/envoy/source/server/server.cc:209]   access_loggers: envoy.file_access_log,envoy.http_grpc_access_log
[2019-05-31 01:54:13.779][6][info][main] [external/envoy/source/server/server.cc:212]   filters.http: envoy.buffer,envoy.cors,envoy.ext_authz,envoy.fault,envoy.filters.http.grpc_http1_reverse_bridge,envoy.filters.http.header_to_metadata,envoy.filters.http.jwt_authn,envoy.filters.http.rbac,envoy.filters.http.tap,envoy.grpc_http1_bridge,envoy.grpc_json_transcoder,envoy.grpc_web,envoy.gzip,envoy.health_check,envoy.http_dynamo_filter,envoy.ip_tagging,envoy.lua,envoy.rate_limit,envoy.router,envoy.squash,io.solo.aws_lambda,io.solo.nats_streaming,io.solo.transformation
[2019-05-31 01:54:13.779][6][info][main] [external/envoy/source/server/server.cc:215]   filters.listener: envoy.listener.original_dst,envoy.listener.original_src,envoy.listener.proxy_protocol,envoy.listener.tls_inspector
[2019-05-31 01:54:13.780][6][info][main] [external/envoy/source/server/server.cc:218]   filters.network: envoy.client_ssl_auth,envoy.echo,envoy.ext_authz,envoy.filters.network.dubbo_proxy,envoy.filters.network.mysql_proxy,envoy.filters.network.rbac,envoy.filters.network.sni_cluster,envoy.filters.network.thrift_proxy,envoy.filters.network.zookeeper_proxy,envoy.http_connection_manager,envoy.mongo_proxy,envoy.ratelimit,envoy.redis_proxy,envoy.tcp_proxy,io.solo.filters.network.consul_connect
[2019-05-31 01:54:13.780][6][info][main] [external/envoy/source/server/server.cc:220]   stat_sinks: envoy.dog_statsd,envoy.metrics_service,envoy.stat_sinks.hystrix,envoy.statsd
[2019-05-31 01:54:13.780][6][info][main] [external/envoy/source/server/server.cc:222]   tracers: envoy.dynamic.ot,envoy.lightstep,envoy.tracers.datadog,envoy.zipkin
[2019-05-31 01:54:13.780][6][info][main] [external/envoy/source/server/server.cc:225]   transport_sockets.downstream: envoy.transport_sockets.alts,envoy.transport_sockets.tap,raw_buffer,tls
[2019-05-31 01:54:13.781][6][info][main] [external/envoy/source/server/server.cc:228]   transport_sockets.upstream: envoy.transport_sockets.alts,envoy.transport_sockets.tap,raw_buffer,tls
[2019-05-31 01:54:13.781][6][info][main] [external/envoy/source/server/server.cc:234] buffer implementation: old (libevent)
[2019-05-31 01:54:13.785][6][info][main] [external/envoy/source/server/server.cc:281] admin address: 127.0.0.1:19000
[2019-05-31 01:54:13.786][6][info][config] [external/envoy/source/server/configuration_impl.cc:50] loading 0 static secret(s)
[2019-05-31 01:54:13.786][6][info][config] [external/envoy/source/server/configuration_impl.cc:56] loading 2 cluster(s)
[2019-05-31 01:54:13.790][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 14, no healthy upstream
[2019-05-31 01:54:13.790][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:64] Unable to establish new stream
[2019-05-31 01:54:13.790][6][info][config] [external/envoy/source/server/configuration_impl.cc:60] loading 1 listener(s)
[2019-05-31 01:54:13.792][6][info][config] [external/envoy/source/server/configuration_impl.cc:85] loading tracing configuration
[2019-05-31 01:54:13.792][6][info][config] [external/envoy/source/server/configuration_impl.cc:105] loading stats sink configuration
[2019-05-31 01:54:13.793][6][info][main] [external/envoy/source/server/server.cc:478] starting main dispatch loop
[2019-05-31 01:54:13.971][6][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:133] cm init: initializing cds
[2019-05-31 01:54:14.071][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 14, no healthy upstream
[2019-05-31 01:54:14.071][6][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:137] cm init: all clusters initialized
[2019-05-31 01:54:14.071][6][info][main] [external/envoy/source/server/server.cc:462] all clusters initialized. initializing init manager
[2019-05-31 01:54:14.071][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:64] Unable to establish new stream
[2019-05-31 01:54:14.071][6][info][config] [external/envoy/source/server/listener_manager_impl.cc:1006] all dependencies initialized. starting workers
[2019-05-31 01:54:17.182][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 14, no healthy upstream
[2019-05-31 01:54:17.182][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:64] Unable to establish new stream
[2019-05-31 01:54:26.611][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 14, no healthy upstream
[2019-05-31 01:54:26.611][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:64] Unable to establish new stream
[2019-05-31 01:54:49.349][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 14, no healthy upstream
```
When I try the exact same sequence on a cluster created on Amazon EKS, it works exactly as expected.   

Here is the log from the gateway proxy (Envoy) using Amazon EKS:

```
$ kubectl logs -n gloo-system gateway-proxy-5746f96ccd-f995x
[2019-05-31 00:09:21.981][6][info][main] [external/envoy/source/server/server.cc:205] initializing epoch 0 (hot restart version=disabled)
[2019-05-31 00:09:21.982][6][info][main] [external/envoy/source/server/server.cc:207] statically linked extensions:
[2019-05-31 00:09:21.982][6][info][main] [external/envoy/source/server/server.cc:209]   access_loggers: envoy.file_access_log,envoy.http_grpc_access_log
[2019-05-31 00:09:21.982][6][info][main] [external/envoy/source/server/server.cc:212]   filters.http: envoy.buffer,envoy.cors,envoy.ext_authz,envoy.fault,envoy.filters.http.grpc_http1_reverse_bridge,envoy.filters.http.header_to_metadata,envoy.filters.http.jwt_authn,envoy.filters.http.rbac,envoy.filters.http.tap,envoy.grpc_http1_bridge,envoy.grpc_json_transcoder,envoy.grpc_web,envoy.gzip,envoy.health_check,envoy.http_dynamo_filter,envoy.ip_tagging,envoy.lua,envoy.rate_limit,envoy.router,envoy.squash,io.solo.aws_lambda,io.solo.nats_streaming,io.solo.transformation
[2019-05-31 00:09:21.982][6][info][main] [external/envoy/source/server/server.cc:215]   filters.listener: envoy.listener.original_dst,envoy.listener.original_src,envoy.listener.proxy_protocol,envoy.listener.tls_inspector
[2019-05-31 00:09:21.982][6][info][main] [external/envoy/source/server/server.cc:218]   filters.network: envoy.client_ssl_auth,envoy.echo,envoy.ext_authz,envoy.filters.network.dubbo_proxy,envoy.filters.network.mysql_proxy,envoy.filters.network.rbac,envoy.filters.network.sni_cluster,envoy.filters.network.thrift_proxy,envoy.filters.network.zookeeper_proxy,envoy.http_connection_manager,envoy.mongo_proxy,envoy.ratelimit,envoy.redis_proxy,envoy.tcp_proxy,io.solo.filters.network.consul_connect
[2019-05-31 00:09:21.982][6][info][main] [external/envoy/source/server/server.cc:220]   stat_sinks: envoy.dog_statsd,envoy.metrics_service,envoy.stat_sinks.hystrix,envoy.statsd
[2019-05-31 00:09:21.982][6][info][main] [external/envoy/source/server/server.cc:222]   tracers: envoy.dynamic.ot,envoy.lightstep,envoy.tracers.datadog,envoy.zipkin
[2019-05-31 00:09:21.982][6][info][main] [external/envoy/source/server/server.cc:225]   transport_sockets.downstream: envoy.transport_sockets.alts,envoy.transport_sockets.tap,raw_buffer,tls
[2019-05-31 00:09:21.982][6][info][main] [external/envoy/source/server/server.cc:228]   transport_sockets.upstream: envoy.transport_sockets.alts,envoy.transport_sockets.tap,raw_buffer,tls
[2019-05-31 00:09:21.982][6][info][main] [external/envoy/source/server/server.cc:234] buffer implementation: old (libevent)
[2019-05-31 00:09:21.985][6][info][main] [external/envoy/source/server/server.cc:281] admin address: 127.0.0.1:19000
[2019-05-31 00:09:21.985][6][info][config] [external/envoy/source/server/configuration_impl.cc:50] loading 0 static secret(s)
[2019-05-31 00:09:21.985][6][info][config] [external/envoy/source/server/configuration_impl.cc:56] loading 2 cluster(s)
[2019-05-31 00:09:21.987][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 14, no healthy upstream
[2019-05-31 00:09:21.987][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:64] Unable to establish new stream
[2019-05-31 00:09:21.987][6][info][config] [external/envoy/source/server/configuration_impl.cc:60] loading 1 listener(s)
[2019-05-31 00:09:21.988][6][info][config] [external/envoy/source/server/configuration_impl.cc:85] loading tracing configuration
[2019-05-31 00:09:21.988][6][info][config] [external/envoy/source/server/configuration_impl.cc:105] loading stats sink configuration
[2019-05-31 00:09:21.989][6][info][main] [external/envoy/source/server/server.cc:478] starting main dispatch loop
[2019-05-31 00:09:21.999][6][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:133] cm init: initializing cds
[2019-05-31 00:09:22.137][6][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:477] add/update cluster default-linkerd-controller-api-default-linkerd-controller-8085_sm-marketplace during init
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): v0.3.0
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by BenTheElder** [comment] 2019-05-31 02:58
I don't see anything obviously related to kind in those logs.
I'm not familiar with gloo, perhaps another contributor to kind is.

Moving this to triage since it's unclear what the problem is.

Note (Possibly related to your overall usage): if you're running on macOS, the node IPs will not be reachable from the host, only from within the container network, this is a docker for mac limitation. We're exploring alternative options #99.

**Comment by BenTheElder** [comment] 2019-05-31 03:11
I've put out an ask in [#kind](https://kubernetes.slack.com/messages/CEKK1KTN2) on the Kubernetes slack for anyone familiar.

**Comment by aojea** [comment] 2019-05-31 06:30
I think that the key here is to understand what endpoint, IP or DNS, address it trying to reach.
Seems like an envoy thing 🤔

**Comment by howardjohn** [comment] 2019-06-12 03:18
for what it's worth I run Istio on kind all the time without issues, so it isn't an Envoy issue (Istio uses envoy)

**Comment by aojea** [comment] 2019-06-12 06:41
well, don't get me wrong 😅 , I mean a misconfiguration or something similar in one of the endpoints used in the envoy config

``` 
[2019-05-31 01:54:17.182][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 14, no healthy upstream
[2019-05-31 01:54:17.182][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:64] Unable to establish new stream
```

**Comment by BenTheElder** [comment] 2019-07-23 00:27
I'm going to close this in favor of the upstream issue at https://github.com/solo-io/gloo/issues/730, especially given that we've gone about two months without any further details or activity.

I suspect the upstream comment is correct and technically this is a bug in neither, but rather a resources issue.

**Closed by BenTheElder** 2019-07-23 00:27 UTC
Labels: triage/support
