### ISSUE TITLE
kind doesn't support Docker networks other than the default bridge

### ISSUE THREAD

**Issue by chrisob** [kubernetes-sigs/kind#683] opened 2019-07-03 18:31 UTC
**What would you like to be added**:
Currently it seems like `kind` only supports using the [default docker bridge](https://github.com/kubernetes-sigs/kind/blob/e9e20a87853e22ff8a75651b02779016b3e17a25/pkg/cluster/nodes/node.go#L38).

It would be helpful if `kind` allowed a user to specify which Docker network to use for a cluster, instead of assuming that the default bridge interface already exists.

**Why is this needed**:
Not all Docker configurations create a default bridge interface. For example, environments which are hardened according to the CIS benchmark may have the default bridge interface disabled.

**Comment by BenTheElder** [comment] 2019-07-03 19:48
This is a duplicate of https://github.com/kubernetes-sigs/kind/issues/273

We agree, but the non-default docker networks have additional behavior changes vs the default network that are problematic for kind. We're figuring out how best to handle this 😅

**Closed by BenTheElder** 2019-07-03 19:48 UTC
Labels: kind/feature

**Comment by chrisob** [comment] 2019-07-04 09:53
:grimacing: sorry for the duplicate issue!

**Comment by BenTheElder** [comment] 2019-07-04 18:27
Not at all! Good to know what people need, just trying to keep the repo
organized :-)
