### ISSUE TITLE
kind CLI delete non-existing cluster returns success

### ISSUE THREAD

**Issue by flyotlin** [kubernetes-sigs/kind#3808] opened 2024-12-06 07:38 UTC
**What happened**:
I use `$ kind delete cluster --name <cluster-name>` to delete my kind cluster, and accidentally provide a wrong cluster name.

However, the command retured successfully with 0, and did not indicate that the provided cluster name did not exist.

**What you expected to happen**:

Return an error and corresponding error message, so that users can know the provided cluster name does not exist.

**How to reproduce it (as _minimally_ and precisely as possible)**:

Type `$ kind delete cluster --name non-existing-cluster`, which returns successfully with 0

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.25.0
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`):
  runc, with containerd version 207ad711eabd375a01713109a8a197d197ff6542.m
- OS (e.g. from `/etc/os-release`): Arch Linux
- Kubernetes version: (use `kubectl version`): v1.30.0
- Any proxies or other special environment settings?: No

**Comment by aojea** [comment] 2024-12-06 11:12
/close

duplicate of https://github.com/kubernetes-sigs/kind/issues/2924#issuecomment-1245650592 , please read the comments on that issue to understand why this is working as intended

Thanks

**Closed by aojea** 2024-12-06 11:12 UTC
Labels: kind/bug
