### ISSUE TITLE
GPG signed release artifacts/sha256sums

### ISSUE THREAD

**Issue by jcpunk** [kubernetes-sigs/kind#2962] opened 2022-10-10 17:01 UTC
**What would you like to be added**:
Can the binary releases or sha sums be signed with a GPG key?

**Why is this needed**:
For folks who are pulling down these artifacts, having a signature they can check against would be helpful for verifying the supply chain.

**Comment by jcpunk** [comment] 2022-10-10 17:47
There is some mention of SIG Security up at https://github.com/kubernetes/enhancements/issues/3031 but I'm really not super familiar with this whole ecosystem....

**Comment by BenTheElder** [comment] 2022-10-10 18:09
That is not GPG signing.

**Comment by aojea** [comment] 2022-10-10 22:13
this one https://github.com/kubernetes/release/issues/914

**Comment by BenTheElder** [comment] 2022-10-11 16:21
To elaborate: GPG signing things has been a long thread in Kubernetes that has not, as of yet, landed anywhere.

I do not want to sidetrack into developing key management infrastructure or evaluating signing ecosystems ahead of other high-priority issues in Kubernetes (the KIND maintainers are also Kubernetes maintainers because kind exists first and foremost so SIG Testing can test Kubernetes more easily: https://kind.sigs.k8s.io/docs/contributing/project-scope/).

If and when the rest of the organization has a better answer for signing binaries, we will consider steps to adopt it.

**Comment by BenTheElder** [comment] 2022-10-11 16:23
There is a current thread regarding the dependency on Googlers and Google-internal package signing for Kubernetes' Debian + RPM packages and active recent discussion about how to replace that, but it remains to be seen where that lands and if it's easily reusable. https://github.com/kubernetes/release/issues/913

**Comment by BenTheElder** [comment] 2023-04-18 04:18
We're not going to deviate from SIG release on new signing mechanisms, when sigstore signing is mature in Kubernetes we'll look into this route.

As is the binaries are reproducible and it's quick and straightforward to build kind from source.

**Closed by BenTheElder** 2023-04-18 04:18 UTC
Labels: kind/feature
