### ISSUE TITLE
[podman] (rootless) fails to create cluster

### ISSUE THREAD

**Issue by abderrahim** [kubernetes-sigs/kind#1668] opened 2020-06-16 17:32 UTC
I'm trying to use kind with podman, and I got the following error. This is the same error as #1658, but since I'm using a different container engine, I thought it best to open a new issue.

```
kind create cluster 
enabling experimental podman provider
Creating cluster "kind" ...
podman provider may not work properly in rootless mode
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
 ✓ Preparing nodes 📦  
 ✗ Writing configuration 📜 
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "podman exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 255
Command Output: Error: can only create exec sessions on running containers: container state improper
```

Trying to figure out what's happening, I tried to run the kindest/node:v1.18.2 image directly. It's failing with the following error
```
WARN: /dev/kmsg does not exist, symlinking /dev/console
INFO: ensuring we can execute /bin/mount even with userns-remap
INFO: remounting /sys read-only
mount: /sys: permission denied.
```

I believe this step is unneeded with rootless podman, as `/sys` is already read-only (owned by nobody:nogroup with mode `dr-xr-xr-x`). In fact, it's not even a mount, so remounting doesn't make sense anyway.

I think it would make sense to test whether `/sys` is writable first before trying to remount it.

**Comment by BenTheElder** [comment] 2020-06-16 18:31
Rootless is not supported and not expected to work.

**Comment by BenTheElder** [comment] 2020-06-16 18:33
You could however pretty trivially modify this step in the image and see how far it gets
Cc @aojea @amwat

**Comment by aojea** [comment] 2020-06-16 20:07
> You could however pretty trivially modify this step in the image and see how far it gets
> Cc @aojea @amwat

it will be interesting to know how far one can go with rootles 😄 
does systemd works inside a rootless container ?
also, rootless uses slirp4netns, don't know if that will be an important constraint :/

**Comment by BenTheElder** [comment] 2020-06-17 19:53
adding that this was a bug that slipped in (not checking for UID=0), kind at HEAD will treat running rootless as an error and direct you to use rootful podman currently.

**Comment by abderrahim** [comment] 2020-06-17 20:16
So after deleting the remount line, it currently fails to start kubelet. The error message I see is
```
Jun 17 20:14:33 kind-control-plane kubelet[418]: F0617 20:14:33.149515     418 server.go:274] failed to run Kubelet: failed to create kubelet: open /dev/kmsg: operation not permitted
```

btw, how am I supposed to use rootful podman? do I need to install and run kind as root?

**Comment by aojea** [comment] 2020-06-17 20:36
> btw, how am I supposed to use rootful podman? do I need to install and run kind as root?

`sudo kind`

**Comment by BenTheElder** [comment] 2020-06-18 08:51
Yeah, kubelet needs to read that to watch for OOM.

I spoke to some podman people fairly recently and don't expect kubernetes to work inside rootless anytime soon, e.g. kubelet is a system daemon that wants to do all sorts of priv things like manage mounts.

**Comment by BenTheElder** [comment] 2020-06-19 23:37
this is working as intended for now, minus the lack of warning / error about running as non-root, which has been fixed in HEAD already

**Closed by BenTheElder** 2020-06-19 23:37 UTC

**Comment by dahrens** [comment] 2021-08-10 17:53
Just in case you hit exactly the above error with `kind > 0.11.0`. [RTM](https://kind.sigs.k8s.io/docs/user/rootless/) and ensure your cgroups are delegated properly :)
