### ISSUE TITLE
How to use kind behind a HTTP proxy with NTLM authentication (and not get ErrImagePull)

### ISSUE THREAD

**Issue by yogeek** [kubernetes-sigs/kind#2009] opened 2021-01-17 16:37 UTC
**What happened**:

I have CNTLM configured to authenticate to my coporate proxy and Redocks (pointing to CNTLM) acting as a transparent proxy on an Ubuntu machine.

I would like my kind cluster to be able to pull public images without error.

I created a kind cluster with HTTP_PROXY env vars set :

I tried to simply `kind create cluster` and `kubectl run test --image nginx -n default` but it ended in `ImagePullBackOff`... As my Redsocks configuration includes the docker network, I thought it would work without further configuration, but it did not.
So I tried other ways :

```
export HTTP_PROXY=http://127.0.0.1:3128 # this is my CNTLM local port
export HTTPS_PROXY=$HTTP_PROXY
export NO_PROXY="localhost, 127.0.0.*"
export http_proxy=$HTTP_PROXY 
export https_proxy=$HTTPS_PROXY 
export no_proxy=$NO_PROXY

kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
```

and when I try to deploy pods from a public docker image, I have pull errors.

```
kubectl run test --image nginx -n default
kubectl get po

NAME   READY   STATUS         RESTARTS   AGE
test   0/1     ErrImagePull   0          3m27s

kubectl describe po
[...]
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m13s                  default-scheduler  Successfully assigned default/test to kind-control-plane
  Normal   Pulling    2m43s (x4 over 4m12s)  kubelet            Pulling image "nginx"
  Warning  Failed     2m43s (x4 over 4m12s)  kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to resolve reference "docker.io/library/nginx:latest": failed to do request: Head https://registry-1.docker.io/v2/library/nginx/manifests/latest: proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused
  Warning  Failed     2m43s (x4 over 4m12s)  kubelet            Error: ErrImagePull
  Normal   BackOff    2m30s (x6 over 4m11s)  kubelet            Back-off pulling image "nginx"
  Warning  Failed     2m15s (x7 over 4m11s)  kubelet            Error: ImagePullBackOff

```

I also tried to configure kind to map the CNTLM host port :
```
cat <<EOF > config-proxy.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 3128
    hostPort: 3128
    # optional: set the bind address on the host
    listenAddress: "0.0.0.0"
    # optional: set the protocol to one of TCP, UDP, SCTP.
    # TCP is the default
    protocol: TCP
EOF
```

But the cluster does not start :
```
kind create cluster --config=config-proxy.yaml
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼 
 ✗ Preparing nodes 📦  
ERROR: failed to create cluster: docker run error: command "docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --net kind --restart=on-failure:1 -e 'no_proxy=172.19.0.0/16,fc00:f853:ccd:e793::/64,localhost, 127.0.0.*,10.96.0.0/16,10.244.0.0/16,kind-control-plane,.svc,.svc.cluster,.svc.cluster.local' -e HTTP_PROXY=http://127.0.0.1:3128 -e http_proxy=http://127.0.0.1:3128 -e HTTPS_PROXY=http://127.0.0.1:3128 -e https_proxy=http://127.0.0.1:3128 -e 'NO_PROXY=172.19.0.0/16,fc00:f853:ccd:e793::/64,localhost, 127.0.0.*,10.96.0.0/16,10.244.0.0/16,kind-control-plane,.svc,.svc.cluster,.svc.cluster.local' --publish=0.0.0.0:3128:3128/TCP --publish=127.0.0.1:37003:6443/TCP kindest/node:v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600" failed with error: exit status 125
Command Output: 3f6448dce7b746028a65a9960e6c5f23b8bc231e99679ab39ff55dc414997370
docker: Error response from daemon: driver failed programming external connectivity on endpoint kind-control-plane (c4c3977f968743c97f0ab2c2e96b88ac5d4a6e945ff2ea74d08798ad1a837863): Error starting userland proxy: listen tcp4 0.0.0.0:3128: bind: address already in use.
```

**Question**:

How can one use kind with HTTP proxy and NTLM authentication like CNTLM please ?

**Environment:**

- kind version: (use `kind version`): 
```
kind v0.9.0 go1.15.2 linux/amd64
```
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:18:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`): 
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-130-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 10.84GiB
 Name: vmcdsf
 ID: 4DA4:UTTH:S4KI:ZQB6:34NR:WZUZ:ZJTH:MZCC:5YWG:RHML:RM7Z:H3DW
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 37
  Goroutines: 39
  System Time: 2021-01-17T17:17:56.833571593+01:00
  EventsListeners: 0
 Username: yogeek2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  docker.repo.int.be.continental.cloud
  localhost:443
  localhost:80
  0.0.0.0/0
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by BenTheElder** [comment] 2021-01-18 06:21
> export HTTP_PROXY=http://127.0.0.1:3128 # this is my CNTLM local port

You can't use a proxy on loopback, this isn't going to work with docker in general. Every container has it's own loopback interface, which is not the same as the host's, so the kernel is not going to route traffic between them.

You need to have your proxy on some other address that is routable from the node containers + pods.

**Comment by BenTheElder** [comment] 2021-01-18 06:27
alternatively: you can try to something like this: https://medium.com/@saniaky/configure-docker-to-use-a-host-proxy-e88bd988c0aa, but as long as you specify the proxy address as 127.0.0.1 or anything in that /8 it won't route between containers and other containers or containers and the host.

another approach might be running the proxy as a container attached to the kind docker network and passing the IP to the HTTP_PROXY, it appears to be possible to run cntlm in a container https://hub.docker.com/r/robertdebock/docker-cntlm/

**Comment by BenTheElder** [comment] 2021-01-21 00:44
Hope that helps, will respond to further comments but closing this out now as I think we've answered what we can for now, and the loopback issue is definitely the root cause / not something we can change on our end, it's just linux networking.

**Closed by BenTheElder** 2021-01-21 00:44 UTC
Labels: kind/support

**Comment by yogeek** [comment] 2021-01-21 18:39
@BenTheElder thanks for you help

> You can't use a proxy on loopback

Indeed ! Sorry about that but I forgot to edit my snippet : before your answer, I continued my tests and I changed the "http_proxy" to point to my host (`172.17.0.1:3128`, corresponding to the `docker0` interface, which is pingable by my containers), on which CNTLM is running. For the container to be able to contact the CNTLM on the host IP, I also had to use the "Gateway mode" of CNTLM to listen to all interfaces. (as mentionned in the article you pointed to)

And now it seems to work !

So to sum up my current config :
- configure my CNTLM with gateway mode
- `export HTTP_PROXY=http://172.17.0.1:3128 && export HTTPS_PROXY=$HTTP_PROXY && export NO_PROXY="localhost, 127.0.0.*, 172.17.*" && export http_proxy=$HTTP_PROXY && export https_proxy=$HTTPS_PROXY && export no_proxy=$NO_PROXY`
- `kind create cluster`
=> kind can now pull public docker images

Initially, I thought I did not have to export http proxy vars because I have redsocks and this iptable rule : 
```
iptables -t nat -A PREROUTING -s 172.17.0.0/16 -p tcp -j REDSOCKS # Docker networks
```
but apparently, without the http_proxy exported, it does not work... do not understand why.

Anyway, thanks again for your help !

**Comment by BenTheElder** [comment] 2021-01-21 19:13
> but apparently, without the http_proxy exported, it does not work... do not understand why.

We need it to be respected in the nested runtimes etc, which kind can handle, but only if you make it aware of the proxy (by exporting it), currently this seems to be the "standard" for proxy settings.

**Comment by BurlyLuo** [comment] 2024-12-21 07:11
i am following below logical:
```
cat <<EOF | kind create cluster --name=flannel-udp --image=kindest/node:v1.27.3 --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: ./udp
      containerPath: /root/udp
    - hostPath: ./http-proxy.conf
      containerPath: /etc/systemd/system/containerd.service.d/http-proxy.conf
  - role: worker
    extraMounts:
    - hostPath: ./udp
      containerPath: /root/udp
    - hostPath: ./http-proxy.conf
      containerPath: /etc/systemd/system/containerd.service.d/http-proxy.conf

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."192.168.2.100:5000"]
      endpoint = ["http://192.168.2.100:5000"]
EOF

[root@rowan> 1-flannel-udp]# cat http-proxy.conf 
[Service]
Environment="HTTP_PROXY=socks5://192.168.2.10:10808"
Environment="HTTPS_PROXY=socks5://192.168.2.10:10808"
Environment="NO_PROXY=localhost,127.0.0.1,192.168.2.99,192.168.2.100"
[root@rowan> 1-flannel-udp]# 
```
