### ISSUE TITLE
Add resource awareness for node

### ISSUE THREAD

**Issue by huoqifeng** [kubernetes-sigs/kind#1963] opened 2020-12-06 02:30 UTC
**What would you like to be added**:
Resources awareness of a container node comes from the host, it's not same as the resources limited by the cgroup. There is a PR tracked in `cadvisor` to discuss how to hack it https://github.com/google/cadvisor/pull/2699, I recently find a project `lxcfs` https://github.com/lxc/lxcfs which seems meet all the requirements.

**Why is this needed**:
With this implemented, we can use metrics to monitor a container nodes resources capability and usability.

**Comment by BenTheElder** [comment] 2020-12-06 07:22
It's not clear to me that lxcfs is actually a reasonable approach here, or that kind is a good approach to running things with serious resource management (e.g. most users probably have swap enabled which would ordinarily cause kubelet to refuse to run).

The system reserved approach seems possibly acceptable

**Comment by huoqifeng** [comment] 2020-12-06 14:30
I agree https://github.com/lxc/lxcfs did not handle SWAP precisely, and I agree kind does not serious depends on resources awareness today. But I think it's a good feature for users who use kind that he/she can also uses metrics server against kind cluster -- isn't it cool to experiment more functions on kind? Right, maybe, more options need be explored for right approach...

**Comment by BenTheElder** [comment] 2020-12-06 20:44
Sure but *experimenting* is possible without agreeing to ship something in the project 😅

I commented upstream about another approach.

**Comment by BenTheElder** [comment] 2021-02-01 06:00
there's discussion in https://github.com/google/cadvisor/pull/2699 and in SIG Node slack. There's significant pushback against having any way to tell cAdvisor what the actual host limits are w/o relying on auto-detection and against letting cAdvisor read it from the cgroup. 

To a certain extent it may still be possible to implement a bad version of this by setting a computed system-reserved at the kubelet level. Or by bind mounting static fakes / using something similar to lxcfs (bringing on their own problems...).

**Comment by BenTheElder** [comment] 2021-07-09 00:43
we may have a new opportunity in the future https://github.com/kubernetes/enhancements/issues/2371

**Comment by MadhavJivrajani** [comment] 2021-10-11 11:13
/remove-kind design
/kind feature
`kind/design` is migrated to `kind/feature`, see https://github.com/kubernetes/community/issues/6144 for more details

**Comment by BenTheElder** [comment] 2022-02-01 19:57
This is really a dupe of the earlier issue https://github.com/kubernetes-sigs/kind/issues/877

Worth noting that kubelet seems to be moving in the direction of CRI providing the stats, not necessarily with cAdvisor.

**Closed by BenTheElder** 2022-02-01 19:57 UTC
Labels: kind/feature, lifecycle/frozen
