### ISSUE TITLE
Can't connect to kind after the VM was suspended and then resumed

### ISSUE THREAD

**Issue by dmitrynovik** [kubernetes-sigs/kind#2879] opened 2022-08-15 03:45 UTC
**What happened**:
I am using the latest VMWare Workstation VM (Ubuntu).
- suspend the VM
- resume the VM
- any command run against the cluster produces the error:
```
Unable to connect to the server: net/http: TLS handshake timeout

```

**What you expected to happen**:
After resuming the VM, it should work as it did before.

**How to reproduce it (as minimally and precisely as possible)**:
- suspend the VMWare Workstation VM with a kind cluster
- resume the VM
- 
**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): `kind v0.14.0 go1.18.2 linux/amd64`
- Kubernetes version: (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
`
- Docker version: (use `docker info`): see below
- OS (e.g. from `/etc/os-release`): `Linux ubuntu 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 2
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-39-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.73GiB
 Name: ubuntu
 ID: 77T3:WAYL:YA47:CEKF:CNCP:7LG6:H6IS:P3I6:ANL6:RSHC:TYPK:DQXG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

root@ubuntu:~# 


```

**Comment by BenTheElder** [comment] 2022-08-15 15:55
Is the container running? Are these commands run inside the VM or over some special VM networking?

can please you share `kind export logs`, we do not have this product to reproduce.

error suggests a network issue or the node container isn’t running for some reason

**Comment by dmitrynovik** [comment] 2022-08-15 23:49
Yes, every time when the VM is resumed, `kubectl` times out.
Logs attached:
[1784484211.zip](https://github.com/kubernetes-sigs/kind/files/9340598/1784484211.zip)

**Comment by BenTheElder** [comment] 2022-08-15 23:57
Besides the other questions above:
> Is the container running? Are these commands run inside the VM or over some special VM networking?


(seems like a) yes b) unclear ...)

How long are you suspending?  api-server logs show a bunch of logs about expired service account tokens.

It looks like a long time from the container inspect:
>             "StartedAt": "2022-06-21T05:28:45.790592547Z",
>            "FinishedAt": "2022-06-20T22:28:43.61475851-07:00"

You can also try using an image from HEAD, we are about to do a release and it contains some fixes related to rebooting, but this doesn't tentatively look like those issues.

I'm not sure Kubernetes supports being suspended this long.

**Comment by dmitrynovik** [comment] 2022-08-16 00:12
The time how long the VM is suspended does not matter: I tried to suspend and resume immediately => same result.

**Comment by BenTheElder** [comment] 2023-04-18 04:08
Sorry this is difficult to come back to with no way to reproduce. I can't use VMWare workstation myself.

**Comment by zeph** [comment] 2024-11-11 18:11
> E1111 19:10:36.056085   24459 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:45971/api?timeout=32s\": read tcp 127.0.0.1:55718->127.0.0.1:45971: read: connection reset by peer - error from a previous attempt: read tcp 127.0.0.1:55714->127.0.0.1:45971: read: connection reset by peer"

[export.tar.gz](https://github.com/user-attachments/files/17706781/export.tar.gz) <- `kind export logs`
hi all, we are being affected by this... as we run kind on docker-ce (and docker.io) packages on a laptop... on system reboot we are stuck in this situation where kind is not answering anymore to the http kubelet requests... (we are running the `nvkind` fork)

p.s. i removed the logs from pods specific to our org from the dump

**Comment by zeph** [comment] 2024-11-11 18:12
the laptop is a Linux Mint `LMDE 6` (Debian 12 based)

**Comment by BenTheElder** [comment] 2024-11-11 19:46
> requests... (we are running the nvkind fork

I'm sorry but I'm not familiar with this fork and this is not something we reasonably support.

It's unclear if you're also running in a VMware workstation VM or something else. I won't be able to look at the zip for a while (at kubecon)

**Comment by zeph** [comment] 2024-11-12 11:21
Hi @BenTheElder fair enough... it seems actually to be a wrapper around kind https://github.com/NVIDIA/nvkind

We are running on physical laptops with GPU cards, and the kubelet pod inside the node pod is basically restarting without control... we are attemting to isolate the problem. This is not a VM specific issue. It is just similar to the issue mentioned in this ticket given the reported error -> `Unable to connect to the server: net/http: TLS handshake timeout`.

I'll open a new one, and mention this one, if you think it would be a better way of proceeding.

**Comment by aojea** [comment] 2024-11-12 11:31
Let me add @klueska that seems the author of the project for visibility

> kind v0.14.0 go1.18.2 linux/amd64

this looks like a really old versions, I can't remember when did we fix the cluster restart problem, can you try with a newer version of kind?

**Comment by zeph** [comment] 2024-11-12 11:44
that's the one that comes down following the curl based installation on the site

p.s. we seem to have isolated the issue to the node pod version... nvkind tries to initialized kindest/node:1.31.0 ...while with 1.29.2 it works smoothly... (rebooting and accessing after installation)

**Comment by zeph** [comment] 2024-11-12 13:23
btw... we have
```
$ kind --version
kind version 0.24.0
```

on one host and 0.25.0 on the other

**Comment by zeph** [comment] 2024-11-12 14:10
uhmm, seems related to the way we initialize the cluster... a plain `nvkind create cluster` does not get this after a reboot

```
$ nvkind cluster print-gpus


F1112 15:09:39.494087    2406 main.go:45] Error: getting cluster: setting config: getting config bytes: getting configmap: Get "https://127.0.0.1:40587/api/v1/namespaces/default/configmaps/nvkind-cluster-config": EOF
```

**Comment by zeph** [comment] 2024-11-12 14:12
this is the extra config we pass

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: KubeletConfiguration
    apiVersion: kubelet.config.k8s.io/v1beta1
    v: 4  # Set log verbosity level to 4 for debugging
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
{{- range $gpu := until numGPUs }}
  extraMounts:
    # We inject all NVIDIA GPUs using the nvidia-container-runtime.
    # This requires `accept-nvidia-visible-devices-as-volume-mounts = true` be set
    # in `/etc/nvidia-container-runtime/config.toml`
    - hostPath: /dev/null
      containerPath: /var/run/nvidia-container-devices/{{ $gpu }}
{{- end }}
```

**Comment by zeph** [comment] 2024-11-12 14:19
if we get into the container, processes are there... and last port at the bottom is the one from `kube-apiserver`
```
$ docker exec -ti 2c21ef1c6c29 bash
root@nvkind-z7klm-control-plane:~# ss -ntlp
State          Recv-Q         Send-Q                 Local Address:Port                  Peer Address:Port        Process
LISTEN         0              4096                       127.0.0.1:10257                      0.0.0.0:*            users:(("kube-controller",pid=6298,fd=3))
LISTEN         0              4096                       127.0.0.1:10248                      0.0.0.0:*            users:(("kubelet",pid=204,fd=16))
LISTEN         0              4096                       127.0.0.1:2379                       0.0.0.0:*            users:(("etcd",pid=4308,fd=8))
LISTEN         0              4096                       127.0.0.1:2381                       0.0.0.0:*            users:(("etcd",pid=4308,fd=16))
LISTEN         0              4096                       127.0.0.1:32859                      0.0.0.0:*            users:(("containerd",pid=114,fd=10))
LISTEN         0              4096                      127.0.0.11:46675                      0.0.0.0:*
LISTEN         0              4096                      172.18.0.2:2380                       0.0.0.0:*            users:(("etcd",pid=4308,fd=7))
LISTEN         0              4096                      172.18.0.2:2379                       0.0.0.0:*            users:(("etcd",pid=4308,fd=9))
LISTEN         0              4096                               *:10250                            *:*            users:(("kubelet",pid=204,fd=20))
LISTEN         0              4096                               *:6443                             *:*            users:(("kube-apiserver",pid=707,fd=3))
```

**Comment by zeph** [comment] 2024-11-12 14:19
that dies after a few secs...
```
# ss -ntlp
State          Recv-Q         Send-Q                 Local Address:Port                    Peer Address:Port         Process
LISTEN         0              4096                       127.0.0.1:10249                        0.0.0.0:*             users:(("kube-proxy",pid=7325,fd=14))
LISTEN         0              4096                       127.0.0.1:10248                        0.0.0.0:*             users:(("kubelet",pid=204,fd=16))
LISTEN         0              4096                       127.0.0.1:32859                        0.0.0.0:*             users:(("containerd",pid=114,fd=10))
LISTEN         0              4096                      127.0.0.11:46675                        0.0.0.0:*
LISTEN         0              4096                               *:10256                              *:*             users:(("kube-proxy",pid=7325,fd=12))
LISTEN         0              4096                               *:10250                              *:*             users:(("kubelet",pid=204,fd=20))
```

**Comment by BenTheElder** [comment] 2024-11-12 14:19
This seems unrelated to the original issue then?

**Comment by zeph** [comment] 2024-11-12 14:21
@BenTheElder I can't rule tbh... since at the end of the day u have also an issue communicating to the kube-apiserver

> 2024-11-12T14:20:29.805018642Z stderr F W1112 14:20:29.804720       1 logging.go:55] [core] [Channel #172 SubChannel > #173]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:2379", ServerName: "127.0.0.1:2379", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused"
root@nvkind-z7klm-control-plane:/var/log# cat ./pods/kube-system_kube-apiserver-nvkind-z7klm-control-plane_d3264d9509d421b3016ba117ae1c12b5/kube-apiserver/2.log

**Comment by zeph** [comment] 2024-11-12 14:29
oh wait... normally i'd expect to have 2 containers at docker level...
```
$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS          PORTS                       NAMES
4fa6da735ce5   kindest/node:v1.31.2   "/usr/local/bin/entr…"   51 seconds ago   Up 48 seconds   127.0.0.1:34451->6443/tcp   nvkind-7lszk-control-plane
1a7c9beb506a   kindest/node:v1.31.2   "/usr/local/bin/entr…"   51 seconds ago   Up 48 seconds                               nvkind-7lszk-worker
```

**Comment by zeph** [comment] 2024-11-12 14:29
and one is the related to the kube-api `127.0.0.1:34451->6443/tcp`

**Comment by zeph** [comment] 2024-11-12 14:32
ok, my configuration leads to a single pod... 
> $ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED              STATUS              PORTS
          NAMES
23673738c005   kindest/node:v1.31.2   "/usr/local/bin/entr…"   About a minute ago   Up About a minute   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 127.0.0.1:39003->6443/tcp   nvkind-jjx6v-control-plane

**Comment by zeph** [comment] 2024-11-12 14:43
the following solved it for us... we have to keep the roles split... 

```diff
r$ git diff
diff --git a/kind_files/privilege-ports.nvkind.yaml b/kind_files/privilege-ports.nvkind.yaml
index b9766d4..ab1c4c8 100644
--- a/kind_files/privilege-ports.nvkind.yaml
+++ b/kind_files/privilege-ports.nvkind.yaml
@@ -2,16 +2,18 @@ kind: Cluster
 apiVersion: kind.x-k8s.io/v1alpha4
 nodes:
 - role: control-plane
+  kubeadmConfigPatches:
+  - |
+    kind: KubeletConfiguration
+    apiVersion: kubelet.config.k8s.io/v1beta1
+    v: 4  # Set log verbosity level to 4 for debugging
+- role: worker
   kubeadmConfigPatches:
   - |
     kind: InitConfiguration
     nodeRegistration:
       kubeletExtraArgs:
         node-labels: "ingress-ready=true"
-  - |
-    kind: KubeletConfiguration
-    apiVersion: kubelet.config.k8s.io/v1beta1
-    v: 4  # Set log verbosity level to 4 for debugging
   extraPortMappings:
   - containerPort: 80
     hostPort: 80
@@ -26,4 +28,4 @@ nodes:
     # in `/etc/nvidia-container-runtime/config.toml`
     - hostPath: /dev/null
       containerPath: /var/run/nvidia-container-devices/{{ $gpu }}
-{{- end }}
\ No newline at end of file
+{{- end }}
```

**Comment by BenTheElder** [comment] 2024-11-13 07:02
> since at the end of the day u have also an issue communicating to the kube-apiserver

That's a symptom, not a root issue. A LOT of things can cause issues with talking to the apiserver.

> the following solved it for us... we have to keep the roles split...

ah, this is a confusing corner of the config, kubeadm ignores kubeletconfiguration for nodes other than the first one, the result of which goes into a configmap used for subsequent nodes. you have to override kubelet flags instead. there's some other discussion in other issues.

I'm going to close this one out since you found the solution for you and the original issue is not something we can follow up on at this point, it's outdated and we don't have access to a comparable environment.

**Closed by BenTheElder** 2024-11-13 07:02 UTC
Labels: kind/bug
