### ISSUE TITLE
kind and docker `--net=host`

### ISSUE THREAD

**Issue by alexz-kh** [kubernetes-sigs/kind#651] opened 2019-06-25 14:30 UTC
Currently, there is no possibility to pass custom network type, for kind cluster.

Docs `networking:` example:
https://kind.sigs.k8s.io/docs/user/quick-start#ipv6-clusters
https://raw.githubusercontent.com/kubernetes-sigs/kind/master/site/content/docs/user/kind-example-config.yaml

**What would you like to be added**:
Possibility, to use host network in k8s\kind clusters

**Why is this needed**:
To be able pass into privileged containers network bridges\etc from host system.

**Comment by BenTheElder** [comment] 2019-06-25 16:54
this is approximately a duplicate of https://github.com/kubernetes-sigs/kind/issues/273

note that net=host specifically probably not going to work well, port forwarding is going to work in a saner fashion most likely and is a work in progress.

**Comment by BenTheElder** [comment] 2019-06-25 16:54
please follow https://github.com/kubernetes-sigs/kind/issues/273

**Closed by BenTheElder** 2019-06-25 16:54 UTC
Labels: kind/feature

**Comment by nikhil-nutanix** [comment] 2023-09-06 03:37
Does this work now? My use case is to run open-iscsi in a pod and for that to run, the cluster must be running in host network.
I checked out #273 and tried creating a cluster with `KIND_EXPERIMENTAL_NETWORK=host kind create cluster`, but that doesn't seem to have any visible effect.
```
$ kind version
kind v0.17.0 go1.19 linux/amd64
```

**Comment by BenTheElder** [comment] 2023-09-06 16:55
No, this is not and will not be supported.

If you'd like to run a kubernetes node in the host network without isolation, I highly recommend using `kubeadm init` directly instead of kind. It will be supported and much more debuggable.

**Comment by weberc2-tempus** [comment] 2024-06-04 16:53
> If you'd like to run a kubernetes node in the host network without isolation, I highly recommend using `kubeadm init` directly instead of kind. It will be supported and much more debuggable.

Presumably this won't work for macOS or Windows developers.

**Comment by BenTheElder** [comment] 2024-06-04 17:01
You can't run docker directly on macOS or Windows, if you're running kind then you're running linux in a VM or directly. For example docker desktop uses a linux VM.

You can instead run kubeadm directly on a Linux VM (which, your host must support, because it had to support Linux to get docker/kind running).

For macOS I would suggest looking at https://github.com/lima-vm/lima, for Windows I don't have any particular recommendations but there are many options.

IN general I would not recommend depending on host network though, it's not going to be nearly as portable to other options as avoiding that dependency, and to run in the host network we can only have a single node/cluster anyhow which makes most of the containerized / devel cluster tools far less useful.
