### ISSUE TITLE
Kind cluster not startet after server reboot

### ISSUE THREAD

**Issue by chaos234** [kubernetes-sigs/kind#479] opened 2019-05-04 01:23 UTC
**What happened**: After rebooting my server, gitlab starts fine but the kubernetes in docker (kind) isn't starting and there is no documentation on how to get things working. It was a normal restart without changing enything at the environment form the server.

**What you expected to happen**:
That all clusters are started in the correct order and are running. In my case I think first gitlab and then kind with it's defualt "kind" cluster.

**How to reproduce it (as minimally and precisely as possible)**:

Setup a debian 9 server, install gitlab, docker, kind, zsh and all of it's dependencies and create in gitlab then a dummy admin/group/repro and setup kubernetes with all "plugins" and restart the system. When you then take a look over ssh before and after the reboot you should see that your RAM is lower. On my side without kube only ~2GB but with it it should be ~6GB (32GB in total for my machine)

**Anything else we need to know?**:

I added the patches from #306 and also tried the other commands.

**Environment:**

- kind version: (use `kind version`): 0.3.0-alpha
- Kubernetes version: (use `kubectl version`): The output is a bit strange:
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
error: unable to parse the server version: invalid character '<' looking for beginning of value`

- Docker version: (use `docker info`): 

`Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-9-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.36GiB
Name: host.dnet-p.de
ID: MNYW:4GZV:EKZN:SSJX:ZRQ3:Z7TM:WWYO:M4UT:JTVF:C3EK:AMYD:2WXD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support`

Unsure why I am getting the swap warning. Server is hosted by Hetzner and over installimage I didn't created any swap partition and htop shows 0k/0k swap.

- OS (e.g. from `/etc/os-release`): Debian 9 (stretch)

**Comment by BenTheElder** [comment] 2019-05-04 01:26
- currently kind clusters are meant to be ephemeral. see #148 tracking the ability to restart the containers.

- swap limit support is a docker warning, limit support != not having swap, don't worry about the warning though

**Comment by BenTheElder** [comment] 2019-05-04 01:29
this is a duplicate of https://github.com/kubernetes-sigs/kind/issues/148, we've made some improvements to make restarting simpler but we're not there yet. there's no documentation because restarting kind clusters is not supported, if you reboot the host you will need to recreate the cluster currently.

Originally it was meant to be fast enough to not persist clusters at all, for testing purposes it is more reliable to create a clean cluster each time. 

I expect we'll have working restart support in the near future after we rework the networking a bit.

Please subscribe to https://github.com/kubernetes-sigs/kind/issues/148 for progress on restart.

**Closed by BenTheElder** 2019-05-04 01:29 UTC
Labels: kind/bug, triage/duplicate

**Comment by chaos234** [comment] 2019-05-04 01:33
Thanks for your fast response :)
