### ISSUE TITLE
Error shows heapster than metrics-server for kubectl top command

### ISSUE THREAD

**Issue by rajalokan** [kubernetes-sigs/kind#1448] opened 2020-03-27 12:55 UTC
**What happened**:
Running `kubectl top po` gives this error. 
```
➜ kubectl top po          
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
```

**What you expected to happen**:
Output should mention `metrics-server` than already retired `heapster` . Is this in kind or upstream kubernetes 1.18 ? 

**How to reproduce it (as minimally and precisely as possible)**:
- Start a new kind cluster ( Currently I'm using version 1.18)
- On a brand new cluster run `kubectl get po`

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.7.0
- Kubernetes version: (use `kubectl version`): 1.18 ( both client and server)
- Docker version: (use `docker info`): 18.06.1-ce
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by aojea** [comment] 2020-03-27 22:24
This is not a kind issue, you should install the metrics-server
https://github.com/kubernetes-sigs/kind/issues/398#issuecomment-478323664

Closing as duplicate of #398 
/close

**Closed** 2020-03-27 22:24 UTC
Labels: kind/bug

**Comment by BenTheElder** [comment] 2020-03-28 21:00
metrics server is technically not a required component and not part of the upstream k8s release, we may ship it in the future anyhow though
