### ISSUE TITLE
Performance regression in cluster create

### ISSUE THREAD

**Issue by amwat** [kubernetes-sigs/kind#576] opened 2019-05-31 01:23 UTC
**What happened**:
Cluster create took ~50 seconds when using image built from k/k master .

```
real	0m49.629s
user	0m0.579s
sys	0m0.399s
```

**What you expected to happen**:
Cluster create should take around ~30 seconds
which it does when using the kindest/node:v1.14.1 image
```
real	0m31.548s
user	0m0.567s
sys	0m0.363s

```
**How to reproduce it (as minimally and precisely as possible)**:
At kubernetes/kubernetes master (currently https://github.com/kubernetes/kubernetes/commit/990695c839a99cbd0e00fd3806f9802e2af7c2e0)

```
kind build node-image --type=bazel
time kind create cluster --image=kindest/node:latest 
```

**Anything else we need to know?**:
This probably is a regression in k/k and not kind itself
Here are the kubelet logs: https://gist.github.com/amwat/41323bbf70f01cf958d70d66b6f6be75
which show a bunch of fatals at the start which weren't there in 1.14.

**Environment:**
- kind version: (use `kind version`): 0.3.0-alpha
- Kubernetes version: (use `kubectl version`): master
- Docker version: (use `docker info`): 18.09.3
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux

**Comment by BenTheElder** [comment] 2019-05-31 01:25
cc @neolit123 :eyes:

**Comment by amwat** [comment] 2019-05-31 01:37
Got similar results on kind HEAD (v0.4.0-alpha).
The kubelet fatals only take up about 2 seconds though so there's also something more at play.

**Comment by aojea** [comment] 2019-05-31 09:22
I think that this is the change that introduced the kubelet `fatals` https://github.com/kubernetes/kubernetes/commit/7cbe2d6c5f4c3b00d482dc7de3bfd1831ff0e861

I guess that the problem is that now systemd waits until the timeout of 10s expires to restart the kubelet

**Comment by neolit123** [comment] 2019-05-31 12:08
looks like something that should be discussed with sig node.

**Comment by BenTheElder** [comment] 2019-05-31 17:31
Got distracted, coming back to this now. Seems that startup time is now consistently at least slightly longer than 1.14.2, but also less consistent and sometimes quite a bit longer. Not sure what the root cause is yet.

**Comment by BenTheElder** [comment] 2019-05-31 17:51
https://github.com/kubernetes/kubernetes/blob/ba8fcafaf8c502a454acd86b728c857932555315/build/debs/kubelet.service#L9

this in general is a problem for us, kind starts fast enough that a 10s crashloop is too slow. we should probably just be shipping our own systemd files at this point, the upstream ones don't do much and aren't even consistent with what the official releases contain. testing these unit files is not super interesting at the moment.

**Comment by aojea** [comment] 2019-06-03 07:05
I'm not a systemd expert but the service file has `Restart=Always` , that means that it should be restarted once the kubelet fails to start, not when the timeout expires

```
May 31 00:17:20 kind15-control-plane kubelet[193]:         staging/src/k8s.io/component-base/logs/logs.go:58 +0x8a
May 31 00:17:20 kind15-control-plane systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
May 31 00:17:20 kind15-control-plane systemd[1]: kubelet.service: Failed with result 'exit-code'.
May 31 00:17:30 kind15-control-plane systemd[1]: kubelet.service: Service RestartSec=10s expired, scheduling restart.
May 31 00:17:30 kind15-control-plane systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 1.
May 31 00:17:30 kind15-control-plane systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
May 31 00:17:30 kind15-control-plane systemd[1]: Started kubelet: The Kubernetes Node Agent.
```
Why systemd is not honoring the exit code and waiting for the timeout to expire? I don't see errors related to the rate limiting. Can it be related to the change on the signal handling that I linked in my previous comment?

**Comment by BenTheElder** [comment] 2019-06-03 20:39
It is honoring it, `RestartSec` is not the timeout, it's the interval for restarting.

**Comment by BenTheElder** [comment] 2019-06-04 07:09
We have gained around 10sec back under ideal conditions but not necessarily identified this regression yet. 🤔

**Comment by BenTheElder** [comment] 2019-06-24 23:32
with very recent kubernetes & kind:
```
$ time kind create cluster --image=kindest/node:latest
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:latest) 🖼
 ✓ Preparing nodes 📦 
 ✓ Creating kubeadm config 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
kubectl cluster-info

real    0m24.876s
user    0m0.587s
sys     0m0.402s
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.0.1445+1973373be9b171", GitCommit:"1973373be9b171b31c5b05601a9764c98f0640c9", GitTreeState:"clean", BuildDate:"2019-06-24T22:26:53Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by BenTheElder** [comment] 2019-06-24 23:44
I think we can close this out, it varies a bit, but we've done a lot to improve things on our end and improving kubernetes should be tracked upstream

**Closed by BenTheElder** 2019-06-24 23:44 UTC
Labels: kind/bug
