### ISSUE TITLE
Pod deletion hangs, containerd issue: "/opt/cni/bin/loopback: argument list too long"

### ISSUE THREAD

**Issue by bbl** [kubernetes-sigs/kind#2167] opened 2021-03-29 09:20 UTC
**What happened**:
Running `kubectl delete ns <some-namespace>` randomly fails.
Pods stuck in the "Termination" phase due to the `containerd` issue. From containerd service logs **inside** kind container:
```
Mar 29 08:02:43 test-cluster-control-plane containerd[478745]: time="2021-03-29T08:02:43.442708643Z" level=info msg="StopPodSandbox for \"0a36509dcfc500b5090ee28e6c53faf90308ad13bcbadf8dfa0b1f9eee9c12a4\""
Mar 29 08:02:43 test-cluster-control-plane containerd[478745]: time="2021-03-29T08:02:43.443615250Z" level=error msg="StopPodSandbox for \"0a36509dcfc500b5090ee28e6c53faf90308ad13bcbadf8dfa0b1f9eee9c12a4\" failed" error="failed to destroy network for sandbox \"0a36509dcfc500b5090ee28e6c53faf90308ad13bcbadf8dfa0b1f9eee9c12a4\": netplugin failed with no error message: fork/exec /opt/cni/bin/loopback: argument list too long"
Mar 29 08:02:43 test-cluster-control-plane containerd[478745]: time="2021-03-29T08:02:43.444195181Z" level=info msg="StopPodSandbox for \"5c91ce58b5ea70a17b45c1293e28c5f62f20bb0819e997c914393e514e459c9c\""
Mar 29 08:02:43 test-cluster-control-plane containerd[478745]: time="2021-03-29T08:02:43.445062363Z" level=error msg="StopPodSandbox for \"5c91ce58b5ea70a17b45c1293e28c5f62f20bb0819e997c914393e514e459c9c\" failed" error="failed to destroy network for sandbox \"5c91ce58b5ea70a17b45c1293e28c5f62f20bb0819e997c914393e514e459c9c\": netplugin failed with no error message: fork/exec /opt/cni/bin/loopback: argument list too long"
```

This leads to kubelet errors and prevents pods and namespace deletion:
```
4bd3fd6e722623fc9d7f39eab46" from runtime service failed: rpc error: code = Unknown desc = failed to destroy network for sandbox "38289292c07bef6ba9429dac9f51da382eda64bd3fd6e722623fc9d7f39eab46": netplugin failed with no error message: fork/exec /opt/cni/bin/loopback: argument list too long
```

Also, `crictl ps` shows that the needed containers were **actually deleted**, there were no processes running inside the kind container. Seems that the issue only happens on the network deletion process.

**What you expected to happen**:
Expected `kubectl delete namespace <some-namespace>` to finish successfully along with all pods deletion.

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately, this happens randomly on all our CI nodes (5 Ubuntu VMs) during the evaluation of `kubectl delete namespace <some-namespace>`.

**Environment:**

- kind version: 
```
kind v0.10.0 go1.15.7 linux/amd64
```
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-20T02:22:41Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```
- Docker version:
```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 347
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-53-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.788GiB
 Name: stenant02
 ID: 3LWL:KDWV:S7PP:X72I:66DE:T7QS:7J5W:LZPK:XQRA:NXO3:TJEU:TQW3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: resoptimahlo
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by BenTheElder** [comment] 2021-03-29 19:05
Huh, do you have anything more about reproducing this?

>  Backing Filesystem: extfs

I'm having trouble finding more about this filesystem, is this ext4?

Is `/dev/mapper` in use with this filesystem? If so we may need to add it to https://github.com/kubernetes-sigs/kind/pull/2149/commits/69b84abbe22b508ce7009b6ccbe84f0fd2747d6e

**Comment by BenTheElder** [comment] 2021-03-29 19:10
> I'm having trouble finding more about this filesystem, is this ext4?

Answering my own question: this is probably ext2/ext3.

**Comment by aojea** [comment] 2021-03-29 19:18
@bbl what CNI plugin are you using?
the loopback plugin is not used by kindnetd?

**Comment by BenTheElder** [comment] 2021-03-29 19:30
CRI uses it to setup `lo` inside the container / pod https://github.com/containerd/containerd/blob/717dde3c27145dab133a35250434b270935f834f/pkg/cri/server/service_linux.go#L77

https://github.com/containerd/go-cni/blob/b5e1823798c8979f1fc9d736f5707a5518df6759/opts.go#L77

I wonder if containerd is bulk deleting or something, arg_max is usually not reached so easily.

**Comment by aojea** [comment] 2021-03-29 20:16
@squeed does this error rings a bell?

**Comment by aojea** [comment] 2021-03-29 20:30
@bbl please provide more details about the environment:
- CNI plugins used
- manifest for pods to reproduce it
- kind export logs tarball if possible
- ...

**Comment by squeed** [comment] 2021-03-30 11:23
That is very odd, since CNI doesn't actually use any command-line arguments and doesn't batch (and nor does CRI...)

**Comment by squeed** [comment] 2021-03-30 19:38
None at all. And libcni, which containerd uses, doesn't set any arguments -- https://github.com/containernetworking/cni/blob/master/pkg/invoke/raw_exec.go#L37

This is properly weird :)

**Comment by BenTheElder** [comment] 2021-04-02 10:10
@bbl can you provide any more information? https://github.com/kubernetes-sigs/kind/issues/2167#issuecomment-809690964

This is a very strange and interesting bug, but we don't have quite enough to reproduce or to root cause.

**Comment by jshaughn** [comment] 2021-04-07 17:13
Having the same issue on Fedora 32.

**Comment by aojea** [comment] 2021-04-07 21:09
we need more data https://github.com/kubernetes-sigs/kind/issues/2167#issuecomment-809690964, feel free to reach out in slack directly if necessary

**Comment by aojea** [comment] 2021-04-08 22:18
talked with @jshaughn in slack and he shared some logs, it seems istio is installing some cni stuff
```
Apr 06 20:35:23 jshaughn-control-plane containerd[101]: time="2021-04-06T20:35:23.725380987Z" level=info msg="ImageCreate event &ImageCreate{Name:gcr.io/istio-release/install-cni:1.9.1,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
Apr 06 20:35:23 jshaughn-control-plane containerd[101]: time="2021-04-06T20:35:23.728228496Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:4d21ba35c00de5614f21cb0c97e44508af88c5c23db4b87c709934c9861decca,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
```
@bbl do you have istio running too?

**Comment by aojea** [comment] 2021-04-08 22:33
@howardjohn does istio install some special loopback plugin?

**Comment by howardjohn** [comment] 2021-04-08 22:45
That would be some binary called `loopback`? We do not, its called `istio-iptables`

**Comment by bbl** [comment] 2021-04-09 08:14
@aojea sorry for the delay, regarding additional info:
-  We are not using any additional CNI plugins, the default one is used;
- Sample deployment manifest attached to this comment;
- Tarball logs will be attached later today, need to sanitize some info.

[deployment.zip](https://github.com/kubernetes-sigs/kind/files/6284167/deployment.zip)

**Comment by jshaughn** [comment] 2021-04-09 14:22
@aojea , thanks for investigating.  One note, I do have openshift contexts defined as well.  In this env I also use remote openshift clusters and use the 'oc' command as opposed to kubectl.  no idea if that matters...

**Comment by aojea** [comment] 2021-04-09 14:31
that is Ben territory, maybe that is the lead, the context things
``` 
     securityContext:
        runAsUser: 0
        supplementalGroups: [ 100001 ]
```
he'll be back next week IIRC

**Comment by jshaughn** [comment] 2021-04-09 15:02
@aojea Now I'm wondering if I installed istio with CNI support and perhaps that is leading to this issue.  I'm going create a fresh cluster and make sure I install without any CNI.  Will let you know...

**Comment by jshaughn** [comment] 2021-04-09 17:17
Hooray, I think I'm past the problem.  I believe the issue was my originally installing Istio configured with cni, the way I typically do it when installing on OpenShift.  More explicitly, with the following settings:

`"--set components.cni.enabled=true --set components.cni.namespace=kube-system --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/etc/cni/multus/net.d --set values.cni.chained=false --set values.cni.cniConfFileName=istio-cni.conf --set values.sidecarInjectorWebhook.injectedAnnotations.k8s\.v1\.cni\.cncf\.io/networks=istio-cni"`

With this I think the Istio init containers failed to start with the errors described in this issue.

Thanks @aojea and others!

**Comment by adalrsjr1** [comment] 2021-05-10 19:18
Hey @BenTheElder I'm using kind for testing purposes. It is a vanilla deployment + metrics-server. I thought that this issue was caused due to my `init-container` that runs the following iptables rule: `iptables -t nat -A PREROUTING -p tcp -i eth0 --dport $SERVICE_PORT -j REDIRECT --to-port $PROXY_PORT
`. However, I've deployed my application without both init-container and proxy, and the issue has persisted. It is a blue-green deployment with at most two simultaneous replicas (1B + 1G) and always one of them has triggered this issue, sometimes the B, them G, but never both simultaneously.

Once I reverted both kind and node images to:

* kind 0.9.0
* kindest/node:v1.18.8

The problem has vanished. I didn't have time to test if it was caused by either kind or node upgrade.

**Comment by BenTheElder** [comment] 2021-05-18 05:28
Thanks for the info @adalrsjr1. Sorry I don't currently have a lot of time to look into this at the moment either, I've not seen many reports and it's not happening in any of our environments.

**Comment by llhuii** [comment] 2021-06-12 13:10
Same issue here with  kind v.0.10.0 and node kindest/node:v1.20.2:
```
Jun 12 06:42:42 kind-worker kubelet[753]: E0612 06:42:42.283875     753 pod_workers.go:191] Error syncing pod 8248caac-f97b-4330-bf69-1e1d83fe58af ("test-kube-controler-dc84d6548-vcxql_default(8248caac-f97b-4330-bf69-1e1d83fe58af)"), skipping: failed to "CreatePodSandbox" for "test-kube-controler-dc84d6548-vcxql_default(8248caac-f97b-4330-bf69-1e1d83fe58af)" with CreatePodSandboxError: "CreatePodSandbox for pod \"test-kube-controler-dc84d6548-vcxql_default(8248caac-f97b-4330-bf69-1e1d83fe58af)\" failed: rpc error: code = Unknown desc = failed to setup network for sandbox \"9baeb8eefdabebda14e0ce196b295a9b94e4e384b4cdba3ea1893ed039485b20\": netplugin failed with no error message: fork/exec /opt/cni/bin/loopback: argument list too long"
Jun 12 06:42:43 kind-worker kubelet[753]: E0612 06:42:43.319831     753 remote_runtime.go:116] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to setup network for sandbox "6c39fb53f96c20ce7f93db2bd5e78972bb291ec254c8ed785740179f9672ac46": netplugin failed with no error message: fork/exec /opt/cni/bin/loopback: argument list too long
Jun 12 06:42:43 kind-worker kubelet[753]: E0612 06:42:43.319878     753 kuberuntime_sandbox.go:70] CreatePodSandbox for pod "nginx-many-77f4565dc6-sz8gl_default(1c7319f8-1480-41ee-9ad7-b0632ddc242a)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "6c39fb53f96c20ce7f93db2bd5e78972bb291ec254c8ed785740179f9672ac46": netplugin failed with no error message: fork/exec /opt/cni/bin/loopback: argument list too long
Jun 12 06:42:43 kind-worker kubelet[753]: E0612 06:42:43.319891     753 kuberuntime_manager.go:755] createPodSandbox for pod "nginx-many-77f4565dc6-sz8gl_default(1c7319f8-1480-41ee-9ad7-b0632ddc242a)" failed: rpc error: code = Unknown desc = failed to setup network
for sandbox "6c39fb53f96c20ce7f93db2bd5e78972bb291ec254c8ed785740179f9672ac46": netplugin failed with no error message: fork/exec /opt/cni/bin/loopback: argument list too long
Jun 12 06:42:43 kind-worker kubelet[753]: E0612 06:42:43.319929     753 pod_workers.go:191] Error syncing pod 1c7319f8-1480-41ee-9ad7-b0632ddc242a ("nginx-many-77f4565dc6-sz8gl_default(1c7319f8-1480-41ee-9ad7-b0632ddc242a)"), skipping: failed to "CreatePodSandbox" for "nginx-many-77f4565dc6-sz8gl_default(1c7319f8-1480-41ee-9ad7-b0632ddc242a)" with CreatePodSandboxError: "CreatePodSandbox for pod
\"nginx-many-77f4565dc6-sz8gl_default(1c7319f8-1480-41ee-9ad7-b0632ddc242a)\" failed: rpc error: code = Unknown desc = failed to setup network for sandbox \"6c39fb53f96c20ce7f93db2bd5e78972bb291ec254c8ed785740179f9672ac46\": netplugin failed with no error message: fork/exec /opt/cni/bin/loopback: argument list too long"
```

After I restarted containerd by `systemctl restart containerd`, everything has returned to normal.

**Comment by llhuii** [comment] 2021-06-12 16:12
look like containerd can't fork/exec any process:
```bash
root@kind-worker:/# ctr image pull docker.io/library/bash:latest
docker.io/library/bash:latest:                                                    resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:86861c0d08be2e91f2c1f5af12b17724161cccd278b0b620b68c68b1926d105d:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:312f4c41c5574e08ee61a3d991d30c88026bd9996cfff3f7970795498ffbb004: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:9b416d32a3fe15f2f9ab2136e2034ba67f90aa0ed217b433228f830c15ab4026:    done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:f72dd207f6f4c1c8cb02a825fd82d0cc5aba925072a839375a305c462b06067f:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:339de151aab4bc06eed8409daae147c408478cb538dacb90cc63f19ad4eba80b:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:ebfc2c53be8a9a183ae283dbddd91868c0614d32e1b86a2d945935dbc9728224:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 2.2 s                                                                    total:  1.6 Ki (744.0 B/s)                         
unpacking linux/amd64 sha256:86861c0d08be2e91f2c1f5af12b17724161cccd278b0b620b68c68b1926d105d...
INFO[0002] apply failure, attempting cleanup             error="failed to extract layer sha256:32f366d666a541852cad754ee1cdb53a736110b550f0c2d5a46bc5ba519896b6: failed to get stream processor for application/vnd.docker.image.rootfs.diff.tar.gzip: fork/exec /usr/bin/unpigz: argument list too long: unknown" key="extract-673451741-TwIN sha256:32f366d666a541852cad754ee1cdb53a736110b550f0c2d5a46bc5ba519896b6"
ctr: failed to extract layer sha256:32f366d666a541852cad754ee1cdb53a736110b550f0c2d5a46bc5ba519896b6: failed to g
```

**Comment by llhuii** [comment] 2021-06-13 17:26
> I'm facing the very same issue in my deployment. It started after I install kind v.0.10.0 and node kindest/node:v1.18.15.
> 
> I've never had problems with v0.9.0 and node kindest/node:v1.18.8

I noticed that containerd version of both kindest/node:v1.18.15 and my local kindest/node@sha256:8f7ea6e7642c0da54f(its tag is v1.20.2, but inconsistent with upstream v1.20.2): 
```bash
# docker run --privileged --entrypoint /usr/local/bin/containerd -it kindest/node@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab --version
containerd github.com/containerd/containerd v1.4.0-106-gce4439a8 ce4439a8151f77dc50adb655ab4852ee9c366589

# docker run  --privileged --entrypoint /usr/local/bin/containerd -it kindest/node:v1.18.15   --version
containerd github.com/containerd/containerd v1.4.0-106-gce4439a8 ce4439a8151f77dc50adb655ab4852ee9c366589

# docker run  --privileged --entrypoint /usr/local/bin/containerd -it kindest/node:v1.18.8   --version
containerd github.com/containerd/containerd v1.4.0 09814d48d50816305a8e6c1a4ae3e2bcc4ba725a
```

v1.4.0-106-gce4439a8 at here: https://github.com/kind-ci/containerd-nightlies/releases/tag/containerd-1.4.0-106-gce4439a8

**Comment by llhuii** [comment] 2021-06-14 14:58
Hi, I found the reason.
It's the bug of `containerd/nri` in https://github.com/containerd/nri/blame/0afc7f031eaf9c7d9c1a381b7ab5462e89c998fc/client.go#L32.
```go
// DefaultBinaryPath = /opt/nri/bin
if err := os.Setenv("PATH", fmt.Sprintf("%s:%s", os.Getenv("PATH"), DefaultBinaryPath)); err != nil {
```
it was fixed by https://github.com/containerd/nri/pull/1.
In containerd, the bug was:
1. introduced by https://github.com/containerd/containerd/pull/4497 (25 Aug 2020) 
2. fixed by https://github.com/containerd/containerd/pull/4605 (8 Oct 2020)

--- debug --
```bash
strace -ff -p $(pidof /usr/local/bin/containerd) -e trace=execve -v -s200000 &> E2BIG.log
```
![image](https://user-images.githubusercontent.com/419660/121906425-b1964500-cd5d-11eb-98dd-7d2b84fc29bd.png)

**Comment by aojea** [comment] 2021-06-14 15:11
that was an impressive investigation @llhuii , thank you very much

Should we remove those images @BenTheElder ?

**Comment by BenTheElder** [comment] 2021-06-14 17:09
No we should not remove images. We will not break existing users.

Users can upgrade kind and use newer images.

Also: please use the images we publish by digest (which refers to a specific image unlike mutable tags) as outlined in the docs and release notes. It's more secure, reproducible, and the best guarantee of compatibility for a given kind version.

**Comment by BenTheElder** [comment] 2021-06-14 17:10
Impressive debugging, thank you :-)

**Comment by dims** [comment] 2021-06-14 17:46
@llhuii very nice!

**Comment by BenTheElder** [comment] 2021-06-14 22:58
with https://github.com/containerd/containerd/pull/4605/commits/d0f6895d8dd6832aa4ce3657317ca4bc9d9aad04 in all current kind builds / containerd versions I think we can finally close this :-)

images for v0.11.1 in the release notes have containerd 1.5.2 https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1

**Closed by BenTheElder** 2021-06-14 22:58 UTC
Labels: kind/bug

**Comment by llhuii** [comment] 2021-06-15 15:01
Thank you all! I'm glad I can help here!
In case anyone would be interested in E2BIG(i.e. `argument list too long`), so I wrote here.
There are two main cases leading to E2BIG:
1. the limit size of args and all environments
   ```bash
   limit_size=$[$(getconf ARG_MAX) - $(env|wc -c) - $(env|wc -l) * 4 - 2048]
   ```
2. the limit size of an environment key(i.e. key=value) or an argument, a constant value(128KB)

See discussion https://unix.stackexchange.com/a/120842, and https://www.in-ulm.de/~mascheck/various/argmax/.
I also wrote a [bash script](https://github.com/llhuii/hack/blob/main/args_limits/get_limits.sh) to get these truly values in linux.

Back to this issue, it violates the second limit(the length of PATH environment > 128KB). This means that nri/client.New has been called about 10 thousands(=128K/len("/opt/nri/bin")).

**Comment by llhuii** [comment] 2021-06-15 15:09
> No we should not remove images. We will not break existing users.
> 
> Users can upgrade kind and use newer images.
> 
> Also: please use the images we publish by digest (which refers to a specific image unlike mutable tags) as outlined in the docs and release notes. It's more secure, reproducible, and the best guarantee of compatibility for a given kind version.

Hi @BenTheElder, https://github.com/kubernetes-sigs/kind/releases/tag/v0.10.0:
![image](https://user-images.githubusercontent.com/419660/122076853-cfcb7600-ce2d-11eb-88d8-6d8735d92dea.png)

But I pull `kindest/node:v1.20.2`, it shows `sha256:15d3b5c4f521a84896ed1ead1b14e4774d02202d5c65ab68f30eeaf310a3b1a7` instead:
![image](https://user-images.githubusercontent.com/419660/122077641-7b74c600-ce2e-11eb-864c-e06ffa0c3ae7.png)

**Comment by BenTheElder** [comment] 2021-06-15 16:23
> But I pull kindest/node:v1.20.2, it shows sha256:15d3b5c4f521a84896ed1ead1b14e4774d02202d5c65ab68f30eeaf310a3b1a7 instead:


use `kindest/node:v1:20.2@sha256:15d3b5c4f521a84896ed1ead1b14e4774d02202d5c65ab68f30eeaf310a3b1a7` consistently everywhere you specify the image, all tooling will prefer the digest and use that, but the tag can be used to inform humans.
