### ISSUE TITLE
Cluster on reboot

### ISSUE THREAD

**Issue by WStasW** [kubernetes-sigs/kind#385] opened 2019-03-14 05:21 UTC
I am running kind cluster on linux machine (16.04), and it works fine from every single aspect, however. When i restart linux, or docker in general I seem to be unable to restart the cluster, and have to make it from scratch all over again. I guess the issue could be connected to this thread https://github.com/kubernetes-sigs/kind/issues/148

Is there like a work around? would be cool to have something like `kind list cluster` to show you which ones are out there, and `kind restart clusterName`.

When i type `docker container ps -a` I can see there is a control panel, but not the cluster or anything that can be rebooted. How should i tackle and approach this issue?

**Comment by BenTheElder** [comment] 2019-03-14 05:53
this is https://github.com/kubernetes-sigs/kind/issues/148

**Comment by WStasW** [comment] 2019-03-14 06:09
ahw cool, what is the status on this issue ?

**Comment by tao12345666333** [comment] 2019-03-14 06:24
Sorry for delay, I am implementing this feature.

/assign

**Comment by neolit123** [comment] 2019-03-14 16:07
/close
duplicate of https://github.com/kubernetes-sigs/kind/issues/148

**Closed by neolit123** 2019-03-14 16:07 UTC
Labels: triage/duplicate
