### ISSUE TITLE
Pod not able to connect to url login.microsoftonline.com:443

### ISSUE THREAD

**Issue by mastrauckas** [kubernetes-sigs/kind#3604] opened 2024-05-11 00:14 UTC
kind version: kind v0.22.0 go1.20.13 windows/amd64

docker version:  26.1.1

OS: Windows 11 23H2

Kubernetes version: 
```cmd
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```

My application is attempting to do OAuth when trying to get secrets from Azure Key Vault on startup.  However, it is not able to connect to URL `login.microsoftonline.com:443`, so it crashes and goes into a `CrashLoopBackOff` loop.  Eventually, it will be able to connect after many `CrashLoopBackOff` attempts.

**Comment by mastrauckas** [comment] 2024-05-13 01:36
It appears `login.microsoftonline.com` is not resolving. 

If I do:
```cmd
nslookup login.microsoftonline.com
```

![image](https://github.com/kubernetes-sigs/kind/assets/1589169/911bb803-2ec6-4445-8949-6307985347b2)

However, if I do 

```cmd
nslookup login.microsoftonline.com 9.9.9.9
```

I get:

![image](https://github.com/kubernetes-sigs/kind/assets/1589169/4ed8c94d-9b14-42b7-a0a3-9bedf1ae6102)

So he default DNS server can't resolve `login.microsoftonline.com` for whatever reason.

**Comment by BenTheElder** [comment] 2024-05-13 16:02
Most of the questions in the bug template are missing in your post and you don't specify where / how you're executing nslookup but DNS within the cluster is either:
- the in-cluster DNS server (coreDNS) as deployed by kubeadm IF you're inside a pod that isn't hostnetwork
- Docker's embedded DNS resolver which listens within the node containers (and any container not on the default "bridge" bridge network) and then resolves them in dockerd on the host with your hosts's resolver settings.  https://docs.docker.com/network/#dns-services

**Comment by mastrauckas** [comment] 2024-05-14 02:09
Thank you for your response @BenTheElder. My fault if I didn't fill out all the information.

The command I ran to get into a pod to troubleshoot was:
```cmd
 kubectl run troubleshooting --rm -i --tty --image nicolaka/netshoot -- /bin/bash
```

Once in the pod, I ran `nslookup login.microsoftonline.com` and `nslookup login.microsoftonline.com 9.9.9.9` as shown above; where the Quad9 nameserver worked and the internal nameserver didn't.

I also tried 
```cmd
docker run --rm -it nicolaka/netshoot /bin/bash
```

Once in the container, I did `nslookup login.microsoftonline.com` and `curl -I login.microsoftonline.com` and both worked just fine.

I also did `docker exec -it experimental-cluster-worker bash`, where `experimental-cluster-worker` is one of my nodes

Once in the node container, I did 
```cmd
apt update
apt install dnsutils
nslookup login.microsoftonline.com
```

Once again, inside the node itself I was able to do a `nslookup` just find on `login.microsoftonline.com`.

It appears the problem only happens inside the pod.

**Comment by BenTheElder** [comment] 2024-05-14 16:23
> docker run --rm -it nicolaka/netshoot /bin/bash

This would need to be with `--net=kind` (or similar, the default bridge network does not have docker's embedded DNS, non-default networks do by default)

The internal nameserver is coreDNS with configurable search paths, if your host has a lot of search paths you might try this config option https://github.com/kubernetes-sigs/kind/blob/5d17676c07b6aa9a13c25e671dd8375e5981dde5/hack/ci/e2e-k8s.sh#L159 (We're considering making this default)

**Comment by mastrauckas** [comment] 2024-05-15 01:02
> > docker run --rm -it nicolaka/netshoot /bin/bash
> 
> This would need to be with `--net=kind` (or similar, the default bridge network does not have docker's embedded DNS, non-default networks do by default)
> 
> The internal nameserver is coreDNS with configurable search paths, if your host has a lot of search paths you might try this config option
> 
> https://github.com/kubernetes-sigs/kind/blob/5d17676c07b6aa9a13c25e671dd8375e5981dde5/hack/ci/e2e-k8s.sh#L159
> 
> (We're considering making this default)

I am just doing basic Kubernetes testing for learning purposes.  I want to forward all non-pod traffic to an external name server.  I tried 
```cmd
networking:
  dnsSearch:
  - 9.9.9.9
```

but that doesn't appear to work.  What exactly am I doing wrong?

I am able to edit the `coreDNS` config after the cluster has been created, then restart the `coreDNS` pods and everything works.  However, I'd prefer to do put my forwarder in the cluster `yaml` file, so it gets added at cluster creation time.

**Comment by BenTheElder** [comment] 2024-05-15 17:26
the DNS resolvers shouldn't see "www" vs "login" differently

> I shouldn’t have to do anything special,

Er, I'm not saying special to this particular domain, I'm saying your host environment may be resulting in a large number of search paths which can create flakiness.

You can also test this by testing for `login.microsoftonline.com.` (FQDN) instead.

**Comment by mastrauckas** [comment] 2024-05-15 19:58
> the DNS resolvers shouldn't see "www" vs "login" differently

I agree, it shouldn't.

> > I shouldn’t have to do anything special,
> 
> Er, I'm not saying special to this particular domain, I'm saying your host environment may be resulting in a large number of search paths which can create flakiness.
> 
> You can also test this by testing for `login.microsoftonline.com.` (FQDN) instead.

It's one 1 control-plane and 5 or 6 workers, the only pod is the test pod created with `kubectl run troubleshooting --rm -i --tty --image nicolaka/netshoot -- /bin/bash`.

**Comment by stmcginnis** [comment] 2024-05-15 20:41
> It's a plain deployment with 1 control-plane and 5 or 6 workers

I believe the point wasn't about the kind pod configuration, rather the host environment it is running in. So your dev machine, the network you are connected to, any proxy relays, etc.

**Comment by BenTheElder** [comment] 2024-05-15 20:52
Right, the behavior of the DNS is related to the host machine's network, the docker install, the resolver configuration on the host, etc.

I've made some suggestions about how to test for excluding some of these (namely the search paths).

If I run the same pod on my host then resolving the domain works fine.

**Comment by mastrauckas** [comment] 2024-05-16 01:58
> > It's a plain deployment with 1 control-plane and 5 or 6 workers
> 
> I believe the point wasn't about the kind pod configuration, rather the host environment it is running in. So your dev machine, the network you are connected to, any proxy relays, it’s 

> > It's a plain deployment with 1 control-plane and 5 or 6 workers
> 
> I believe the point wasn't about the kind pod configuration, rather the host environment it is running in. So your dev machine, the network you are connected to, any proxy relays, etc

This command `nslookup login.microsoftonline.com `

Works on my machine in a docker container and not in a docker container, it works on vms on my machine, it works on multiple machines in my networks.  All machines all use the same DNS server, which is 9.9.9.9.

I also have a very basic home network. I even connected my computer straight to my cable modem, have my computer connected to my cell phone, all getting  the same behavior, which works just fine, except when using the pods default DNS Server.

It even works in the K8s pod if I use`nslookup login.microsoftonline.com 9.9.9.9` instead of just `nslookup login.microsoftonline.com`.

So I really don’t get why you believe it’s my computer/network.

**Comment by mastrauckas** [comment] 2024-05-16 12:10
I also tried doing the same test with `k3d` and it has the same results too.  So `k3d` and `kind` have the same issue when using the default dns server `coreDNS`.

**Comment by stmcginnis** [comment] 2024-05-16 14:04
This is definitely a kubernetes configuration issue and not anything kind is doing. What that configuration issue is though, still not clear. :)

The is indeed _not_ correct for `dnsSearch`. These entries are DNS search entries, so basically what that configuration is telling Kubernetes to do is when looking for the host name `foo`, also try to see if it can be found as `foo.8.8.8.8`.

Rather than running a container to test this, it would be good to run a pod within the context of the k8s cluster to make sure it's getting the same environment. This page has some useful tips for troubleshooting DNS issues: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by BenTheElder** [comment] 2024-05-16 19:14
> So I really don’t get why you believe it’s my computer/network.

Because it doesn't replicate on my computer/network and it's a networking issue. It's not an inherent coreDNS behavior.

> This also didn't work. Then again, I am not even sure if I'm even doing the dnsSearch correct.

This isn't a valid dnsSearch setting, my suggestion was to configure an empty list instead to avoid passing in any from the host. DNS search is the list of suffixes attempted for domains that are not fully qualified.

The better test mentioned here https://github.com/kubernetes-sigs/kind/issues/3604#issuecomment-2113080086  is to avoid search paths entirely by using a fully qualified domain name and see if that works. https://en.wikipedia.org/wiki/Fully_qualified_domain_name

so try `login.microsoftonline.com.` (note the trailing dot) where `login.microsoftonline.com` was not working.

Also, if by any chance you're using alpine / muslc for your application image, consider using a glibc based base image (e.g. debian), there have historically been DNS issues with muslc's resolver in Kubernetes clusters which is not specific to kind.

**Comment by mastrauckas** [comment] 2024-05-16 23:15
> This is definitely a kubernetes configuration issue and not anything kind is doing. What that configuration issue is though, still > not clear. :)

At first, I thought it was a `kind` issue, which is why the issue was created, Then I started to retract that; thinking it may be a  `coreDNS` issue.   

I believe the evidence is showing its unlikely just a **me** issue, since I have been able to recreate this issue on multiple computers on my network and outside my network.  With that being said, until the issue is known, it could be a configuration issue on my network.

>Rather than running a container to test this, it would be good to run a pod within the context of the k8s cluster to make sure >it's getting the same environment. This page has some useful tips for troubleshooting DNS issues: >https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

So, I did everything in the post with no issues.  

So running 

```cmd
kubectl exec -ti dnsutils -- cat /etc/resolv.conf
```

gave me:

```cmd
search default.svc.cluster.local svc.cluster.local cluster.local 9.9.9.9
nameserver 10.96.0.10
options ndots:5

```

I even ran:

```cmd
kubectl exec -i -t dnsutils -- nslookup login.microsoftonline.com
```
and it worked as expected.

I will continue to do more debugging.

**Comment by mastrauckas** [comment] 2024-05-16 23:23
After looking over the post a second time that @stmcginnis mentioned, I thought I would look at the `coreDNS` logs after getting the error trying to do a lookup on `login.microsoftonline.com`

I went into the pod as I did before with 
```cmd
kubectl run troubleshooting --rm -i --tty --image nicolaka/netshoot -- /bin/bash
````

and then I went to view the logs for `coreDNS`, which I haven't done previously, with command
```cmd
kubectl logs --namespace=kube-system -l k8s-app=kube-dns
```

Which shows a DNS error, shown below:

```cmd
.:53
[INFO] plugin/reload: Running configuration SHA512 = 591cf328cccc12bc490481273e738df59329c62c0b729d94e8b61db9961c2fa5f046dd37f1cf888b953814040d180f52594972691cd6ff41be96639138a43908
CoreDNS-1.11.1
linux/amd64, go1.20.7, ae2bbc2
[ERROR] plugin/errors: 2 login.microsoftonline.com. A: dns: overflow unpacking uint32
.:53
[INFO] plugin/reload: Running configuration SHA512 = 591cf328cccc12bc490481273e738df59329c62c0b729d94e8b61db9961c2fa5f046dd37f1cf888b953814040d180f52594972691cd6ff41be96639138a43908
CoreDNS-1.11.1
linux/amd64, go1.20.7, ae2bbc2
```
So now I have an error to work with!

**Comment by BenTheElder** [comment] 2024-05-17 16:57
https://github.com/coredns/coredns/issues/3305#issuecomment-543146604 suggests that this is a bug in the upstream DNS server https://github.com/coredns/coredns/issues/3305#issuecomment-1782922976

**Comment by BenTheElder** [comment] 2024-05-17 18:33
This seems to be somewhat environment dependent, based on UDP packet size? In any case, we can track it here but it doesn't look like there are good options for the kind project to directly affect this.

We could force DNS over TCP but that's going to be a breaking change, it looks like you could enable this as a workaround like https://github.com/coredns/coredns/issues/3305#issuecomment-1800308700

**Comment by mastrauckas** [comment] 2024-05-17 19:48
> This seems to be somewhat environment dependent, based on UDP packet size? In any case, we can track it here but it doesn't look like there are good options for the kind project to directly affect this.
> 
> We could force DNS over TCP but that's going to be a breaking change, it looks like you could enable this as a workaround like [coredns/coredns#3305 (comment)](https://github.com/coredns/coredns/issues/3305#issuecomment-1800308700)

Sometime this weekend, I may try to use `tshark` to try to troubleshoot the issue.

Either way, in my opinion, `kind` shouldn't do anything because it's not a `kind` issue.

**Comment by BenTheElder** [comment] 2024-05-17 20:28
I think there's a workaround available in https://github.com/coredns/coredns/pull/6277/commits but it's not in a ralease consumable by kuebadm yet because https://github.com/coredns/coredns/issues/6661 ?

If we can help sort that out, we can get it into a future kubernetes release and then into kind.

**Comment by mastrauckas** [comment] 2024-05-22 01:21
> I think there's a workaround available in https://github.com/coredns/coredns/pull/6277/commits but it's not in a ralease consumable by kuebadm yet because [coredns/coredns#6661](https://github.com/coredns/coredns/issues/6661) ?
> 
> If we can help sort that out, we can get it into a future kubernetes release and then into kind.

I will check this out.  I got cough up doing having to handle something this weekend so was not able to troubleshoot.  I will look over what you sent.

**Comment by aojea** [comment] 2024-05-22 07:50
if you can upload the pcap that should be useful, it seems the issue is because a malformed answer that should be visible in the pcap

**Comment by BenTheElder** [comment] 2024-05-22 16:54
@aojea I think coreDNS already has a mitigation merged, but there is not a released container image so kubeadm cannot upgrade. context above.

When coreDNS can release an image for the current tag, we need to get the image mirrored into registry.k8s.io, upgrade kubeadm, and then kind can ship a patched image.

In the meantime your options are somewhat limited unfortunately, you could patch the coreDNS deployment to your own coreDNS image with the new code maybe.

**Comment by mastrauckas** [comment] 2024-06-01 20:16
So, I tested this on a mac book in my network and everything worked just fine.  I am thinking it may be an issue with docker running the docker container in `WSL 2`?

> if you can upload the pcap that should be useful, it seems the issue is because a malformed answer that should be visible in the pcap

I have been trying to get a `pcap` file.   Steps that I have been able to do so far.

- exec into control plane docker container and ran `nslookup login.microsoftonline.com` and it didn't work.
- exec into the docker `wsl ` image with ` wsl -d docker-desktop`, and ran `nslookup login.microsoftonline.com` and it didn't work.  My assumption is that `docker-desktop` is the name server that coreDNS is forwarding request to and docker-desktop is running the wsl container.
- Ran `uname -a` to get operating system information in the wsl docker container.  The details were `Linux MyComputer 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 Linux`
- The WSL doesn't appear to have a package manager installed, so I'm trying to figure out how to download tshark so I can get a pcap file.

**Comment by aojea** [comment] 2024-06-03 22:48
no worries, is fine, I just was curious  ... maybe there is some sort of dns proxy in WSL?

**Comment by BenTheElder** [comment] 2024-07-31 18:22
I'm working with folks on getting coreDNS updated in kubernetes / kubeadm here https://github.com/kubernetes/kubernetes/issues/126443

It will probably be in 1.32 or 1.31.1 at the earliest, we're not realistically going to make the cutoff for 1.31.0 (we were blocked on upstream coreDNS release)

**Comment by BenTheElder** [comment] 2024-09-03 17:07
Note: landed https://github.com/kubernetes/kubernetes/issues/126443 into 1.30 and 1.31 branches for upcoming patch releases (not 1.28, 1.29 yet, earlier branches are also no longer supported for patching).

We can expect the fix to be available at the next patch releases which are due in a week: https://kubernetes.io/releases/patch-releases/

**Comment by BenTheElder** [comment] 2024-11-08 19:49
1.31.2 image will be in kind v0.25.0, which I'm preparing now.

**Closed by BenTheElder** 2024-11-08 19:49 UTC
Labels: kind/bug, lifecycle/active, kind/external

**Comment by BenTheElder** [comment] 2024-11-08 19:50
(which has coredns 1.11.3)
