### ISSUE TITLE
[kong ingress] Documentation Bug: ingress example fails applying patch

### ISSUE THREAD

**Issue by vsoch** [kubernetes-sigs/kind#3265] opened 2023-06-05 14:21 UTC
Hi! I'm following the ingress example [here](https://kind.sigs.k8s.io/docs/user/ingress/#ingress-kong) and when applying the Kong patch, I get:

```bash
$ kubectl patch deployment -n kong proxy-kong -p '{"spec":{"replicas":1,"template":{"spec":{"containers":[{"name":"proxy","ports":[{"containerPort":8e3,"hostPort":80,"name":"proxy","protocol":"TCP"},{"containerPort":8443,"hostPort":443,"name":"proxy-ssl","protocol":"TCP"}]}],"nodeSelector":{"ingress-ready":"true"},"tolerations":[{"key":"node-role.kubernetes.io/control-plane","operator":"Equal","effect":"NoSchedule"},{"key":"node-role.kubernetes.io/master","operator":"Equal","effect":"NoSchedule"}]}}}}'
```
```console
The Deployment "proxy-kong" is invalid: spec.template.spec.containers[0].ports[1].name: Duplicate value: "proxy"
```

The content is served from [here](https://github.com/kubernetes-sigs/kind/blob/main/site/content/docs/user/ingress.md) and I believe the file that needs updating is [this one](https://github.com/kubernetes-sigs/kind/blob/main/site/static/examples/ingress/kong/deployment.patch.json). If it's something I can help with via PR, would love to! I'm new to ingress with kind (was just testing it out) so I'd need your guidance about which proxy to delete or rename. Thank you!

**Comment by aojea** [comment] 2023-06-06 00:13
@vsoch so you are all over the place recently ;) glad to have new contributions.

This is a problem that has been discussed these days here https://github.com/kubernetes/kubernetes/issues/113482

@apelisse is there any kubectl flag that allow to apply these patches without conflicts or should we rework our patches?

**Comment by aojea** [comment] 2023-06-07 18:19
maybe someone can figure out in the meantime another patch format https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/ that avoids this problem

**Comment by apelisse** [comment] 2023-06-07 20:36
Yeah, this is definitely related to that other issue we've been discussing a lot about.

The problem is that the merge key for the ports is NOT the name field and so who knows how this is merged, and the merge probably ends-up duplicating the `name=proxy` entry, which is invalid.

IOW, We're working on this, in the mean time ... I don't know enough to know what this is trying to do?

**Comment by BenTheElder** [comment] 2023-06-09 16:12
@apelisse this adds a node-selector to a node with a port forward to the host and remaps the ingress container's ports to use a hostPort for the ports that align with the host=>node ports.

Against the otherwise standard kong installation.

**Comment by BenTheElder** [comment] 2023-06-09 16:15
We want to replace name=proxy port, I guess we could craft a 6902 patch.

**Comment by AryanSharma9917** [comment] 2023-06-22 19:13
Hi @aojea I think to resolve the issue, I suggest making a minor adjustment to the patch command. You can accomplish this by modifying the value of the "name" field for the new port. In particular, change the existing name "proxy-ssl" to a different, unique name like "proxy-ssl-new". By implementing this modification, you ensure that the new port is assigned a distinct name, effectively eliminating the "Duplicate value" error that was encountered earlier.

**Comment by aojea** [comment] 2023-06-22 20:07
go for it, just test it and submit a change with your proposal and add the explanation on the description

**Closed** 2023-07-30 21:48 UTC
Labels: kind/bug, help wanted

**Comment by vsoch** [comment] 2023-07-30 21:49
Thank you!
