### ISSUE TITLE
how to start k8s dev version "kind" after reboot

### ISSUE THREAD

**Issue by amolkesare** [kubernetes-sigs/kind#1217] opened 2020-01-02 05:00 UTC
Hi,

I have installed k8s dev prog called kind on Ubuntu vm. 
After installing kind, I created cluster and launched pods as well. 

But after reboot, I am not able to see that cluster using kubectl or kind command:
root@debian1:~# kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server 127.0.0.1:41605 was refused - did you specify the right host or port?
root@debian1:~# kind get clusters
root@debian1:~# 

Is there any command do I have to run to start k8s

**Comment by BenTheElder** [comment] 2020-01-02 18:53
this is a duplicate of #148, we're working on it.

do not reboot the host, or else recreate the cluster. these are cheap ephemeral test cluster and do not currently support rebooting the host.

**Closed by BenTheElder** 2020-01-02 18:53 UTC
Labels: triage/duplicate, triage/support
