### ISSUE TITLE
Docker Hub tags for v1.15.4 and v1.14.7?

### ISSUE THREAD

**Issue by jdolitsky** [kubernetes-sigs/kind#948] opened 2019-10-13 22:06 UTC
Wondering if these versions can be built and pushed to [kindest/node](https://hub.docker.com/r/kindest/node/tags) repo on Docker Hub? 

If there is somewhere in automation scripts to enable this please let me know and I can add.

**Comment by aojea** [comment] 2019-10-13 22:42
this is a duplicate of https://github.com/kubernetes-sigs/kind/issues/863#issuecomment-538765735 , please read the comment I linked to understanding current status

**Comment by BenTheElder** [comment] 2019-10-13 23:24
This is https://github.com/kubernetes-sigs/kind/issues/197. I will be working on this in Q4.

**Closed by BenTheElder** 2019-10-13 23:24 UTC
Labels: kind/feature

**Comment by BenTheElder** [comment] 2019-10-13 23:27
Also, the issue will be infra mainly rather than the scripts. The Kubernetes CI infra is not suitably secure for publishing images. We'll figure something out.

**Comment by jdolitsky** [comment] 2019-10-14 13:16
ok thank you!
