### ISSUE TITLE
Number of desired replicas not matching with the actually existing ones after PC restart and manual pod deletion

### ISSUE THREAD

**Issue by Kavuti** [kubernetes-sigs/kind#2210] opened 2021-04-21 20:49 UTC
I created a basic cluster configuration trying to deploy Keycloak on my PC. Here is the Deployment manifest I wrote:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:12.0.4
        resources:
          limits:
            cpu: "500m"
            memory: "1G"
        env:
        - name: KEYCLOAK_USER
          valueFrom: 
            secretKeyRef:
              name: keycloak-secret
              key: keycloakUser
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: keycloakPassword
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: postgres-db.default.svc.cluster.local
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: keycloakDbUser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: keycloakDbPassword
        - name: DB_SCHEMA
          value: public
        - name: DB_DATABASE
          value: keycloak
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
```

The manifest, together with the configuration of a Service, a PV, PVC and Ingress, is correctly applied without any warning or error. The Deployment is correctly created along with the correspondent ReplicaSet and the 3 replicas.
Then I left and shut down my PC. When I came back and restarted my PC, I started making my tests with the deployed pods. I deleted one pod manually with

`kubectl delete pod keycloak-xxxxxxxxx-xxxxx -n keycloak`

and the pod has been correctly deleted. I was then expecting that the currently active Replicaset would replace the deleted pod with a new one in order to match the number of 3 replicas. Instead, no pod is created after the deletion, but examining the ReplicaSet, the Desired, Current and Ready pods are still 3. If I call a `kubectl describe` on the ReplicaSet, just the first three pod creation events are showed, all successful. Deleting the other pods, the ReplicaSet and the Deployment, does not make any difference. Even if I recreate the deployment by reapplying the manifest above, no ReplicaSet is created (and obviously no pod).

I tried to troubleshoot the cluster by exporting the logs with `kind export logs` but I didn't notice any strange log among the control-plane api logs and workers kubelet logs.

I have this problem every time I restart my PC. I had this problem also with my previous PC, with the same version of kind. For now, I'm deleting and recreating my cluster every time, but I can do it just because I have a few services running that I can easily restart, even if it's a bit time consuming.

Since I'm not familiar with Kubernetes yet, I'm sorry if I'm missing some important information. I'm here to give you any information is needed to find the origin of the problem.

Here is the basic tools and system information:
- kind version: v0.9.0
- Kubernetes version: v1.19.1
- Docker version: 20.10.5
- OS: Manjaro Linux

**Comment by BenTheElder** [comment] 2021-04-21 21:01
quick notes:

- unless you have a specific use case for workers I recommend using a single node which behaves more reliably on reboot and has less overhead. there are known bugs with restarting and e.g. multiple control plane nodes. (See the issue tracker)

- you will probably be better served by a deployment, daemonset, or statefulset than using replicaset directly

- deletion behavior of pods, how replicasets beahve, etc. is kubernetes, not kind, and we wouldn't debug that here just as a matter of maintainer bandwidth. if you can show a bug in _kind_ please file a bug with us, but if it's a kubernetes bug please file it against the kubernetes repo.

- kind v0.9.0 is outdated so if this were a kind bug we would be patching against the upcoming v0.11.0

**Comment by Kavuti** [comment] 2021-04-21 21:17
Actually I'm only examining the ReplicaSet generated by the Deployment. I'm not creating ReplicaSets directly but all I do is applying the manifest above. I'm having this problem only with kind but not with other distributions. Anyway, I will try to not use a multi-node cluster and go for a single node. I'll give you a feedback whether it resolves the problem or not.

**Comment by FedericoAntoniazzi** [comment] 2021-04-21 21:53
Hi everybody, I've been able to replicate the bug even on kind v0.10.0. I've tried on v0.9.0 too but I got the same result and I noticed the issue occurs only on multi node clusters.

**Comment by aojea** [comment] 2021-04-21 22:24
multinode clusters have issues rebooting , they may come back with different ips 
https://github.com/kubernetes-sigs/kind/issues/2045

**Comment by BenTheElder** [comment] 2021-06-24 08:13
@Kavuti were you able to confirm? @FedericoAntoniazzi suggests this is only for multi-node, which as @aojea said is covered in #2045

**Comment by Kavuti** [comment] 2021-06-29 12:10
Yes. The problem is present only for multi-node clusters. I recreated the cluster as a single node and I'm not having this error anymore, so I will go on with this configuration for now.

**Comment by BenTheElder** [comment] 2021-06-29 19:29
i think this is a dupe of https://github.com/kubernetes-sigs/kind/issues/2045, in effect multi-node clusters have a high chance to not come back up healthy, it needs fixing, but nobody is working on this. it's tricky and we mostly focus on trying to bring down the costs of bringing up a new cluster.

/triage duplicate

**Closed** 2021-06-29 19:29 UTC
Labels: kind/bug, priority/awaiting-more-evidence, triage/duplicate
