### ISSUE TITLE
Horizontal Pod Autoscale does not scale pods

### ISSUE THREAD

**Issue by serrodcal** [kubernetes-sigs/kind#2047] opened 2021-01-31 14:12 UTC
**What happened**: It seems like Horizontal Pod Autoscale (a.k.a HPA) doesn't work because the current resource utilisation is unknown:

```sh
$ kubectl get hpa
NAME   REFERENCE        TARGETS                        MINPODS   MAXPODS   REPLICAS   AGE
app    Deployment/app   <unknown>/15%, <unknown>/15%   1         5         1          8m36s
```

**What you expected to happen**: HPA should work fine

**How to reproduce it (as minimally and precisely as possible)**: Apply the following YAML

```yml
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: serrodcal/quarkus-locust:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 10M
              cpu: 100m
            limits:
              memory: 10M
              cpu: 100m
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 15
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 15
```

Generate load with:

```sh
$ kubectl run -i --tty load-generator --rm --image=busybox --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://app:8080/hello; done"
```

**Anything else we need to know?**: I'm not sure about the reason the HPA does not work, but I suspect it is related to the cluster can't get metrics.

**Environment:**

- kind version: (use `kind version`): `kind v0.10.0 go1.15.7 darwin/amd64`
- Kubernetes version: (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version: (use `docker info`):

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 492
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: 5M4Y:MA52:VX76:WJAW:GCBB:UO7H:54SL:3ORY:QTT2:O5HK:QDYZ:FJ2L
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 49
  Goroutines: 51
  System Time: 2021-01-31T14:09:49.6574622Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- OS (e.g. from `/etc/os-release`): macOS Catalina 10.15.7

**Comment by serrodcal** [comment] 2021-01-31 21:04
I've tried [this example](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/) and it doesn't work either.

**Comment by BenTheElder** [comment] 2021-02-01 05:49
root cause is a dupe of: https://github.com/kubernetes-sigs/kind/issues/1963 https://github.com/kubernetes-sigs/kind/issues/398

one of these is easy, but only insecurely.
the other (actually limiting node resources) is ... challenging to do cleanly. We've had a long chat with cAdvisor / SIG node about this, you can find some of it following through from the issues above. For the moment you're going most likely to want to use a VM based solution.

**Comment by serrodcal** [comment] 2021-02-01 07:58
Wow, interesting conversations...

I'm not familiar with the internal stuff of Kubernetes but is there any chance of add a page in [https://kind.sigs.k8s.io/](https://kind.sigs.k8s.io/) to try to collect and give a guide to the user about this? I mean, in the same way the Ingress Controller...

It's true if you want provide K8s as minimal as possible, maybe the metrics are not in the scope. But, on the other hand, if we need to use Kind to have a sandbox in which is able to test something likethe scaling, it will be very useful. So, as I mentioned before, something like a guidance.

Regarding VM based solution, they are so heavy and, in my personal case, I have not been able to get the virtual machine to start a second time hahaha.

Thanks a lot for your reply. Close this issue if you consider it.

**Comment by BenTheElder** [comment] 2021-02-02 05:18
> I'm not familiar with the internal stuff of Kubernetes but is there any chance of add a page in https://kind.sigs.k8s.io/ to try to collect and give a guide to the user about this? I mean, in the same way the Ingress Controller...

That's been brought up in #398, for #1963 I don't think we have a great answer yet.

> It's true if you want provide K8s as minimal as possible, maybe the metrics are not in the scope. But, on the other hand, if we need to use Kind to have a sandbox in which is able to test something likethe scaling, it will be very useful. So, as I mentioned before, something like a guidance.

I recommend having something else (perhaps a simple script) scale up your app predictable for testing, instead of relying on HPA, since the goal is to test your app, not HPA. This can give you more repeatable testing anyhow.

Few apps consume the metrics directly in my experience.

It's less that "metrics are not in scope" and more that "including them would probably be misleading anyhow, and nobody interested in this has cooked up a good guide for this" and it's not clear that most of our users need this. If a good guide is written, we can see about placing it / linking to it in our docs.

> Regarding VM based solution, they are so heavy and, in my personal case, I have not been able to get the virtual machine to start a second time hahaha.

That's fair, but with a VM solution you can reliably partition your host into resources. At least with current kind this won't work well and is due to upstream limitations. In the future under cgroupsv2 it should be easier to do the limiting part correctly I think, but there will still be cAdvisor reporting the entire host's resources and kubelet consuming it directly, which we don't have a good path forward on.

I'm going to close this for now to take it out of the tracker, but I do think #398 and #1963 should be fixed ideally (at which point this issue should be fixed)

**Closed by BenTheElder** 2021-02-02 05:18 UTC
Labels: kind/bug
