### ISSUE TITLE
Kind v0.10.0 cluster fails to schedule pods after host restarts

### ISSUE THREAD

**Issue by optimus-kart** [kubernetes-sigs/kind#2080] opened 2021-02-19 05:57 UTC
**What happened**:
With the latest version of kind (v0.10.0) pods scheduling does not work 

**What you expected to happen**:
The cluster should work even after the host machine restarts

**How to reproduce it (as minimally and precisely as possible)**:
Install latest kind cluster (v0.10.0), create a deployment, restart the host machine, Once the host machine is up again delete the pod. the pod will not be recreated.

**Anything else we need to know?**:

This works fine in v0.8.0.

**Environment:**

- kind version: (use `kind version`): 0.10.0
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Docker version: (use `docker info`): 20.10.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04 LTS

**Comment by BenTheElder** [comment] 2021-02-19 07:14
Is this a multi-node cluster? If so this is already in another tracked issue.

**Comment by BenTheElder** [comment] 2021-02-19 07:15
Given that it worked fine for you in v0.8.0 I would hazard that either:
- you got lucky previously
- it's a regression in kubeadm/Kubernetes <-> kind since we upgraded the default version. Does this happen with the same minor Kubernetes version? (Images in the release notes)

**Comment by optimus-kart** [comment] 2021-02-19 07:22
@BenTheElder  yes it is a multi node cluster.

**Comment by BenTheElder** [comment] 2021-02-19 07:54
https://github.com/kubernetes-sigs/kind/issues/2045
/triage duplicate

**Comment by BenTheElder** [comment] 2021-02-21 03:45
closing as a dupe for now, though I'd be very interested if you could add details to #2045 confirming exactly how you used kind on each versions (config, images, etc.) that worked and didn't work.

**Closed by BenTheElder** 2021-02-21 03:45 UTC
Labels: kind/bug, triage/duplicate
