### ISSUE TITLE
line 6: field constraints not found in type v1alpha4.Node

### ISSUE THREAD

**Issue by bestofman** [kubernetes-sigs/kind#3048] opened 2022-12-30 02:52 UTC
I am trying `kind create cluster --config kind-config.yaml` to create a kind cluster using the following `kind-config.yaml` file:

    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
    - role: worker
      constraints:
        memory: "512m"
        cpu: "4"

But I get this result:

    ERROR: failed to create cluster: unable to decode config: yaml: unmarshal errors:
      line 6: field constraints not found in type v1alpha4.Node

What I am trying to do is doing something like bellowing but for a `Kind` cluster instead of `minilube`:

`minikube start --memory 5120 --cpus=4`

**Comment by aojea** [comment] 2022-12-30 09:35
/close

This is a duplicate of https://github.com/kubernetes-sigs/kind/issues/877#issuecomment-689365559

docker containers can not emulate resources , you need VMs or fake the linux subsystem to emulate VMs with containers, that is not something we have implemented in KIND because of the complexity.

Thanks

**Closed by aojea** 2022-12-30 09:35 UTC
Labels: kind/support
