### ISSUE TITLE
[zfs] [dupe] Timeout starting control-plane

### ISSUE THREAD

**Issue by pplanel** [kubernetes-sigs/kind#1968] opened 2020-12-08 19:12 UTC
**What happened**:
cluster not created

**What you expected to happen**:
cluster created

**How to reproduce it (as minimally and precisely as possible)**:
```
# Get arkade, and move it to $PATH
curl -sLS https://dl.get-arkade.dev | sh
sudo mv arkade /usr/local/bin/

# Run Kubernetes locally
arkade get kind 

# Kubernetes CLI
arkade get kubectl

# Create a cluster
kind create cluster

```
**Anything else we need to 

**Environment:**

- kind version: (use `kind version`):
`kind v0.9.0 go1.15.2 linux/amd64`

- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-16T17:18:52Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
- Docker version: (use `docker info`):
```
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 8
  Paused: 0
  Stopped: 3
 Images: 33
 Server Version: 19.03.13
 Storage Driver: zfs
  Zpool: rpool
  Zpool Health: ONLINE
  Parent Dataset: rpool/ROOT/ubuntu_8t50w5/var/lib
  Space Used By Parent: 14039322624
  Space Available: 154048020480
  Parent Quota: no
  Compression: lz4
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-29-generic
 Operating System: Ubuntu 20.10
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.25GiB
 Name: core
 ID: XB4R:Z3WD:52QC:OHNP:SLMC:EVS6:SZKT:NIWB:QWGP:WTQA:N3Y3:F5PI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
```

**Comment by BenTheElder** [comment] 2020-12-08 20:21
Please provide more information per the bug template. We can't take any action just based on control plane startup timing out, this could mean any number of things are wrong with your host.

**Comment by pplanel** [comment] 2020-12-08 20:48
Okay, I edited the original post. thanks.

**Comment by BenTheElder** [comment] 2020-12-08 20:58
ah, this is the ZFS bug, sorry about that.

you'll have to install kind from HEAD, we've got a patch for that in but not released yet.

clone the repo then from the repo run `make build` and then the binary is in `bin/kind`, you don't need any special tools installed, just bash/make/git. you can copy the binary into your path.

I don't know how arkade manages versions, but we'll have a release soon, we need to look into https://github.com/kubernetes-sigs/kind/issues/1969

**Comment by BenTheElder** [comment] 2020-12-08 20:59
dupe of https://github.com/kubernetes-sigs/kind/issues/1719

**Closed by BenTheElder** 2020-12-08 20:59 UTC
Labels: kind/bug, triage/duplicate
