### ISSUE TITLE
Not able to start kind cluster in Mac(M2) using podman [podman exec broken upstream due to mismatched client/server version]

### ISSUE THREAD

**Issue by kamalkraj** [kubernetes-sigs/kind#3439] opened 2023-11-29 08:47 UTC
podman version 4.8.0
kind version 0.20.0

```
kind create cluster -v 1

using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Creating cluster "kind" ...
DEBUG: podman/images.go:67] Pulling image: docker.io/kindest/node@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72 ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
 ✓ Preparing nodes 📦
 ✗ Writing configuration 📜
Deleted nodes: ["kind-control-plane"]
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "podman exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 255
Command Output: v1.27.3Error: unmarshalling error into &errorhandling.ErrorModel{Because:"", Message:"", ResponseCode:0}, data "Not Found\n": invalid character 'N' looking for beginning of value
Stack Trace:
sigs.k8s.io/kind/pkg/errors.WithStack
	sigs.k8s.io/kind/pkg/errors/errors.go:59
sigs.k8s.io/kind/pkg/exec.(*LocalCmd).Run
	sigs.k8s.io/kind/pkg/exec/local.go:124
sigs.k8s.io/kind/pkg/cluster/internal/providers/podman.(*nodeCmd).Run
	sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/node.go:146
sigs.k8s.io/kind/pkg/exec.OutputLines
	sigs.k8s.io/kind/pkg/exec/helpers.go:81
sigs.k8s.io/kind/pkg/cluster/nodeutils.KubeVersion
	sigs.k8s.io/kind/pkg/cluster/nodeutils/util.go:37
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.getKubeadmConfig
	sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config/config.go:158
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.(*Action).Execute.func1.1
	sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config/config.go:90
sigs.k8s.io/kind/pkg/errors.UntilErrorConcurrent.func1
	sigs.k8s.io/kind/pkg/errors/concurrent.go:30
runtime.goexit
	runtime/asm_arm64.s:1172
```

**Comment by kamalkraj** [comment] 2023-11-29 08:57
with podman `4.7.2` working properly

**Comment by am3o** [comment] 2023-11-29 09:17
Same issue with podman version `4.8.0`.

**Comment by BenTheElder** [comment] 2023-11-29 18:59
> failed to get file: command "podman exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 255
Command Output: v1.27.3Error: unmarshalling error into &errorhandling.ErrorModel{Because:"", Message:"", ResponseCode:0}, data "Not Found\n": invalid character 'N' looking for beginning of value

this looks like a podman bug. we're not doing any unmarshalling ourselves, just asking podman to exec cat of a plain text file ...

**Comment by gnomefin** [comment] 2023-11-30 07:23
I also use podman 4.7.2 and it works: https://github.com/containers/podman/releases/tag/v4.7.2 there is something wrong with 4.8.0

**Comment by vietk** [comment] 2023-11-30 07:40
Hello, 
I got the same issue but with a Mac with an Intel Chip 

<img width="1046" alt="Screenshot 2023-11-30 at 08 40 16" src="https://github.com/kubernetes-sigs/kind/assets/1568850/1d182baa-73b9-4b2a-988e-71298e06b06c">

**Comment by BenTheElder** [comment] 2023-11-30 20:12
It looks like it's confirmed that downgrading podman version will fix it? https://github.com/containers/podman/issues/20821

**Comment by BenTheElder** [comment] 2023-12-01 19:38
Should be fixed upstream https://github.com/containers/podman/pull/20831

**Comment by BenTheElder** [comment] 2023-12-04 17:44
https://github.com/containers/podman/issues/20821#issuecomment-1834592191 may also be an option, aside from upgrading to the next release with CLI skew fix.

**Closed** 2023-12-05 19:44 UTC
Labels: kind/external
