### ISSUE TITLE
Add Support for PowerLinux

### ISSUE THREAD

**Issue by reece-oliver** [kubernetes-sigs/kind#2662] opened 2022-03-07 12:16 UTC
**What would you like to be added**:
Add support to be able to run the kind binaries on PowerLinux and be able to create node images for that architecture as well. 

**Why is this needed**:
We develop our software for the PowerLinux Infrastructure and use kind to run tests in isolated environment. We need to ability to able to run these tests on PowerLinux arch so that we can find any bugs or regressions.

**Comment by aojea** [comment] 2022-03-07 12:30
/help wanted

I don't think that any of the maintainers have time or resources to do this ... but happy to review patches

**Comment by BenTheElder** [comment] 2022-03-07 18:42
I would prefer to see substantial demand before committing our resources to doing so.

It is very slow to build for additional platforms for each growing number of kubernetes versions we support.

We have seen significant flakiness from relatively builds for unused platforms like s390x and PPC64LE and have even needed to disable them in the past.

It is possible to do this yourself without our doing so. You will need to build the various images and binaries.

**Comment by BenTheElder** [comment] 2022-03-07 18:57
AFAICT the binary already supports powerlinux still, we still publish ppc64le binaries for now. You must build the node images yourself.

**Comment by BenTheElder** [comment] 2022-04-19 03:42
I think any potential remainder of this is a dupe of https://github.com/kubernetes-sigs/kind/issues/2707 (though this was filed sooner, it is pretty non-specific, the other issue has more discussion on that topic)

**Closed** 2022-04-19 03:41 UTC
Labels: kind/feature, priority/backlog
