### ISSUE TITLE
Minikube 'docker-env'

### ISSUE THREAD

**Issue by costinm** [kubernetes-sigs/kind#460] opened 2019-04-29 18:58 UTC
**What would you like to be added**:

Add an option to expose the DIND environment to the host.

Could be a port forward plus starting docker with the port option.

**Why is this needed**:

To avoid copy of the docker image - user could use the Kind dind docker to run docker build, similar with minikube.

**Comment by BenTheElder** [comment] 2019-04-29 19:18
we're moving off of docker on the nodes (later today hopefully!), containerd will allow us to be more performant with a smaller image.

this is a dupe of https://github.com/kubernetes-sigs/kind/issues/220

**Closed by BenTheElder** 2019-04-29 19:18 UTC
Labels: kind/feature, triage/duplicate
