### ISSUE TITLE
Consider using a default file path when --config=""

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/kind#1938] opened 2020-11-20 19:24 UTC
**What would you like to be added**:
Currently, when kind creates a cluster with `kind create cluster` and the `config` flag is not specified, or is an empty string, the code https://github.com/kubernetes-sigs/kind/blob/65a3f36d6d46e5469bc56573d8de68427da7d5b1/pkg/internal/apis/config/encoding/load.go#L36-L37 creates an empty Config and calls `SetDefaultsCluster`.

This is a good fallback for lots of users that are starting up, although it'd be great if before using this fallback we default the config to a well specified default path e.g. `$HOME/.config/kind/default.yaml`. 

**Why is this needed**:

The feature requested above would allow users to customize their default clusters without the need to specify any flags; if the file is not specified, we can fallback to the current logic.

**Comment by BenTheElder** [comment] 2020-11-20 19:28
ooh this is a great bug haha.

do we know what client-go/kubectl do here? this makes sense to me but we do
try to match the behavior 1:1

**Comment by vincepri** [comment] 2020-11-20 19:34
If we follow the `--kubeconfig` example, we could default to an environment variable, instead of hardcoding a path based on some convention, that would allow the use case above and retain similarities with kubectl

**Comment by BenTheElder** [comment] 2020-11-20 19:44
I had a brain fart and thought this was about KUBECONFIG for a second (I read this in my inbox only).. 🙃 

This is an interesting idea

**Comment by vincepri** [comment] 2020-11-20 19:50
Happy to contribute something after we reach some agreement on the outcome we'd like

**Comment by BenTheElder** [comment] 2020-12-16 06:33
I've thought about this, and I'm concerned for the impact on all the projects shipping `kind` in their development scripts etc.

Suddenly for some users they will get unexpected behavior and probably lose a lot of time debugging why things don't work on a "default" cluster that isn't actually default. This impacts reproducibility and would effectively force everyone to always specify a config to avoid this.

kubeconfig on the other hand really only provides credentials, I don't think kubectl has any object defaults / settings in files that aren't explicitly specified as inputs. I don't think any other tools in the space do either?

**Comment by vincepri** [comment] 2020-12-17 17:40
What about falling back to a well defined environment variable instead? Like today you could export `KUBECONFIG` to route `kubectl` (or other tools respecting that variable) to a config.

If we'd add some support for a `KINDCONFIG` environment variable, or similar, we could keep the current fallback.

> Suddenly for some users they will get unexpected behavior and probably lose a lot of time debugging why things don't work on a "default" cluster that isn't actually default

We could log out when we're using a configuration file, and say where it's coming from for example?

**Comment by BenTheElder** [comment] 2020-12-17 21:56
KUBECONFIG isn't really equivalent though because it doesn't change the objects created, and it applies equally to all commands.

I think even if we log something people are very bad about sharing relevant logs when filing bugs, and it'll still be a surprising behavioral change.

What are you looking to set in default config, actually?
A lot of these things are candidates for *the* default config, like the issue about service account projection.

**Comment by vincepri** [comment] 2021-01-04 16:36
I was mostly interested to place a default cluster config on a machine. When using `kind create cluster`, we could try to look in a predefined default path if a valid config exists, otherwise proceed with the current behavior

**Comment by BenTheElder** [comment] 2021-01-22 01:50
Sorry I failed to actually post back my thoughts here :(

I think this feature is actually potentially a tad dangerous and here's why:

Security of the docker socket, chosen KUBECONFIG directory, etc. are all up to the user, admittedly the kubeconfig + kind is probably risky in practice but that's true for *lots* of clusters and something already created that we benefit from compatibility with ...

if we add a $HOME/.kind/config.yml, now processes with access to this file can alter how default clusters are created, in particular they can replace the node image with a malicious image. This is potentially very nasty and most users probably wouldn't be aware of it. While we could try to restrict the directory permissions etc., I think most users run kind under their $USER and restricting access to $USER wouldn't help much, and this is easy to mess up.

Unlike KUBECONFIG or docker.sock, this becomes a totally new and unknown danger for users, I think that's not something we want to take on.

**Comment by BenTheElder** [comment] 2021-02-06 02:00
cc @kubernetes-sigs/kind-maintainers

**Comment by vincepri** [comment] 2021-02-06 03:05
@BenTheElder Feel free to close if that's not a great idea, I agree it has implications that's why I opened an issue to chat about it :)

**Comment by aojea** [comment] 2021-02-06 10:47
I think that is too late for a change like this ... and that will keep state for the default cluster, i.e. I do `kind create cluster`, something happen and file is corrupted,changed or disappear and I restart the cluster ...

**Comment by BenTheElder** [comment] 2021-02-07 02:15
Thanks @vincepri. I'll close this for now, but this is a very interesting suggestion :-)

**Closed by BenTheElder** 2021-02-07 02:15 UTC
Labels: kind/feature
