### ISSUE TITLE
Fails to create a cluster using podman provider on macOS

### ISSUE THREAD

**Issue by bodz1lla** [kubernetes-sigs/kind#2520] opened 2021-11-02 13:02 UTC
**What happened**:

```bash
$ KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster 
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Cgroup controller detection is not implemented for Podman. If you see cgroup-related errors, you might need to set systemd property "Delegate=yes", see https://kind.sigs.k8s.io/docs/user/rootless/
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦
 ✗ Writing configuration 📜
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "podman exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 125

$ kind export logs
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Exporting logs for cluster "kind" to:
/private/var/folders/sx/gyc4n7617fd3xbkz9yhzgj0m0000gn/T/422846131
ERROR: [command "podman exec --privileged kind-control-plane sh -c 'tar --hard-dereference -C /var/log/ -chf - . || (r=$?; [ $r -eq 1 ] || exit $r)'" failed with error: exit status 125, [command "podman exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 125, command "podman exec --privileged kind-control-plane journalctl --no-pager" failed with error: exit status 125, command "podman exec --privileged kind-control-plane journalctl --no-pager -u containerd.service" failed with error: exit status 125, command "podman exec --privileged kind-control-plane journalctl --no-pager -u kubelet.service" failed with error: exit status 125]]
```
**How to reproduce it (as minimally and precisely as possible)**:

`$ KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster `

**Anything else we need to know?**:

```bash
$ podman machine list
NAME                     VM TYPE     CREATED     LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        4 days ago  Currently running  1           2.147GB     10.74GB

$ podman info | grep cgroup
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
 ```
 
**Environment:**

- kind version: v0.11.1
- Kubernetes version: Client v1.22.2, Server v1.21.1
- Podman version: 3.4.1
- macOS Big Sur 11.6

**Comment by aojea** [comment] 2021-11-02 16:08
I'm going to close it as duplicate of https://github.com/kubernetes-sigs/kind/issues/2233
You can read more in this comment https://github.com/kubernetes-sigs/kind/issues/2233#issuecomment-837861552
short history, podman remote is not easy to implement
Thanks for reporting
/close

**Closed** 2021-11-02 16:09 UTC
Labels: kind/bug
