### ISSUE TITLE
Docker Options in the Kind Config

### ISSUE THREAD

**Issue by rrichardson** [kubernetes-sigs/kind#1506] opened 2020-04-23 16:45 UTC
**What would you like to be added**: A section in the Kind Config that allows for manipulation of Docker options.  I have a need to specify the DNS server that is configured in the host, but I could see the need for other features in addition to the volume mounts and port-mapping options that are currently provided. 

**Why is this needed**:   For me specifically, I am building a development environment around kind that uses a private docker registry, this registry is accessed via private DNS records through a VPN.  This DNS server is configured to be accessed on the host,  however,  when docker runs, it uses the DHCP provided DNS server as the container host's DNS server, this makes it impossible to resolve the private registry URL.   

Changing the Coredns config does not help, since the docker pull in k8s apparently uses the container host's DNS server.  

Changing /etc/docker/daemon.json to fix a DNS server also does not work, since Docker uses the DHCP supplied DNS server as the first option, before consulting the fallback. 

As far as I can tell, my only solution is to set `--dns=my-private-dns-server` when kind is started.  I would love to hear of some alternate approaches that I can roll into a deployment script.

**Comment by rrichardson** [comment] 2020-04-23 18:00
Looking at the implementation and the `Providers` interface,  I now see that passing raw commands straight through might not be the best idea.  

The good news, though, is that both Podman and Docker support a `--dns`  flag that allows one to specify the dns server for the container.  Perhaps we can yet have a `ContainerRuntimeConfig` property in the Kind config which contains certain, named settings?

**Comment by BenTheElder** [comment] 2020-04-23 18:31
Hi, we're about to depend on docker embedded DNS in user defined networks to fufill #148 (enabling kind clusters to not break when the host / docker restarts).

We won't be able to implement that in podman trivially, but it won't break the interface, they'll just handle returning node endpoints different.

Once this is implemented your DNS should "just work" :tm: 

https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge

This is up next after #1471, which has a PR out but we're diagnosing some unusual CI failures.

**Comment by BenTheElder** [comment] 2020-04-25 08:00
https://github.com/kubernetes-sigs/kind/pull/1508 should obviate this, it will use the host DNS via docker's embedded DNS proxy.

**Comment by BenTheElder** [comment] 2020-04-25 08:01
this is a dupe of https://github.com/kubernetes-sigs/kind/issues/284

**Closed by BenTheElder** 2020-04-25 08:01 UTC
Labels: kind/feature
