### ISSUE TITLE
Unable to create kind cluster on crostini

### ISSUE THREAD

**Issue by samos123** [kubernetes-sigs/kind#1397] opened 2020-03-11 18:36 UTC
**What happened**:
Trying to create cluster with Kind on crostini but it failed

```
kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 137
```

**What you expected to happen**:
Success

**How to reproduce it (as minimally and precisely as possible)**:
On a chromebook with crostini install docker and run
`kind create cluster`

**Anything else we need to know?**:

**Environment:**
Crostini

- kind version: (use `kind version`):
`kind v0.7.0 go1.13.6 linux/amd64`

- Kubernetes version: (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`

- Docker version: (use `docker info`):
```
Client:
 Debug Mode: false

Server:
 Containers: 158
  Running: 1
  Paused: 0
  Stopped: 157
 Images: 674
 Server Version: 19.03.4
 Storage Driver: btrfs
  Build Version: Btrfs v4.7.3
  Library Version: 101
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc runc-chromeos
 Default Runtime: runc-chromeos
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: a0b7d6dc09b58d2f44dd61c304a66d9249e56c8f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.79-07511-ge32b3719f26b
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 13.47GiB
 Name: penguin
 ID: E6HU:DQ5L:BN27:3SVU:FV5X:Z6RM:JFYO:N2LA:LBJR:IGYC:XJF3:J6VT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: samos123
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- OS (e.g. from `/etc/os-release`):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by BenTheElder** [comment] 2020-03-11 20:03
Dupe of https://github.com/kubernetes-sigs/kind/issues/763

**Comment by BenTheElder** [comment] 2020-03-11 20:07
See also https://kind.sigs.k8s.io/docs/user/known-issues/#chrome-os

**Closed by BenTheElder** 2020-03-11 20:07 UTC
Labels: kind/bug
