### ISSUE TITLE
[docker for mac]: custom apiServerAddress yields kubeconfig pointing to 127.0.0.1 due to docker regression

### ISSUE THREAD

**Issue by vdice** [kubernetes-sigs/kind#1732] opened 2020-07-14 18:57 UTC
Greetings!  I've been utilizing the ability to specify custom `apiServerAddress` and `apiServerPort` values as listed in https://kind.sigs.k8s.io/docs/user/configuration/#api-server

While the API Server's listening address indeed appears updated (API server communication is successful after manual updates mentioned below), neither variant of the resulting kubeconfig has a `server` value that uses the custom settings.

With kind version `kind v0.9.0-alpha+2b0b8c07769f88 go1.15beta1 darwin/amd64`, say I set the aforementioned values to:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 10.0.1.4
  apiServerPort: 6443
```

and create the cluster as usual (`kind create cluster --config kind-config.yaml`),

`kind get kubeconfig` has `server: https://127.0.0.1:32777` and
`kind get kubeconfig --internal` has `server: https://kind-control-plane:6443`

The first is automatically merged/placed into the `$KUBECONFIG` location, but neither work to communicate with the cluster.

Only after manually updating the kubeconfig will communications work:

```console
 $ kubectl config view -o json | jq -r '.clusters[0].cluster.server'
https://127.0.0.1:32778

 $ kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server 127.0.0.1:32778 was refused - did you specify the right host or port?

 $ kubectl config set clusters.kind-kind.server https://10.0.1.4:6443
Property "clusters.kind-kind.server" set.

 $ kubectl cluster-info
Kubernetes master is running at https://10.0.1.4:6443
KubeDNS is running at https://10.0.1.4:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

My question is thus: Should not the stock kubeconfig returned via `kind get kubeconfig` use a `server` address built from the provided `apiServerAddress` and `apiServerPort` values?

**Comment by BenTheElder** [comment] 2020-07-14 20:31
Hi, can you share some more details about your environment please?
It should be using those values in the default.

**Comment by vdice** [comment] 2020-07-14 20:39
Definitely.  Let me know if there is any other info that would help.

I'm seeing this behavior both with the most recent `v0.8.1` release (for osx/darwin) and a build from the latest (as of writing) source commit:
```
 $ kind version
kind v0.9.0-alpha+2b0b8c07769f88 go1.15beta1 darwin/amd64
```

As mentioned above, the config I'm using to create the cluster is:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 10.0.1.4
  apiServerPort: 6443
```

**Comment by BenTheElder** [comment] 2020-07-14 21:13
thanks, I'll look at replicating this later today, this looks like a bug.

just in case I can't reproduce based purely on kind version, can you share your container runtime info? if you're using docker the output of `docker info` is pretty helpful.

**Comment by BenTheElder** [comment] 2020-07-14 21:13
on the running cluster from this config if you can grab `docker ps` from the host as well.

**Comment by vdice** [comment] 2020-07-14 21:36
Thank you!  I've created a gist to capture the command outputs, hopefully enabling easier viewing: https://gist.github.com/vdice/c8dc7769fd50e7fc5498630f27297843

**Comment by BenTheElder** [comment] 2020-07-15 03:37
That `docker ps` definitely shows localhost:randomPort is what's being forwarded.
I naively attempted to do this on docker for mac where I instead see that the IP is not available for binding (obviously)

```
$ kind create cluster --config=$HOME/test.yaml
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.4) 🖼 
 ✗ Preparing nodes 📦  
ERROR: failed to create cluster: docker run error: command "docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --net kind --restart=on-failure:1 --publish=10.0.1.4:6443:6443/TCP kindest/node:v1.18.4@sha256:d8ff5fc405fc679dd3dd0cccc01543ba4942ed90823817d2e9e2c474a5343c4f" failed with error: exit status 125
Command Output: 93983c90e8b7fb2597f389328143050c4746c8950aa7730fb33717b15af88764
docker: Error response from daemon: Ports are not available: listen tcp 10.0.1.4:6443: bind: can't assign requested address.
```

**Comment by BenTheElder** [comment] 2020-07-15 03:44
So what kind is doing here is asking docker to forward this IP:Port to the node @ 6443 with the `--publish` flag, and then later it's querying docker for the port forwards on the nodes. Your docker output is showing the 127.0.0.1 port forward on the node.

What's weird is in your output I do see this too:
>                 "desktop.docker.io/ports/6443/tcp": "10.0.1.4:6443",

As if both `127.0.0.1:32778` and `10.0.1.4:6443` exist, but the former is the one showing up when listing the containers and reading their port forwards.

And it sounds like you're saying above that `kubectl config set clusters.kind-kind.server https://10.0.1.4:6443` worked anyhow? Are you able to e.g. list pods (`kubectl get po -A`)?

What happens if you create some trivial server container with this port? `--publish=10.0.1.4:6443:6443/TCP`? Will it succeed in your environment?

If so, maybe docker is doing the forward in some new odd way.

Can you tell me more about how docker was installed and the host machine / OS?

**Comment by BenTheElder** [comment] 2020-07-15 03:48
This looks like https://github.com/docker/for-mac/issues/4541

I think we'll have to adjust how we query for port forwards to read this undocumented label from the proprietary part of docker desktop :/

Apparently per the issue they do rewrite the ip/port passed to docker when using an external IP like this.

**Comment by BenTheElder** [comment] 2020-07-15 03:51
This seems to be a regression this year in > 2.1.X docker desktop. https://github.com/docker/for-mac/issues/4209#issuecomment-577100987

https://github.com/docker/for-mac/issues/4209#issuecomment-627336476 <-- this part is what is breaking kind, currently.

**Comment by BenTheElder** [comment] 2020-07-15 03:54
This is definitely a breakage on Docker's end, but we can and should mitigate it anyhow, there's no evidence that they intend to fix this.

**Comment by vdice** [comment] 2020-07-15 14:37
Thanks so much @BenTheElder. Indeed, the linked issue(s) definitely appear to be the culprits.  Appreciate your help on this issue.

Perhaps redundant now, but:

> Are you able to e.g. list pods (kubectl get po -A)?

Yes.  All kubectl comms w/ the api server are successful.

> What happens if you create some trivial server container with this port? 

It does succeed, with similar loopback IP listing in `PORTS` as the kind container and as is mentioned in https://github.com/docker/for-mac/issues/4541:
```
 $ docker run -d --publish=10.0.1.4:6443:6443/TCP nginx sh -c 'sleep 200'
cc403370c59650cf549e7d959778daa629a642b7d8b48154d53b709e3108571b

 $ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                               NAMES
cc403370c596        nginx                  "/docker-entrypoint.…"   3 seconds ago       Up 3 seconds        80/tcp, 127.0.0.1:32787->6443/tcp   objective_herschel
```

**Comment by BenTheElder** [comment] 2020-08-07 01:25
This is a good moderately difficult first PR.

Inside the docker provider we need to change how we lookup port mappings to inspect the container(s) and give priority to this special label if present.

**Comment by BenTheElder** [comment] 2020-08-07 01:25
I will handle it if someone else doesn't get to it first, but a lot on my plate, and non-loopback macOS is something of an unusual useage I think.

**Comment by BenTheElder** [comment] 2020-08-19 17:55
should be fixed by @vdice in https://github.com/kubernetes-sigs/kind/pull/1785

**Closed by BenTheElder** 2020-08-19 17:55 UTC
Labels: area/provider/docker, help wanted, kind/bug, kind/external, priority/important-longterm, triage/support
